--------------------------------------------------------
--  File created - Friday-October-07-2022   
--------------------------------------------------------
DROP TABLE "ACTION";
DROP TABLE "DAIBIEU";
DROP TABLE "DAIBIEU_KYHOP";
DROP TABLE "DANTOC";
DROP TABLE "DIAPHUONG";
DROP TABLE "DM_COQUAN_TINH";
DROP TABLE "DONVI_LINHVUC";
DROP TABLE "FILE_UPLOAD";
DROP TABLE "KIENNGHI_NGUONDON";
DROP TABLE "KNTC_DON";
DROP TABLE "KNTC_DON_IMPORT";
DROP TABLE "KNTC_DON_LICHSU";
DROP TABLE "KNTC_GIAMSAT";
DROP TABLE "KNTC_LOAIDON";
DROP TABLE "KNTC_LUUTHEODOI";
DROP TABLE "KNTC_NGUONDON";
DROP TABLE "KNTC_NOIDUNGDON";
DROP TABLE "KNTC_TINHCHAT";
DROP TABLE "KNTC_VANBAN";
DROP TABLE "KN_CHUONGTRINH";
DROP TABLE "KN_CHUONGTRINH_CHITIET";
DROP TABLE "KN_CHUONGTRINH_DAIBIEU";
DROP TABLE "KN_CHUONGTRINH_DIAPHUONG";
DROP TABLE "KN_CHUYENXULY";
DROP TABLE "KN_DOANGIAMSAT";
DROP TABLE "KN_DOANGIAMSAT_KIENNGHI";
DROP TABLE "KN_DOANGIAMSAT_YKIEN";
DROP TABLE "KN_GIAMSAT";
DROP TABLE "KN_GIAMSAT_DANHGIA";
DROP TABLE "KN_GIAMSAT_PHANLOAI";
DROP TABLE "KN_IMPORT";
DROP TABLE "KN_KIENNGHI";
DROP TABLE "KN_KIENNGHI_IMPORT";
DROP TABLE "KN_KIENNGHI_TRALOI";
DROP TABLE "KN_NGUONDON";
DROP TABLE "KN_TONGHOP";
DROP TABLE "KN_TRALOI_PHANLOAI";
DROP TABLE "KN_TUKHOA";
DROP TABLE "KN_VANBAN";
DROP TABLE "LINHVUC";
DROP TABLE "LINHVUC_COQUAN";
DROP TABLE "LOGIN_FAIL";
DROP TABLE "NGHENGHIEP";
DROP TABLE "QUANHUYENADD";
DROP TABLE "QUOCHOI_COQUAN";
DROP TABLE "QUOCHOI_COQUAN_BACK20191005";
DROP TABLE "QUOCHOI_COQUAN_TEM";
DROP TABLE "QUOCHOI_KHOA";
DROP TABLE "QUOCHOI_KYHOP";
DROP TABLE "QUOCTICH";
DROP TABLE "TD_VUVIEC";
DROP TABLE "TD_VUVIEC_XULY";
DROP TABLE "TIEPDAN_DINHKY";
DROP TABLE "TIEPDAN_DINHKY_LOAIVUVIEC";
DROP TABLE "TIEPDAN_DINHKY_VUVIEC";
DROP TABLE "TIEPDAN_THUONGXUYEN";
DROP TABLE "TIEPDAN_THUONGXUYEN_KETQUA";
DROP TABLE "TOKEN";
DROP TABLE "TRACKING";
DROP TABLE "USERS";
DROP TABLE "USER_ACTION";
DROP TABLE "USER_CHUCVU";
DROP TABLE "USER_GROUP";
DROP TABLE "USER_GROUP_ACTION";
DROP TABLE "USER_PHONGBAN";
DROP TABLE "USER_TYPE";
DROP TABLE "VB_DONVI_VANBAN";
DROP TABLE "VB_FILE_VANBAN";
DROP TABLE "VB_LOAI";
DROP TABLE "VB_VANBAN";
--------------------------------------------------------
--  DDL for Table ACTION
--------------------------------------------------------

  CREATE TABLE "ACTION" 
   (	"IACTION" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IPARENT" NUMBER(*,0), 
	"IVITRI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table DAIBIEU
--------------------------------------------------------

  CREATE TABLE "DAIBIEU" 
   (	"IDAIBIEU" NUMBER, 
	"ITRUONGDOAN" NUMBER, 
	"CTEN" NVARCHAR2(350), 
	"IDIAPHUONG" NUMBER, 
	"CEMAIL" VARCHAR2(530 BYTE), 
	"CSDT" VARCHAR2(20 BYTE), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER(*,0), 
	"IVITRI" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IGIOITINH" NUMBER, 
	"DNGAYSINH" DATE, 
	"CDOANDB" VARCHAR2(2000 BYTE), 
	"CNOILAMVIEC" VARCHAR2(2000 BYTE), 
	"CCHUCVUDAYDU" VARCHAR2(2000 BYTE), 
	"CCOQUAN" VARCHAR2(2000 BYTE), 
	"ILOAIDAIBIEU" NUMBER DEFAULT 0, 
	"CDONVIBAUCUSO" VARCHAR2(255 BYTE), 
	"ITOTRUONG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table DAIBIEU_KYHOP
--------------------------------------------------------

  CREATE TABLE "DAIBIEU_KYHOP" 
   (	"ID" NUMBER, 
	"ID_KYHOP" NUMBER, 
	"ID_DAIBIEU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;

   COMMENT ON TABLE "DAIBIEU_KYHOP"  IS ' Do ??i bi?u ch? tính theo khoá nên b?ng DAIBIEU_KYHOP th?c t? là DAIBIEU_KHOA, chuy?n ID_KYHOP thành ID_KHOA ';
--------------------------------------------------------
--  DDL for Table DANTOC
--------------------------------------------------------

  CREATE TABLE "DANTOC" 
   (	"IDANTOC" NUMBER(*,0), 
	"CTEN" VARCHAR2(1000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table DIAPHUONG
--------------------------------------------------------

  CREATE TABLE "DIAPHUONG" 
   (	"IDIAPHUONG" NUMBER(*,0), 
	"CTEN" VARCHAR2(50 BYTE), 
	"CTYPE" VARCHAR2(50 BYTE), 
	"IPARENT" NUMBER(*,0), 
	"CCODE" VARCHAR2(50 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table DM_COQUAN_TINH
--------------------------------------------------------

  CREATE TABLE "DM_COQUAN_TINH" 
   (	"ID_COQUAN" NUMBER, 
	"CODE_COQUAN" VARCHAR2(200 BYTE), 
	"TEN_COQUAN" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table DONVI_LINHVUC
--------------------------------------------------------

  CREATE TABLE "DONVI_LINHVUC" 
   (	"ID" NUMBER, 
	"IDONVI" NUMBER, 
	"ILINHVUC" NUMBER, 
	"IDELETE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table FILE_UPLOAD
--------------------------------------------------------

  CREATE TABLE "FILE_UPLOAD" 
   (	"ID_FILE" NUMBER(20,0), 
	"CFILE" VARCHAR2(4000 BYTE), 
	"ID" NUMBER(20,0), 
	"CTYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KIENNGHI_NGUONDON
--------------------------------------------------------

  CREATE TABLE "KIENNGHI_NGUONDON" 
   (	"ID" NUMBER, 
	"IKIENNGHI" NUMBER, 
	"INGUONDON" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_DON
--------------------------------------------------------

  CREATE TABLE "KNTC_DON" 
   (	"IDON" NUMBER(*,0), 
	"IDONTRUNG" NUMBER(*,0), 
	"ILOAIDON" NUMBER(*,0), 
	"ITINHCHAT" NUMBER(*,0), 
	"INGUONDON" NUMBER(*,0), 
	"INOIDUNG" NUMBER(*,0), 
	"ITHAMQUYEN" NUMBER(*,0), 
	"ITHULY" NUMBER(*,0), 
	"IDONVITHULY" NUMBER(*,0), 
	"ITINHTRANGXULY" NUMBER(*,0), 
	"DNGAYNHAN" DATE, 
	"IDIAPHUONG_0" NUMBER(*,0), 
	"IDIAPHUONG_1" NUMBER(*,0), 
	"IDIAPHUONG_2" NUMBER(*,0), 
	"CNGUOIGUI_TEN" VARCHAR2(4000 BYTE), 
	"CNGUOIGUI_DIACHI" VARCHAR2(4000 BYTE), 
	"CNGUOIGUI_CMND" VARCHAR2(4000 BYTE), 
	"IDOANDONGNGUOI" NUMBER(*,0), 
	"ISONGUOI" NUMBER(*,0), 
	"CDIACHI_VUVIEC" VARCHAR2(4000 BYTE), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"CFILE" VARCHAR2(4000 BYTE), 
	"ITINHTRANG_NOIBO" NUMBER(*,0), 
	"ITINHTRANG_DONVIXULY" NUMBER(*,0), 
	"DDATE" DATE, 
	"IUSER" NUMBER(*,0), 
	"IUSER_GIAOXULY" NUMBER(*,0), 
	"CMADON" VARCHAR2(4000 BYTE), 
	"INGUOIGUI_QUOCTICH" NUMBER(*,0), 
	"INGUOIGUI_DANTOC" NUMBER(*,0), 
	"IUSER_DUOCGIAOXULY" NUMBER(*,0), 
	"IDUDIEUKIEN" NUMBER(*,0), 
	"IDUDIEUKIEN_KETQUA" NUMBER(*,0), 
	"ILINHVUC" NUMBER(*,0), 
	"ILUUTHEODOI" NUMBER(*,0), 
	"CLUUTHEODOI_LYDO" VARCHAR2(4000 BYTE), 
	"ISOLUONGTRUNG" NUMBER, 
	"IDOMAT" NUMBER, 
	"IDOKHAN" NUMBER, 
	"CGHICHU" VARCHAR2(4000 BYTE), 
	"IDONVITIEPNHAN" NUMBER, 
	"IDANHGIA" NUMBER, 
	"CGHICHUDANHGIA" VARCHAR2(4000 BYTE), 
	"IDELETE" NUMBER, 
	"IIDIMPORT" NUMBER, 
	"IDOITUONGGUI" NUMBER DEFAULT 0, 
	"CHITIETLYDO_LUUTHEODOI" NVARCHAR2(250), 
	"GHICHU_XULY" NVARCHAR2(250), 
	"ICANHBAO" NUMBER DEFAULT NULL, 
	"INGAYQUYDINH" DATE DEFAULT NULL, 
	"IKHOA" NUMBER, 
	"ICHITIETLYDOLUUDON" NUMBER, 
	"IPLSONGUOI" NUMBER, 
	"CNGUOIGUI_SDT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_DON_IMPORT
--------------------------------------------------------

  CREATE TABLE "KNTC_DON_IMPORT" 
   (	"ID" NUMBER, 
	"IUSER" NUMBER, 
	"DDATE" DATE, 
	"CGHICHU" NVARCHAR2(2000), 
	"CFILE" NVARCHAR2(2000), 
	"ISODON" NUMBER, 
	"ITINHTRANG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_DON_LICHSU
--------------------------------------------------------

  CREATE TABLE "KNTC_DON_LICHSU" 
   (	"ID" NUMBER, 
	"IDON" NUMBER, 
	"IDONVIGUI" NUMBER, 
	"IDONVITIEPNHAN" NUMBER, 
	"DNGAYCHUYEN" DATE, 
	"IUSER" NUMBER, 
	"ITRANGTHAI" NUMBER, 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"ICHUYENXULY" NUMBER, 
	"IDONVIXULY" NUMBER, 
	"IVANBAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_GIAMSAT
--------------------------------------------------------

  CREATE TABLE "KNTC_GIAMSAT" 
   (	"IGIAMSAT" NUMBER(*,0), 
	"IDON" NUMBER(*,0), 
	"IDONVI" NUMBER(*,0), 
	"CKEHOACH" VARCHAR2(4000 BYTE), 
	"CCHUYENDE" VARCHAR2(4000 BYTE), 
	"CNOIDUNG" CLOB, 
	"CFILE" VARCHAR2(50 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CNOIDUNG") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table KNTC_LOAIDON
--------------------------------------------------------

  CREATE TABLE "KNTC_LOAIDON" 
   (	"ILOAIDON" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"IMALOAIDON" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER, 
	"IPARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_LUUTHEODOI
--------------------------------------------------------

  CREATE TABLE "KNTC_LUUTHEODOI" 
   (	"ID" NUMBER, 
	"CTEN" NVARCHAR2(250), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_NGUONDON
--------------------------------------------------------

  CREATE TABLE "KNTC_NGUONDON" 
   (	"INGUONDON" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"INHOMDONVI" NUMBER, 
	"IMANGUONDON" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER, 
	"IPARENT" NUMBER, 
	"ILOAI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_NOIDUNGDON
--------------------------------------------------------

  CREATE TABLE "KNTC_NOIDUNGDON" 
   (	"INOIDUNG" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"ILINHVUC" NUMBER, 
	"IMANOIDUNG" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_TINHCHAT
--------------------------------------------------------

  CREATE TABLE "KNTC_TINHCHAT" 
   (	"ITINHCHAT" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"INHOMNOIDUNG" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KNTC_VANBAN
--------------------------------------------------------

  CREATE TABLE "KNTC_VANBAN" 
   (	"IVANBAN" NUMBER(*,0), 
	"CSOVANBAN" VARCHAR2(50 BYTE), 
	"DNGAYBANHANH" DATE, 
	"CNGUOIKY" VARCHAR2(200 BYTE), 
	"CNOIDUNG" CLOB, 
	"CFILE" VARCHAR2(4000 BYTE), 
	"ICOQUANBANHANH" NUMBER(*,0), 
	"ICOQUANNHAN" NUMBER(*,0), 
	"IDON" NUMBER(*,0), 
	"CLOAI" VARCHAR2(50 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"CCOQUANCHUYENDEN" VARCHAR2(1000 BYTE), 
	"CNOINHAN" VARCHAR2(1000 BYTE), 
	"CCHUCVU" VARCHAR2(300 BYTE), 
	"GHICHU_XULY" NVARCHAR2(250), 
	"GHICHU" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"THOIGIANBC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CNOIDUNG") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table KN_CHUONGTRINH
--------------------------------------------------------

  CREATE TABLE "KN_CHUONGTRINH" 
   (	"ICHUONGTRINH" NUMBER(*,0), 
	"IKYHOP" NUMBER(*,0), 
	"ITRUOCKYHOP" NUMBER(*,0), 
	"DBATDAU" DATE, 
	"DKETTHUC" DATE, 
	"CKEHOACH" VARCHAR2(4000 BYTE), 
	"CNOIDUNG" CLOB, 
	"CFILE" VARCHAR2(4000 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"IDONVI" NUMBER, 
	"CDIACHI" VARCHAR2(4000 BYTE), 
	"IKHOA" NUMBER DEFAULT 0, 
	"IDOITUONG" NUMBER DEFAULT 0, 
	"DNGAYBANHANH" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CNOIDUNG") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table KN_CHUONGTRINH_CHITIET
--------------------------------------------------------

  CREATE TABLE "KN_CHUONGTRINH_CHITIET" 
   (	"ID" NUMBER(*,0), 
	"ICHUONGTRINH" NUMBER(*,0), 
	"ITODAIBIEU" NUMBER(*,0), 
	"IDIAPHUONG" NUMBER(*,0), 
	"CDIACHI" NVARCHAR2(1000), 
	"DNGAYTIEP" DATE, 
	"IDIAPHUONG2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KN_CHUONGTRINH_DAIBIEU
--------------------------------------------------------

  CREATE TABLE "KN_CHUONGTRINH_DAIBIEU" 
   (	"ID" NUMBER(20,0), 
	"ICHUONGTRINH" NUMBER(*,0), 
	"IUSER_DAIBIEU" NUMBER(*,0), 
	"IUSER_COQUAN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_CHUONGTRINH_DIAPHUONG
--------------------------------------------------------

  CREATE TABLE "KN_CHUONGTRINH_DIAPHUONG" 
   (	"ID" NUMBER(20,0), 
	"IDIAPHUONG0" NUMBER(*,0), 
	"IDIAPHUONG1" NUMBER(*,0), 
	"ICHUONGTRINH" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_CHUYENXULY
--------------------------------------------------------

  CREATE TABLE "KN_CHUYENXULY" 
   (	"IKN_CHUYENXULY" NUMBER, 
	"ITONGHOP" NUMBER, 
	"INGUOICHUYEN" NUMBER, 
	"INGUOINHAN" NUMBER, 
	"IDONVI" NUMBER, 
	"CNOIDUNG" VARCHAR2(250 BYTE), 
	"DDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_DOANGIAMSAT
--------------------------------------------------------

  CREATE TABLE "KN_DOANGIAMSAT" 
   (	"IDOAN" NUMBER, 
	"IUSER" NUMBER, 
	"DDATE" DATE, 
	"CTEN" VARCHAR2(2000 BYTE), 
	"CNOIDUNG" VARCHAR2(2000 BYTE), 
	"IKYHOP" NUMBER, 
	"IDONVI" NUMBER, 
	"DNGAYBATDAU" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_DOANGIAMSAT_KIENNGHI
--------------------------------------------------------

  CREATE TABLE "KN_DOANGIAMSAT_KIENNGHI" 
   (	"ID" NUMBER, 
	"IKIENNGHI" NUMBER, 
	"IDOANGIAMSAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_DOANGIAMSAT_YKIEN
--------------------------------------------------------

  CREATE TABLE "KN_DOANGIAMSAT_YKIEN" 
   (	"IYKIEN" NUMBER, 
	"CTEN" VARCHAR2(2000 BYTE), 
	"IDOANGIAMSAT" NUMBER, 
	"CNOIDUNG" VARCHAR2(2000 BYTE), 
	"IUSER" NUMBER, 
	"DDATE" DATE, 
	"DNGAYLAMVIEC" DATE, 
	"IKIENNGHI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_GIAMSAT
--------------------------------------------------------

  CREATE TABLE "KN_GIAMSAT" 
   (	"IGIAMSAT" NUMBER(20,0), 
	"IKIENNGHI" NUMBER(20,0), 
	"IPHANLOAI" NUMBER(*,0), 
	"IDANHGIA" NUMBER(*,0), 
	"IDUNGTIENDO" NUMBER(*,0), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"IDONGKIENNGHI" NUMBER(*,0), 
	"ITRALOI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_GIAMSAT_DANHGIA
--------------------------------------------------------

  CREATE TABLE "KN_GIAMSAT_DANHGIA" 
   (	"IDANHGIA" NUMBER(*,0), 
	"CTEN" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_GIAMSAT_PHANLOAI
--------------------------------------------------------

  CREATE TABLE "KN_GIAMSAT_PHANLOAI" 
   (	"IPHANLOAI" NUMBER(*,0), 
	"CTEN" NVARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_IMPORT
--------------------------------------------------------

  CREATE TABLE "KN_IMPORT" 
   (	"ID" NUMBER, 
	"IUSER" NUMBER, 
	"DDATE" DATE, 
	"CGHICHU" NVARCHAR2(2000), 
	"CFILE" NVARCHAR2(2000), 
	"IKYHOP" NUMBER, 
	"ISOKIENNGHI" NUMBER, 
	"ITRUOCKYHOP" NUMBER, 
	"ITINHTRANG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_KIENNGHI
--------------------------------------------------------

  CREATE TABLE "KN_KIENNGHI" 
   (	"IKIENNGHI" NUMBER(20,0), 
	"IKYHOP" NUMBER(*,0), 
	"IDONVITIEPNHAN" NUMBER(*,0), 
	"ITHAMQUYENDONVI" NUMBER(*,0), 
	"ILINHVUC" NUMBER(*,0), 
	"ICHUONGTRINH" NUMBER(*,0), 
	"ITRUOCKYHOP" NUMBER(*,0), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"CTUKHOA" VARCHAR2(4000 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"IKIEMTRATRUNG" NUMBER(*,0), 
	"IKIENNGHI_TRUNG" NUMBER(*,0), 
	"ITINHTRANG" NUMBER(*,0), 
	"ITONGHOP" NUMBER(*,0), 
	"CMAKIENNGHI" VARCHAR2(4000 BYTE), 
	"CFILE" VARCHAR2(4000 BYTE), 
	"ITONGHOP_BDN" NUMBER, 
	"CNOIDUNG_TRUNG" VARCHAR2(4000 BYTE), 
	"ID_KIENNGHI_PARENT" NUMBER, 
	"IPARENT" NUMBER, 
	"IDANG" NUMBER(1,0), 
	"CDIACHI" VARCHAR2(4000 BYTE), 
	"IDIAPHUONG0" NUMBER, 
	"IDIAPHUONG1" NUMBER, 
	"ID_GOP" NUMBER, 
	"ID_IMPORT" NUMBER, 
	"IDELETE" NUMBER, 
	"INGUONKIENNGHI" NUMBER, 
	"IDOITUONGGUI" NUMBER, 
	"ICANHBAO" NUMBER DEFAULT NULL, 
	"INGAYQUYDINH" DATE DEFAULT NULL, 
	"CGHICHU" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;

   COMMENT ON TABLE "KN_KIENNGHI"  IS '// 0: M?i c?p nh?t
        // 1: ?ã chuy?n ??a ph??ng x? lý
        // 2: ?ã chuy?n t?ng h?p ??n BDN
        // 3: BDN ?ã chuy?n c? quan th?m quy?n
        // 4: ?ang x? lý
        // 5: t?ng h?p ?ã có tr? l?i
        // 6: ki?n ngh? ?ã có tr? l?i, ?óng ki?n ngh?
        // 7: ki?n ngh? trùng, ?óng ki?n ngh?
        // 8: theo dõi ? k? h?p sau
        // 9: ?ã tr? l?i ki?n ngh? 
';
--------------------------------------------------------
--  DDL for Table KN_KIENNGHI_IMPORT
--------------------------------------------------------

  CREATE TABLE "KN_KIENNGHI_IMPORT" 
   (	"ID" NUMBER, 
	"IDONVITIEPNHAN" NUMBER, 
	"DNGAYBANHANH" DATE, 
	"CNOIDUNG" CLOB, 
	"CCONGVAN" NVARCHAR2(200), 
	"CSOCONGVAN" NVARCHAR2(200), 
	"IDONVITHAMQUYEN" NUMBER, 
	"ILINHVUC" NUMBER, 
	"ID_KIENNGHI" NUMBER, 
	"ID_TONGHOP_BDN" NUMBER, 
	"ID_IMPORT" NUMBER, 
	"IKYHOP" NUMBER, 
	"ITRUOCKYHOP" NUMBER, 
	"ICHUONGTRINH" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CNOIDUNG") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table KN_KIENNGHI_TRALOI
--------------------------------------------------------

  CREATE TABLE "KN_KIENNGHI_TRALOI" 
   (	"ITRALOI" NUMBER(20,0), 
	"IKIENNGHI" NUMBER(20,0), 
	"CTRALOI" CLOB, 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"CFILE" VARCHAR2(4000 BYTE), 
	"CLOTRINH" VARCHAR2(2000 BYTE), 
	"ITINHTRANG" NUMBER, 
	"DNGAY_DUKIEN" DATE, 
	"IPHANLOAI" NUMBER, 
	"DNGAYBANHANH" DATE, 
	"CSOVANBAN" VARCHAR2(300 BYTE), 
	"CNGUOIKY" VARCHAR2(200 BYTE), 
	"CCOQUANTRALOI" VARCHAR2(500 BYTE), 
	"ICOQUANTRALOI" NUMBER, 
	"GHICHU_KQ" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CTRALOI") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table KN_NGUONDON
--------------------------------------------------------

  CREATE TABLE "KN_NGUONDON" 
   (	"INGUONDON" NUMBER, 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER, 
	"INHOMDONVI" NUMBER, 
	"IMANGUONDON" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER, 
	"IPARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_TONGHOP
--------------------------------------------------------

  CREATE TABLE "KN_TONGHOP" 
   (	"ITONGHOP" NUMBER(*,0), 
	"IDONVITONGHOP" NUMBER(*,0), 
	"IKYHOP" NUMBER(*,0), 
	"ITRUOCKYHOP" NUMBER(*,0), 
	"ICHUONGTRINH" NUMBER(*,0), 
	"ITHAMQUYENDONVI" NUMBER(*,0), 
	"ILINHVUC" NUMBER(*,0), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"CTUKHOA" VARCHAR2(4000 BYTE), 
	"CFILE" VARCHAR2(4000 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"ITINHTRANG" NUMBER(*,0), 
	"CMATONGHOP" VARCHAR2(50 BYTE), 
	"ID_IMPORT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_TRALOI_PHANLOAI
--------------------------------------------------------

  CREATE TABLE "KN_TRALOI_PHANLOAI" 
   (	"IPHANLOAI" NUMBER, 
	"IPARENT" NUMBER, 
	"CTEN" VARCHAR2(2000 BYTE), 
	"IHIENTHI" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IDELETE" NUMBER, 
	"IVITRI" NUMBER, 
	"ITINHTRANG" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_TUKHOA
--------------------------------------------------------

  CREATE TABLE "KN_TUKHOA" 
   (	"ID" NUMBER(*,0), 
	"CTUKHOA" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table KN_VANBAN
--------------------------------------------------------

  CREATE TABLE "KN_VANBAN" 
   (	"IVANBAN" NUMBER(*,0), 
	"CSOVANBAN" VARCHAR2(50 BYTE), 
	"DNGAYBANHANH" DATE, 
	"CNGUOIKY" VARCHAR2(4000 BYTE), 
	"CNOIDUNG" CLOB, 
	"CFILE" VARCHAR2(4000 BYTE), 
	"ICOQUANBANHANH" NUMBER(*,0), 
	"ICOQUANNHAN" NUMBER(*,0), 
	"IKIENNGHI" NUMBER(*,0), 
	"ITONGHOP" NUMBER(*,0), 
	"CLOAI" VARCHAR2(50 BYTE), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"DNGAYDUKIENHOANTHANH" DATE, 
	"DNGAYBAOCAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CNOIDUNG") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LINHVUC
--------------------------------------------------------

  CREATE TABLE "LINHVUC" 
   (	"ILINHVUC" NUMBER(*,0), 
	"IPARENT" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"CCODE" VARCHAR2(1000 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"INHOM" NUMBER, 
	"ILOAIDON" NUMBER, 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table LINHVUC_COQUAN
--------------------------------------------------------

  CREATE TABLE "LINHVUC_COQUAN" 
   (	"ILINHVUC" NUMBER, 
	"ICOQUAN" NUMBER, 
	"CTEN" VARCHAR2(2000 BYTE), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER, 
	"CCODE" VARCHAR2(2000 BYTE), 
	"IVITRI" NUMBER, 
	"IPARENT" NUMBER DEFAULT 0, 
	"MALINHVUC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table LOGIN_FAIL
--------------------------------------------------------

  CREATE TABLE "LOGIN_FAIL" 
   (	"ID" NUMBER(*,0), 
	"IP" VARCHAR2(50 BYTE), 
	"IFAILED" NUMBER(*,0), 
	"DDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table NGHENGHIEP
--------------------------------------------------------

  CREATE TABLE "NGHENGHIEP" 
   (	"INGHENGHIEP" NUMBER, 
	"CTEN" VARCHAR2(250 BYTE), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUANHUYENADD
--------------------------------------------------------

  CREATE TABLE "QUANHUYENADD" 
   (	"TENQUANHUYEN" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCHOI_COQUAN
--------------------------------------------------------

  CREATE TABLE "QUOCHOI_COQUAN" 
   (	"ICOQUAN" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IPARENT" NUMBER(*,0), 
	"CCODE" VARCHAR2(1000 BYTE), 
	"DKETTHUC" DATE, 
	"IMACDINH" NUMBER(*,0), 
	"IDIAPHUONG" NUMBER(*,0), 
	"IGROUP" NUMBER(*,0), 
	"IVITRI" NUMBER(*,0), 
	"IUSE" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"CTYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCHOI_COQUAN_BACK20191005
--------------------------------------------------------

  CREATE TABLE "QUOCHOI_COQUAN_BACK20191005" 
   (	"ICOQUAN" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IPARENT" NUMBER(*,0), 
	"CCODE" VARCHAR2(1000 BYTE), 
	"DKETTHUC" DATE, 
	"IMACDINH" NUMBER(*,0), 
	"IDIAPHUONG" NUMBER(*,0), 
	"IGROUP" NUMBER(*,0), 
	"IVITRI" NUMBER(*,0), 
	"IUSE" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCHOI_COQUAN_TEM
--------------------------------------------------------

  CREATE TABLE "QUOCHOI_COQUAN_TEM" 
   (	"ICOQUAN" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IPARENT" NUMBER(*,0), 
	"CCODE" VARCHAR2(1000 BYTE), 
	"DKETTHUC" DATE, 
	"IMACDINH" NUMBER(*,0), 
	"IDIAPHUONG" NUMBER(*,0), 
	"IGROUP" NUMBER(*,0), 
	"IVITRI" NUMBER(*,0), 
	"IUSE" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCHOI_KHOA
--------------------------------------------------------

  CREATE TABLE "QUOCHOI_KHOA" 
   (	"IKHOA" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"DBATDAU" DATE, 
	"DKETTHUC" DATE, 
	"IMACDINH" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER, 
	"ILOAI" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCHOI_KYHOP
--------------------------------------------------------

  CREATE TABLE "QUOCHOI_KYHOP" 
   (	"IKYHOP" NUMBER(*,0), 
	"IKHOA" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"DBATDAU" DATE, 
	"DKETTHUC" DATE, 
	"IMACDINH" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table QUOCTICH
--------------------------------------------------------

  CREATE TABLE "QUOCTICH" 
   (	"IQUOCTICH" NUMBER(*,0), 
	"CTEN" VARCHAR2(500 BYTE), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TD_VUVIEC
--------------------------------------------------------

  CREATE TABLE "TD_VUVIEC" 
   (	"IVUVIEC" NUMBER, 
	"IVUVIECTRUNG" NUMBER, 
	"ILOAIDON" NUMBER, 
	"ITINHCHAT" NUMBER, 
	"INGUONDON" NUMBER, 
	"INOIDUNG" NUMBER, 
	"IDINHKY" NUMBER, 
	"IDONVITIEPNHAN" NUMBER, 
	"ITINHTRANGXULY" NUMBER, 
	"DNGAYNHAN" DATE, 
	"IDIAPHUONG_0" NUMBER, 
	"IDIAPHUONG_1" NUMBER, 
	"CNGUOIGUI_TEN" VARCHAR2(2000 BYTE), 
	"CNGUOIGUI_DIACHI" VARCHAR2(2000 BYTE), 
	"IDOANDONGNGUOI" NUMBER, 
	"ISONGUOI" NUMBER, 
	"CNOIDUNG" NVARCHAR2(2000), 
	"DDATE" TIMESTAMP (6), 
	"IUSER" NUMBER, 
	"CMADON" NVARCHAR2(40), 
	"INGUOIGUI_QUOCTICH" NUMBER, 
	"INGUOIGUI_DANTOC" NUMBER, 
	"ILINHVUC" NUMBER, 
	"IKNTC_DON" NUMBER, 
	"CNGUOITIEP" VARCHAR2(200 BYTE), 
	"IDONVI" NUMBER, 
	"IDONDOC" NUMBER, 
	"IGIAMSAT" NUMBER, 
	"CYKIENGIAMSAT" VARCHAR2(4000 BYTE), 
	"ISOLUONGTRUNG" NUMBER, 
	"CLYDOTRUNG" VARCHAR2(4000 BYTE), 
	"CDIADIEM" VARCHAR2(2000 BYTE), 
	"ITIEPDOTXUAT" NUMBER, 
	"ILANHDAOTIEP" NUMBER, 
	"CNOIDUNGCHIDAO" VARCHAR2(4000 BYTE), 
	"IDELETE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TD_VUVIEC_XULY
--------------------------------------------------------

  CREATE TABLE "TD_VUVIEC_XULY" 
   (	"IXULY" NUMBER, 
	"CSOVANBAN" VARCHAR2(500 BYTE), 
	"DNGAYXULY" DATE, 
	"CNGUOIXULY" VARCHAR2(500 BYTE), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"ICOQUANBANHANH" NUMBER, 
	"ICOQUANNHAN" NUMBER, 
	"IVUVIEC" NUMBER, 
	"CLOAI" VARCHAR2(2000 BYTE), 
	"IUSER" NUMBER, 
	"DNGAYLUU" DATE, 
	"CKINHGUI" VARCHAR2(4000 BYTE), 
	"CNOINHAN" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TIEPDAN_DINHKY
--------------------------------------------------------

  CREATE TABLE "TIEPDAN_DINHKY" 
   (	"IDINHKY" NUMBER(*,0), 
	"ILUOT" NUMBER(*,0), 
	"IVUVIEC" NUMBER(*,0), 
	"IDOAN" NUMBER(*,0), 
	"DNGAYTIEP" DATE, 
	"DDATE" DATE, 
	"IUSER" NUMBER(*,0), 
	"CDIADIEM" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TIEPDAN_DINHKY_LOAIVUVIEC
--------------------------------------------------------

  CREATE TABLE "TIEPDAN_DINHKY_LOAIVUVIEC" 
   (	"ID" NUMBER(20,0), 
	"IDINHKY" NUMBER(*,0), 
	"ILOAIDON" NUMBER(*,0), 
	"IVALUE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TIEPDAN_DINHKY_VUVIEC
--------------------------------------------------------

  CREATE TABLE "TIEPDAN_DINHKY_VUVIEC" 
   (	"IVUVIEC" NUMBER(20,0), 
	"IDINHKY" NUMBER(*,0), 
	"CNGUOITIEP" VARCHAR2(1000 BYTE), 
	"CNGUOIGUI_TEN" VARCHAR2(1000 BYTE), 
	"CNGUOIGUI_DIACHI" VARCHAR2(4000 BYTE), 
	"IDOAN" NUMBER(*,0), 
	"IDOAN_NGUOI" NUMBER(*,0), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"ILOAI" NUMBER(*,0), 
	"ILINHVUC" NUMBER(*,0), 
	"INOIDUNG" NUMBER(*,0), 
	"ITINHCHAT" NUMBER(*,0), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"CTRALOI" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TIEPDAN_THUONGXUYEN
--------------------------------------------------------

  CREATE TABLE "TIEPDAN_THUONGXUYEN" 
   (	"ITHUONGXUYEN" NUMBER(20,0), 
	"DNGAYTIEP" DATE, 
	"CDIADIEM" VARCHAR2(4000 BYTE), 
	"ICOQUANTIEPDAN" NUMBER(*,0), 
	"CNGUOITIEP" VARCHAR2(1000 BYTE), 
	"CNGUOIGUI_TEN" VARCHAR2(1000 BYTE), 
	"CNGUOIGUI_DIACHI" VARCHAR2(4000 BYTE), 
	"IDOAN" NUMBER(*,0), 
	"IDOAN_NGUOI" NUMBER(*,0), 
	"CNOIDUNG" VARCHAR2(4000 BYTE), 
	"ILOAI" NUMBER(*,0), 
	"ILINHVUC" NUMBER(*,0), 
	"INOIDUNG" NUMBER(*,0), 
	"ITINHCHAT" NUMBER(*,0), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"CCODE" VARCHAR2(50 BYTE), 
	"ITHUONGXUYEN_TRUNG" NUMBER, 
	"IKIEMTRUNG" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TIEPDAN_THUONGXUYEN_KETQUA
--------------------------------------------------------

  CREATE TABLE "TIEPDAN_THUONGXUYEN_KETQUA" 
   (	"IKETQUA" NUMBER(20,0), 
	"ITHUONGXUYEN" NUMBER(20,0), 
	"CKETQUA" VARCHAR2(4000 BYTE), 
	"CKETQUA_NGUOITRALOI" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TOKEN
--------------------------------------------------------

  CREATE TABLE "TOKEN" 
   (	"ID" NUMBER, 
	"CONTROLLER" VARCHAR2(50 BYTE), 
	"IUSER" NUMBER, 
	"DTIME" DATE, 
	"TOKENACTION" VARCHAR2(500 BYTE), 
	"CSALT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table TRACKING
--------------------------------------------------------

  CREATE TABLE "TRACKING" 
   (	"ID" NUMBER(20,0), 
	"IUSER" NUMBER(*,0), 
	"DDATE" DATE, 
	"CACTION" VARCHAR2(2000 BYTE), 
	"IDON" NUMBER(*,0), 
	"IKIENNGHI" NUMBER(*,0), 
	"ITONGHOP" NUMBER(*,0), 
	"ITIEPDAN_DINHKY" NUMBER(*,0), 
	"ITIEPDAN_THUONGXUYEN" NUMBER(*,0), 
	"IVANBAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"IUSER" NUMBER(*,0), 
	"CUSERNAME" VARCHAR2(500 BYTE), 
	"CPASSWORD" VARCHAR2(4000 BYTE), 
	"CTEN" VARCHAR2(500 BYTE), 
	"IPHONGBAN" NUMBER(*,0), 
	"CEMAIL" VARCHAR2(500 BYTE), 
	"CSDT" VARCHAR2(500 BYTE), 
	"ISTATUS" NUMBER(*,0), 
	"IDONVI" NUMBER(*,0), 
	"ICHUCVU" NUMBER(*,0), 
	"CARRGROUP" VARCHAR2(2000 BYTE), 
	"ITYPE" NUMBER(*,0), 
	"CSALT" VARCHAR2(2000 BYTE), 
	"DLASTCHANGEPASS" DATE, 
	"CAUTHTOKEN" VARCHAR2(4000 BYTE), 
	"ILOGINFAIL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USER_ACTION
--------------------------------------------------------

  CREATE TABLE "USER_ACTION" 
   (	"ID" NUMBER(20,0), 
	"IUSER" NUMBER(*,0), 
	"IACTION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USER_CHUCVU
--------------------------------------------------------

  CREATE TABLE "USER_CHUCVU" 
   (	"ICHUCVU" NUMBER(*,0), 
	"CTEN" VARCHAR2(500 BYTE), 
	"IDELETE" NUMBER, 
	"CCODE" VARCHAR2(250 BYTE), 
	"IVITRI" NUMBER, 
	"IPHONGBAN" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USER_GROUP
--------------------------------------------------------

  CREATE TABLE "USER_GROUP" 
   (	"IGROUP" NUMBER(*,0), 
	"CTEN" VARCHAR2(2000 BYTE), 
	"CMOTA" CLOB, 
	"IDELETE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" 
 LOB ("CMOTA") STORE AS BASICFILE (
  TABLESPACE "KIENNGHI_THA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USER_GROUP_ACTION
--------------------------------------------------------

  CREATE TABLE "USER_GROUP_ACTION" 
   (	"ID" NUMBER(20,0), 
	"IGROUP" NUMBER(*,0), 
	"IACTION" NUMBER(*,0), 
	"IDELETE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USER_PHONGBAN
--------------------------------------------------------

  CREATE TABLE "USER_PHONGBAN" 
   (	"IPHONGBAN" NUMBER(*,0), 
	"IDONVI" NUMBER(*,0), 
	"CTEN" VARCHAR2(4000 BYTE), 
	"IVITRI" NUMBER(*,0), 
	"IHIENTHI" NUMBER(*,0), 
	"IDELETE" NUMBER(*,0), 
	"IPARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table USER_TYPE
--------------------------------------------------------

  CREATE TABLE "USER_TYPE" 
   (	"ITYPE" NUMBER(*,0), 
	"CNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table VB_DONVI_VANBAN
--------------------------------------------------------

  CREATE TABLE "VB_DONVI_VANBAN" 
   (	"ID" NUMBER, 
	"IVANBAN" NUMBER, 
	"IDONVI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table VB_FILE_VANBAN
--------------------------------------------------------

  CREATE TABLE "VB_FILE_VANBAN" 
   (	"IFILE" NUMBER, 
	"IVANBAN" NUMBER, 
	"CURL" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table VB_LOAI
--------------------------------------------------------

  CREATE TABLE "VB_LOAI" 
   (	"ILOAI" NUMBER, 
	"CTEN" VARCHAR2(250 BYTE), 
	"CCODE" VARCHAR2(250 BYTE), 
	"IHIENTHI" NUMBER, 
	"IDELETE" NUMBER, 
	"IVITRI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
--------------------------------------------------------
--  DDL for Table VB_VANBAN
--------------------------------------------------------

  CREATE TABLE "VB_VANBAN" 
   (	"IVANBAN" NUMBER, 
	"CTIEUDE" VARCHAR2(250 BYTE), 
	"CTRICHYEU" VARCHAR2(250 BYTE), 
	"IHIENTHI" NUMBER, 
	"ILINHVUC" NUMBER, 
	"ILOAI" NUMBER, 
	"DDATE" DATE, 
	"IUSER" NUMBER, 
	"DDATECREATE" DATE, 
	"IUSERDUYET" NUMBER, 
	"IKYHOP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KIENNGHI_THA" ;
