CREATE OR REPLACE
PACKAGE BODY "PKG_TD_VUVIEC" AS

  PROCEDURE PRC_PHANTRANG_TIEPDANVUVIEC(res out sys_refcursor) AS
  BEGIN
   Open res for

              SELECT 
              TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               INNER JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
                LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
                 ORDER BY TD_VUVIEC.DNGAYNHAN;

  END PRC_PHANTRANG_TIEPDANVUVIEC;

  PROCEDURE PRC_TIEPDAN_VUVIEC_TRACUU(res out sys_refcursor, NGAYBATDAU in date,
                                                    NGAYKETHUC IN date,
                                                    IDOANDONGNGUOITRACUU in INT,
                                                    ICOQUANTIEP in INT,
                                                    CTENCONGDAN in NVARCHAR2,
                                                    CDIACHI IN  NVARCHAR2,
                                                    CTOMTAT IN NVARCHAR2,
                                                    ILOAIDONTRACUU IN INT,
                                                    ILINHVUCTRACUU IN INT,
                                                    INHOMNOIDUNGTRACUU IN INT,
                                                    ITINHCHATVUVIEC IN INT,
                                                    ITINHTRANGXULYTRACUU IN INT,
                                                    IKIEMTRUNG IN INT,ILOAIVUVIEC IN INT,TIEPDOTXUAT IN INT,NGUOIDUNG IN INT) AS
  BEGIN
    -- TODO: Implementation required for PROCEDURE PKG_TD_VUVIEC.PRC_TIEPDAN_VUVIEC_TRACUU
    Open res for


    SELECT TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              NHOMLINHVUC.CTEN AS TENLINHVUC,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               LEFT JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
              LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
              LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
              WHERE to_date(TD_VUVIEC.DNGAYNHAN) >=  NGAYBATDAU  AND to_date(TD_VUVIEC.DNGAYNHAN) <=  NGAYKETHUC
                AND (UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTENCONGDAN) || '%' OR TD_VUVIEC.CNGUOIGUI_TEN IS NULL)
                AND (UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTOMTAT) || '%' OR TD_VUVIEC.CNOIDUNG IS NULL)
                 AND( UPPER(TD_VUVIEC.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(CDIACHI) || '%'  OR TD_VUVIEC.CNGUOIGUI_DIACHI IS NULL)
                 AND (TD_VUVIEC.IDONVI = ICOQUANTIEP OR ICOQUANTIEP = -1)
                 AND (TD_VUVIEC.ILOAIDON = ILOAIDONTRACUU OR ILOAIDONTRACUU = -1)
                 AND (TD_VUVIEC.ILINHVUC = ILINHVUCTRACUU OR ILINHVUCTRACUU = -1)
                 AND (TD_VUVIEC.IDOANDONGNGUOI = IDOANDONGNGUOITRACUU OR IDOANDONGNGUOITRACUU = -1)
                 AND (TD_VUVIEC.INOIDUNG = INHOMNOIDUNGTRACUU OR INHOMNOIDUNGTRACUU = -1)
                AND (TD_VUVIEC.ITINHCHAT = ITINHCHATVUVIEC OR ITINHCHATVUVIEC = -1)
                AND (TD_VUVIEC.ITINHTRANGXULY = ITINHTRANGXULYTRACUU OR ITINHTRANGXULYTRACUU = -1)
                  AND ((TD_VUVIEC.IVUVIECTRUNG > IKIEMTRUNG AND IKIEMTRUNG = 1 )OR (TD_VUVIEC.IVUVIECTRUNG = IKIEMTRUNG AND IKIEMTRUNG = 0 ) OR IKIEMTRUNG = -1 )
                  AND ((TD_VUVIEC.IDINHKY > 0 AND ILOAIVUVIEC > 0 ) OR (TD_VUVIEC.IDINHKY = 0 AND ILOAIVUVIEC = 0))
                   AND ((TD_VUVIEC.IUSER = NGUOIDUNG) OR (NGUOIDUNG = 0))
                  AND TD_VUVIEC.ITIEPDOTXUAT = TIEPDOTXUAT
              ORDER BY TD_VUVIEC.DNGAYNHAN;


              END PRC_TIEPDAN_VUVIEC_TRACUU;

  PROCEDURE PRC_TRACUUVUVIEC(res out sys_refcursor,CTUKHOA in NVARCHAR2) AS
  BEGIN
   Open res for

              SELECT TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              NHOMLINHVUC.CTEN AS TENNHOMLINHVUC,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 

               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               INNER JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
                LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
                 LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
                 WHERE ( UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CDIADIEM) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTUKHOA) || '%')

                 ORDER BY TD_VUVIEC.DNGAYNHAN;




  END PRC_TRACUUVUVIEC;



  PROCEDURE PRC_TIEPDANLIST(p_PAGE IN INT,p_PAGE_SIZE IN INT,DINHKY IN INT,TIEPDOTXUAT IN INT,DONVI IN INT ,UERS IN INT ,res out sys_refcursor) AS
  BEGIN
   Open res for
   WITH TD_PHANTRANG AS (
              SELECT 
              TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               INNER JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
                LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
                 WHERE (TD_VUVIEC.IDONVI = DONVI OR DONVI = 0)
                 AND  (TD_VUVIEC.IUSER = UERS OR UERS = 0)
                 AND  (TD_VUVIEC.IDINHKY = DINHKY)
                 AND (TD_VUVIEC.ITIEPDOTXUAT = TIEPDOTXUAT)
                 ORDER BY TD_VUVIEC.DNGAYNHAN

                 )
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);

  END PRC_TIEPDANLIST;

   PROCEDURE PRC_TRACUUVUVIECNHANH(res out sys_refcursor,CTUKHOA in NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT,DINHKY IN INT,TIEPDOTXUAT IN INT,DONVI IN INT ,UERS IN INT) AS
  BEGIN
   Open res for
  WITH TD_PHANTRANG AS ( 
              SELECT TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              NHOMLINHVUC.CTEN AS TENNHOMLINHVUC,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 

               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               INNER JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
                LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
                 LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
                 WHERE ( UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CDIADIEM) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTUKHOA) || '%')
              AND (TD_VUVIEC.IDONVI = DONVI OR DONVI = 0)
                 AND  (TD_VUVIEC.IUSER = UERS OR UERS = 0)
                 AND  (TD_VUVIEC.IDINHKY = DINHKY)
                 AND (TD_VUVIEC.ITIEPDOTXUAT = TIEPDOTXUAT)
                 ORDER BY TD_VUVIEC.DNGAYNHAN
                   )
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);   


  END PRC_TRACUUVUVIECNHANH;







  PROCEDURE PRC_TIEPDAN_VUVIECDANHSACH(res out sys_refcursor, 
                                                    NGAYBATDAU in date,
                                                    NGAYKETHUC IN date,
                                                    IDOANDONGNGUOITRACUU in INT,
                                                    ICOQUANTIEP in INT,
                                                    CTENCONGDAN in NVARCHAR2,
                                                    CDIACHI IN  NVARCHAR2,
                                                    CTOMTAT IN NVARCHAR2,
                                                    ILOAIDONTRACUU IN INT,
                                                    ILINHVUCTRACUU IN INT,
                                                    INHOMNOIDUNGTRACUU IN INT,
                                                    ITINHCHATVUVIEC IN INT,
                                                    ITINHTRANGXULYTRACUU IN INT,
                                                    IKIEMTRUNG IN INT,ILOAIVUVIEC IN INT,TIEPDOTXUAT IN INT,
                                                    CTUKHOA in NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT, MADINHKY IN INT,NGUOIDUNG IN INT) AS
  BEGIN
    -- TODO: Implementation required for PROCEDURE PKG_TD_VUVIEC.PRC_TIEPDAN_VUVIEC_TRACUU
    Open res for

   WITH TD_PHANTRANG AS ( 
   SELECT 
              TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               LEFT JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
              LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
              LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
              WHERE 
               to_date(TD_VUVIEC.DNGAYNHAN) >=  NGAYBATDAU  AND to_date(TD_VUVIEC.DNGAYNHAN) <=  NGAYKETHUC
              AND  (UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTENCONGDAN) || '%' OR TD_VUVIEC.CNGUOIGUI_TEN IS NULL)
              AND (UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTOMTAT) || '%' OR TD_VUVIEC.CNOIDUNG IS NULL)
              AND( UPPER(TD_VUVIEC.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(CDIACHI) || '%'  OR TD_VUVIEC.CNGUOIGUI_DIACHI IS NULL)
              AND (TD_VUVIEC.IDONVI = ICOQUANTIEP OR ICOQUANTIEP = -1)
              AND (TD_VUVIEC.ILOAIDON = ILOAIDONTRACUU OR ILOAIDONTRACUU = -1)
              AND (TD_VUVIEC.ILINHVUC = ILINHVUCTRACUU OR ILINHVUCTRACUU = -1)
              AND (TD_VUVIEC.IDOANDONGNGUOI =IDOANDONGNGUOITRACUU OR IDOANDONGNGUOITRACUU = -1)
              AND (TD_VUVIEC.INOIDUNG = INHOMNOIDUNGTRACUU  OR INHOMNOIDUNGTRACUU = -1)
              AND (TD_VUVIEC.ITINHCHAT = ITINHCHATVUVIEC  OR ITINHCHATVUVIEC = -1)
              AND (TD_VUVIEC.ITINHTRANGXULY = ITINHTRANGXULYTRACUU OR ITINHTRANGXULYTRACUU = -1)
              AND ((TD_VUVIEC.IDINHKY > 0 AND ILOAIVUVIEC > 0 ) OR (TD_VUVIEC.IDINHKY = 0 AND ILOAIVUVIEC = -1))
              AND TD_VUVIEC.ITIEPDOTXUAT = TIEPDOTXUAT
              AND  ( UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CDIADIEM) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTUKHOA) || '%')
              AND (TD_VUVIEC.IVUVIECTRUNG != IKIEMTRUNG OR IKIEMTRUNG = -1)
              AND (TD_VUVIEC.IUSER = NGUOIDUNG OR NGUOIDUNG = -1)
              AND (TD_VUVIEC.IDINHKY = MADINHKY OR MADINHKY = -1)
              Order By    TD_VUVIEC.DNGAYNHAN DESC
            )
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);   
              END PRC_TIEPDAN_VUVIECDANHSACH; 

PROCEDURE PRC_TIEPDAN_VUVIECTAMTHOI(res out sys_refcursor, 
                                                    NGAYBATDAU in date,
                                                    NGAYKETHUC IN date,
                                                    IDOANDONGNGUOITRACUU in INT,
                                                    ICOQUANTIEP in INT,
                                                    CTENCONGDAN in NVARCHAR2,
                                                    CDIACHI IN  NVARCHAR2,
                                                    CTOMTAT IN NVARCHAR2,
                                                    ILOAIDONTRACUU IN INT,
                                                    ILINHVUCTRACUU IN INT,
                                                    INHOMNOIDUNGTRACUU IN INT,
                                                    ITINHCHATVUVIEC IN INT,
                                                    ITINHTRANGXULYTRACUU IN INT,
                                                    IKIEMTRUNG IN INT,ILOAIVUVIEC IN INT,TIEPDOTXUAT IN INT,
                                                    CTUKHOA in NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT, MADINHKY IN INT,NGUOIDUNG IN INT) AS
  BEGIN
    -- TODO: Implementation required for PROCEDURE PKG_TD_VUVIEC.PRC_TIEPDAN_VUVIEC_TRACUU
    Open res for

   WITH TD_PHANTRANG AS ( 
   SELECT 
              TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               LEFT JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
              LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
              LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
              WHERE 
               to_date(TD_VUVIEC.DNGAYNHAN) >=  NGAYBATDAU  AND to_date(TD_VUVIEC.DNGAYNHAN) <=  NGAYKETHUC
              AND  (UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTENCONGDAN) || '%' OR TD_VUVIEC.CNGUOIGUI_TEN IS NULL)
              AND (UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTOMTAT) || '%' OR TD_VUVIEC.CNOIDUNG IS NULL)
              AND( UPPER(TD_VUVIEC.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(CDIACHI) || '%'  OR TD_VUVIEC.CNGUOIGUI_DIACHI IS NULL)
              AND (TD_VUVIEC.IDONVI = ICOQUANTIEP OR ICOQUANTIEP = -1)
              AND (TD_VUVIEC.ILOAIDON = ILOAIDONTRACUU OR ILOAIDONTRACUU = -1)
              AND (TD_VUVIEC.ILINHVUC = ILINHVUCTRACUU OR ILINHVUCTRACUU = -1)
              AND (TD_VUVIEC.IDOANDONGNGUOI =IDOANDONGNGUOITRACUU OR IDOANDONGNGUOITRACUU = -1)
              AND (TD_VUVIEC.INOIDUNG = INHOMNOIDUNGTRACUU  OR INHOMNOIDUNGTRACUU = -1)
              AND (TD_VUVIEC.ITINHCHAT = ITINHCHATVUVIEC  OR ITINHCHATVUVIEC = -1)
              AND (TD_VUVIEC.ITINHTRANGXULY = ITINHTRANGXULYTRACUU OR ITINHTRANGXULYTRACUU = -1)

              AND  ( UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CDIADIEM) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTUKHOA) || '%')
              AND (TD_VUVIEC.IVUVIECTRUNG != IKIEMTRUNG OR IKIEMTRUNG = -1)
              AND (TD_VUVIEC.IUSER = NGUOIDUNG OR NGUOIDUNG = -1)
              AND (TD_VUVIEC.IDINHKY = MADINHKY OR MADINHKY = -1)
              AND TD_VUVIEC.IDELETE = 1
              Order By    TD_VUVIEC.DNGAYNHAN DESC
            )
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);   
              END PRC_TIEPDAN_VUVIECTAMTHOI;               


 PROCEDURE PRC_LICHTIEPDINHKY(res out sys_refcursor, CTUKHOA in NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT,MADONVI IN INT,NGUOIDUNG IN INT ) AS
  BEGIN
    -- TODO: Implementation required for PROCEDURE PKG_TD_VUVIEC.PRC_TIEPDAN_VUVIEC_TRACUU
    Open res for

   WITH TD_PHANTRANG AS ( 
   SELECT 
 TIEPDAN_DINHKY.IDINHKY AS IDDINHKY,
 TIEPDAN_DINHKY.IVUVIEC AS IDDONVI,
 TIEPDAN_DINHKY.DNGAYTIEP AS NGAYTIEP,
 TIEPDAN_DINHKY.IUSER AS IDUSER,
 TIEPDAN_DINHKY.CDIADIEM  AS DIADIEMTIEP,
 TINH.CTEN AS TENTINH,
 HUYEN.CTEN AS TENHUYEN,
 coalesce((SELECT COUNT(*)  FROM TD_VUVIEC WHERE TD_VUVIEC.IDINHKY = TIEPDAN_DINHKY.IDINHKY AND (TD_VUVIEC.IDONVI= MADONVI OR MADONVI = -1 ) AND  (TD_VUVIEC.IUSER = NGUOIDUNG OR NGUOIDUNG = -1) ),0) AS SOVUVIEC,
 coalesce((SELECT SUM(ISONGUOI)  FROM TD_VUVIEC WHERE TD_VUVIEC.IDINHKY = TIEPDAN_DINHKY.IDINHKY AND (TD_VUVIEC.IDONVI= MADONVI OR MADONVI = -1 ) AND  (TD_VUVIEC.IUSER = NGUOIDUNG OR NGUOIDUNG = -1) ),0) AS SOLUOTNGUOI,
  coalesce((SELECT SUM(IDOANDONGNGUOI)  FROM TD_VUVIEC WHERE TD_VUVIEC.IDINHKY = TIEPDAN_DINHKY.IDINHKY AND (TD_VUVIEC.IDONVI= MADONVI OR MADONVI = -1 ) AND  (TD_VUVIEC.IUSER = NGUOIDUNG OR NGUOIDUNG = -1) ),0) AS SODDOANDONGNGUOI

FROM TIEPDAN_DINHKY
 LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TIEPDAN_DINHKY.IDOAN AND TINH.IDELETE = 0
 LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TIEPDAN_DINHKY.ILUOT AND HUYEN.IDELETE = 0
 WHERE (TIEPDAN_DINHKY.IVUVIEC = MADONVI OR MADONVI = -1) AND (TIEPDAN_DINHKY.IUSER = NGUOIDUNG OR NGUOIDUNG = -1)
 AND ( UPPER(TIEPDAN_DINHKY.CDIADIEM) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(TINH.CTEN) LIKE '%' || UPPER(CTUKHOA) || '%'
              OR UPPER(HUYEN.CTEN) LIKE '%' || UPPER(CTUKHOA) || '%')
            )
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);   
              END PRC_LICHTIEPDINHKY;   


 PROCEDURE PRC_TIEPDAN_TRACUUVUVIEC(res out sys_refcursor, NGAYBATDAU in date,
                                                    NGAYKETHUC IN date,
                                                    IDOANDONGNGUOITRACUU in INT,
                                                    ICOQUANTIEP in INT,
                                                    CTENCONGDAN in NVARCHAR2,
                                                    CDIACHI IN  NVARCHAR2,
                                                    CTOMTAT IN NVARCHAR2,
                                                    ILOAIDONTRACUU IN INT,
                                                    ILINHVUCTRACUU IN INT,
                                                    INHOMNOIDUNGTRACUU IN INT,
                                                    ITINHCHATVUVIEC IN INT,
                                                    ITINHTRANGXULYTRACUU IN INT,
                                                    IKIEMTRUNG IN INT,ILOAIVUVIEC IN INT,TIEPDOTXUAT IN INT,p_PAGE IN INT, p_PAGE_SIZE IN INT,IDUSER IN INT) AS
  BEGIN
    -- TODO: Implementation required for PROCEDURE PKG_TD_VUVIEC.PRC_TIEPDAN_VUVIEC_TRACUU
    Open res for

  WITH TD_PHANTRANG AS ( 
    SELECT TD_VUVIEC.DNGAYNHAN AS NGAYNHAN,
              TINH.CTEN AS TENTINH,
              HUYEN.CTEN AS TENHUYEN,
              TD_VUVIEC.CNGUOIGUI_DIACHI AS DIACHINGUOIGUI,
              TD_VUVIEC.CNOIDUNG AS NOIDUNGVUVIEC,
              TD_VUVIEC.CNGUOITIEP AS TENNGUOITIEP,
              TD_VUVIEC.CNGUOIGUI_TEN AS TENNGUOIGUI,
              LOAIDON.CTEN AS LOAIDON,
              TINHCHAT.CTEN AS TINHCHAT,
              NHOMNOIDUNG.CTEN AS NHOMNOIDUNG,
              NHOMLINHVUC.CTEN AS TENLINHVUC,
              TD_VUVIEC.IVUVIEC AS IDVUVIEC,
              TD_VUVIEC.ITINHTRANGXULY AS TRANGTHAIXULY,
              TD_VUVIEC.IDONVI AS IDONVI,
              COQUAN.CTEN AS CTENDONVI,
              TD_VUVIEC.IDINHKY AS DINHKY,
              TD_VUVIEC.IUSER AS USER_ID,
              TD_VUVIEC.IVUVIECTRUNG AS VUVIECTRUNG,
              TD_VUVIEC.IGIAMSAT AS GIAMSAT,
              TD_VUVIEC.CYKIENGIAMSAT AS YKIENGIAMSAT,
              TD_VUVIEC.ITIEPDOTXUAT AS TIEPDOTXUAT,
              TD_VUVIEC.ILANHDAOTIEP AS LANHDAOTIEP,
              TD_VUVIEC.CNOIDUNGCHIDAO AS NOIDUNGCHIDAO,
                TD_VUVIEC.IDELETE AS DELVUVIEC
               FROM TD_VUVIEC 
               INNER JOIN QUOCHOI_COQUAN COQUAN ON COQUAN.ICOQUAN = TD_VUVIEC.IDONVI
               LEFT JOIN KNTC_LOAIDON LOAIDON ON LOAIDON.ILOAIDON = TD_VUVIEC.ILOAIDON
              LEFT JOIN LINHVUC NHOMLINHVUC ON NHOMLINHVUC.ILINHVUC = TD_VUVIEC.ILINHVUC
               LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_0
               LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = TD_VUVIEC.IDIAPHUONG_1
               LEFT JOIN KNTC_TINHCHAT TINHCHAT ON TINHCHAT.ITINHCHAT = TD_VUVIEC.ITINHCHAT
              LEFT JOIN KNTC_NOIDUNGDON NHOMNOIDUNG ON NHOMNOIDUNG.INOIDUNG = TD_VUVIEC.INOIDUNG
              WHERE to_date(TD_VUVIEC.DNGAYNHAN) >=  NGAYBATDAU  AND to_date(TD_VUVIEC.DNGAYNHAN) <=  NGAYKETHUC
                AND (UPPER(TD_VUVIEC.CNGUOIGUI_TEN) LIKE '%' || UPPER(CTENCONGDAN) || '%' OR TD_VUVIEC.CNGUOIGUI_TEN IS NULL)
                AND (UPPER(TD_VUVIEC.CNOIDUNG) LIKE '%' || UPPER(CTOMTAT) || '%' OR TD_VUVIEC.CNOIDUNG IS NULL)
                 AND( UPPER(TD_VUVIEC.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(CDIACHI) || '%'  OR TD_VUVIEC.CNGUOIGUI_DIACHI IS NULL)
                 AND (TD_VUVIEC.IDONVI = ICOQUANTIEP OR ICOQUANTIEP = -1)
                 AND (TD_VUVIEC.ILOAIDON = ILOAIDONTRACUU OR ILOAIDONTRACUU = -1)
                 AND (TD_VUVIEC.ILINHVUC = ILINHVUCTRACUU OR ILINHVUCTRACUU = -1)
                 AND (TD_VUVIEC.IDOANDONGNGUOI = IDOANDONGNGUOITRACUU OR IDOANDONGNGUOITRACUU = -1)
                 AND (TD_VUVIEC.INOIDUNG = INHOMNOIDUNGTRACUU OR INHOMNOIDUNGTRACUU = -1)
                AND (TD_VUVIEC.ITINHCHAT = ITINHCHATVUVIEC OR ITINHCHATVUVIEC = -1)
                AND (TD_VUVIEC.ITINHTRANGXULY = ITINHTRANGXULYTRACUU OR ITINHTRANGXULYTRACUU = -1)
                  AND ((TD_VUVIEC.IVUVIECTRUNG > IKIEMTRUNG AND IKIEMTRUNG = 1 )OR (TD_VUVIEC.IVUVIECTRUNG = IKIEMTRUNG AND IKIEMTRUNG = 0 ) OR IKIEMTRUNG = -1 )
                  AND ((TD_VUVIEC.IDINHKY > 0 AND ILOAIVUVIEC > 0 ) OR (TD_VUVIEC.IDINHKY = 0 AND ILOAIVUVIEC = 0))
                  AND TD_VUVIEC.ITIEPDOTXUAT = TIEPDOTXUAT
                   AND (TD_VUVIEC.IUSER = IDUSER OR IDUSER = 0)

              ORDER BY TD_VUVIEC.DNGAYNHAN DESC) 
              SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM TD_PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from TD_PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);   



              END PRC_TIEPDAN_TRACUUVUVIEC;              

END PKG_TD_VUVIEC;

