CREATE OR REPLACE
PACKAGE BODY "PKG_VANBAN" AS

  PROCEDURE PRC_PHANTRANG_VANBAN(res out sys_refcursor,NGAYBATDAU IN DATE,
  NGAYKETTHUC IN DATE,
  CTUKHOA IN NVARCHAR2,
  IMADONVI IN INT ,
  LOAIVANBAN IN INT,
  LINHVUC IN INT, 
  TRANGTHAI IN INT , 
  KYHOP IN INT,
  p_PAGE IN INT, p_PAGE_SIZE IN INT) AS
  BEGIN
     OPEN res FOR

 WITH PHANTRANG AS(
    SELECT distinct
        VB_VANBAN.IVANBAN AS IDVANBAN,
        VB_VANBAN.CTIEUDE AS TIEUDE,
        VB_VANBAN.CTRICHYEU AS TRICHYEU,
        VB_VANBAN.IHIENTHI AS HIENTHI,
        VB_VANBAN.DDATECREATE AS DATECREATE,
        LINHVUC.CTEN AS TENLINHVUC,
        VB_LOAI.CTEN AS TENLOAIVB,
        QUOCHOI_KYHOP.CTEN AS TENKYHOP
        FROM VB_VANBAN 
        LEFT JOIN VB_DONVI_VANBAN ON VB_DONVI_VANBAN.IVANBAN = VB_VANBAN.IVANBAN  AND (VB_DONVI_VANBAN.IDONVI = IMADONVI OR IMADONVI= -1)
        LEFT JOIN QUOCHOI_KYHOP ON QUOCHOI_KYHOP.IKYHOP = VB_VANBAN.IKYHOP   AND QUOCHOI_KYHOP.IDELETE = 0
        LEFT JOIN LINHVUC ON VB_VANBAN.ILINHVUC = LINHVUC.ILINHVUC AND LINHVUC.IDELETE = 0
        LEFT JOIN VB_LOAI ON VB_LOAI.ILOAI = VB_VANBAN.ILOAI AND VB_LOAI.IDELETE = 0
        WHERE (VB_VANBAN.ILOAI = LOAIVANBAN OR LOAIVANBAN= -1) 
        AND (VB_VANBAN.ILINHVUC = LINHVUC OR LINHVUC = -1)
        AND(VB_DONVI_VANBAN.IDONVI  = IMADONVI OR IMADONVI= -1)
        AND (VB_VANBAN.IKYHOP = KYHOP OR  KYHOP = 0)
       AND (VB_VANBAN.IHIENTHI = TRANGTHAI OR TRANGTHAI = 2)
        AND TO_DATE(VB_VANBAN.DDATE) BETWEEN NGAYBATDAU AND NGAYKETTHUC
        AND  ( UPPER(CTRICHYEU) LIKE '%' || UPPER(CTUKHOA) || '%' OR  UPPER(CTIEUDE) LIKE '%' || UPPER(CTUKHOA) || '%' )
       order by  VB_VANBAN.IVANBAN
)
SELECT * FROM 
(
   SELECT k.*,(SELECT COUNT(*) FROM PHANTRANG) AS TOTAL, 
   ROWNUM r_ FROM( select * from PHANTRANG ) k
   WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
) 
 WHERE r_>= (((p_PAGE-1) * p_PAGE_SIZE) + 1);

  END PRC_PHANTRANG_VANBAN;

END PKG_VANBAN;

