CREATE OR REPLACE
PACKAGE BODY "PKG_TCD_VUVIEC" AS

  PROCEDURE PRC_PHANTRANG_TIEPDANVUVIEC(res out sys_refcursor) AS
  BEGIN
     OPEN res FOR
    SELECT 
    DNGAYNHAN AS NGAYNHAN,

    IDIAPHUONG_0 AS DIAPHUONG_0,
    IDIAPHUONG_1 AS DIAPHUONG_1,
    CNGUOIGUI_DIACHI AS DIACHI,
    CNOIDUNG AS NOIDUNGVUVIEC,
    CNGUOITIEP AS TENNGUOITIEP,
    CNGUOIGUI_TEN AS TENNGUOIGUI,
    ITINHTRANGXULY AS TRANGTHAIXULY,
    IVUVIEC AS IDVUVIEC,
    IDONVI AS DONVI,
    IDINHKY AS DINHKY,
    IVUVIECTRUNG AS VUVIECTRUNG,
    IGIAMSAT AS GIAMSAT,
   CYKIENGIAMSAT AS YKIENGIAMSAT

    FROM TD_VUVIEC 
      WHERE TD_VUVIEC.IVUVIEC != 0 ORDER BY IVUVIEC;

  END PRC_PHANTRANG_TIEPDANVUVIEC;

END PKG_TCD_VUVIEC;

