CREATE OR REPLACE
PACKAGE "PKG_THIETLAP_HETHONG" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
PROCEDURE PRC_NGUOIDUNG(res out sys_refcursor, p_TUKHOA IN NVARCHAR2 );
PROCEDURE PRC_NGUOIDUNG_OPT(res out sys_refcursor, p_TUKHOA IN NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT);
  PROCEDURE PKG_COQUANGOC(res out sys_refcursor);
  PROCEDURE PKG_COQUAN_CAPKHAC(res out sys_refcursor,IDPARENT IN INT);
 PROCEDURE PKG_TIMKIEMLICHSU(res out sys_refcursor,NGAYBATDAU IN DATE , NGAYKETHUC IN DATE ,CTUKHOA IN NVARCHAR2);
 PROCEDURE PKG_TIMKIEMTHEODONVI(res out sys_refcursor, IMADONVI IN INT ,CTUKHOA IN NVARCHAR2);   
 PROCEDURE PKG_COQUAN_PHANTRANG(res out sys_refcursor, p_TUKHOA IN NVARCHAR2, p_PAGE IN INT, p_PAGE_SIZE IN INT);
  PROCEDURE PKG_DIAPHUONG_PHANTRANG(res out sys_refcursor , p_TUKHOA in NVARCHAR2, p_PAGE IN INT, p_PAGE_SIZE IN INT );
   PROCEDURE PKG_DIAPHUONG(res out sys_refcursor);    
PROCEDURE PRC_DAIBIEU_PHANTRANG(res out sys_refcursor, p_DAIBIEU IN INT, p_KHOA IN INT, p_LOAIDAIBIEU IN INT ,p_PAGE IN INT, p_PAGE_SIZE IN INT);			
   PROCEDURE PKG_LICHSU(res out sys_refcursor,NGAYBATDAU IN DATE , NGAYKETHUC IN DATE ,CTUKHOANOIDUNG IN NVARCHAR2,IMADONVI IN INT ,CTUKHOANGUOIDUNG IN NVARCHAR2,p_PAGE IN INT, p_PAGE_SIZE IN INT);
    PROCEDURE PRC_PHANTRANG_VANBAN(res out sys_refcursor,NGAYBATDAU IN DATE,NGAYKETTHUC IN DATE,CTUKHOA IN NVARCHAR2,IMADONVI IN INT ,LOAIVANBAN IN INT,LINHVUC IN INT, TRANGTHAI IN INT , KYHOP IN INT,p_PAGE IN INT, p_PAGE_SIZE IN INT);
END PKG_THIETLAP_HETHONG;

