CREATE OR REPLACE
PACKAGE "PKG_VANBAN" AS 

  PROCEDURE PRC_PHANTRANG_VANBAN(res out sys_refcursor,NGAYBATDAU IN DATE,NGAYKETTHUC IN DATE,CTUKHOA IN NVARCHAR2,IMADONVI IN INT ,LOAIVANBAN IN INT,LINHVUC IN INT, TRANGTHAI IN INT , KYHOP IN INT,p_PAGE IN INT, p_PAGE_SIZE IN INT);

END PKG_VANBAN;

