CREATE OR REPLACE
PACKAGE BODY "PKG_KIENNGHI_BAOCAO" 
AS
----Bao cao 1
--- pram01 in IKYHOP, pram02 IN IDONVITIEPNHAN, pram03 IN ILINHVUC
  PROCEDURE  PRO_BAOCAO_TK_PHULUC1(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER, pram03 IN NUMBER) AS
  BEGIN
    OPEN res FOR
        --    
    with   
    TONGKIENNGHI as (
            SELECT COUNT (*) as TONGKIENNGHI, KN_KIENNGHI.ITHAMQUYENDONVI as ICOQUAN
            FROM KN_KIENNGHI
               where 
               KN_KIENNGHI.ITINHTRANG IN (3,4,5,8) AND
               KN_KIENNGHI.IKYHOP = pram01
               AND (pram02 = 0 OR KN_KIENNGHI.IDONVITIEPNHAN = pram02)
               AND (pram03 = -1 OR KN_KIENNGHI.ILINHVUC = pram03)
            group by  KN_KIENNGHI.ITHAMQUYENDONVI) ,
    TONGKIENNGHI_TRALOI as (
            SELECT COUNT (*) as TONGKIENNGHI_TRALOI ,   KN_KIENNGHI.ITHAMQUYENDONVI
            FROM KN_KIENNGHI_TRALOI inner join KN_KIENNGHI ON  KN_KIENNGHI_TRALOI.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI
            where
                 KN_KIENNGHI.IKYHOP = pram01
                AND (pram02 = 0 OR KN_KIENNGHI.IDONVITIEPNHAN = pram02)
                AND (pram03 = -1 OR KN_KIENNGHI.ILINHVUC = pram03)
            group by KN_KIENNGHI.ITHAMQUYENDONVI ),
    TONGKIENNGHI_DAGIAIQUYET as (
              SELECT COUNT(*) AS TONGKIENNGHI_DAGIAIQUYET,KN_KIENNGHI.ITHAMQUYENDONVI FROM KN_KIENNGHI_TRALOI,KN_TRALOI_PHANLOAI,KN_KIENNGHI
              WHERE KN_KIENNGHI_TRALOI.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI AND KN_KIENNGHI_TRALOI.IPHANLOAI = KN_TRALOI_PHANLOAI.IPHANLOAI
  AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI 
    WHERE CCODE='DAGIAIQUYET') AND KN_KIENNGHI.IKYHOP = pram01
                AND (pram02 = 0 OR KN_KIENNGHI.IDONVITIEPNHAN = pram02)
                AND (pram03 = -1 OR KN_KIENNGHI.ILINHVUC = pram03)
                  group by    KN_KIENNGHI.ITHAMQUYENDONVI),
    TONGKIENNGHI_DANGGIAIQUYET as (                   
            SELECT COUNT(*) AS TONGKIENNGHI_DANGGIAIQUYET,KN_KIENNGHI.ITHAMQUYENDONVI FROM KN_KIENNGHI_TRALOI,KN_TRALOI_PHANLOAI,KN_KIENNGHI
              WHERE KN_KIENNGHI_TRALOI.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI AND KN_KIENNGHI_TRALOI.IPHANLOAI = KN_TRALOI_PHANLOAI.IPHANLOAI
  AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI WHERE CCODE='DANGGIAIQUYET') AND KN_KIENNGHI.IKYHOP = pram01
                AND (pram02 = 0 OR KN_KIENNGHI.IDONVITIEPNHAN = pram02)
                AND (pram03 = -1 OR KN_KIENNGHI.ILINHVUC = pram03)
                  group by    KN_KIENNGHI.ITHAMQUYENDONVI),
    TONGKIENNGHI_GIAITRINH as (
          SELECT COUNT(*) AS TONGKIENNGHI_GIAITRINH,KN_KIENNGHI.ITHAMQUYENDONVI FROM KN_KIENNGHI_TRALOI,KN_TRALOI_PHANLOAI,KN_KIENNGHI
              WHERE KN_KIENNGHI_TRALOI.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI AND KN_KIENNGHI_TRALOI.IPHANLOAI = KN_TRALOI_PHANLOAI.IPHANLOAI
                    AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI 
               WHERE CCODE='GIAITRINH_CUNGCAPTHONGTIN') AND KN_KIENNGHI.IKYHOP = pram01
                AND (pram02 = 0 OR KN_KIENNGHI.IDONVITIEPNHAN = pram02)
                AND (pram03 = -1 OR KN_KIENNGHI.ILINHVUC = pram03)
                  group by    KN_KIENNGHI.ITHAMQUYENDONVI)
   SELECT QUOCHOI_COQUAN.ICOQUAN,
        QUOCHOI_COQUAN.CTEN AS TEN_DONVI,
        QUOCHOI_COQUAN.ICOQUAN AS ID_DONVI,
        QUOCHOI_COQUAN.IPARENT AS ID_PARENT,
        TONGKIENNGHI.TONGKIENNGHI,
       TONGKIENNGHI_TRALOI.TONGKIENNGHI_TRALOI,
        TONGKIENNGHI_DAGIAIQUYET.TONGKIENNGHI_DAGIAIQUYET,
        TONGKIENNGHI_DANGGIAIQUYET.TONGKIENNGHI_DANGGIAIQUYET,
        TONGKIENNGHI_GIAITRINH.TONGKIENNGHI_GIAITRINH     
    FROM QUOCHOI_COQUAN 
    left join  TONGKIENNGHI on   QUOCHOI_COQUAN.ICOQUAN  = TONGKIENNGHI.ICOQUAN
    left join  TONGKIENNGHI_TRALOI on   QUOCHOI_COQUAN.ICOQUAN  = TONGKIENNGHI_TRALOI.ITHAMQUYENDONVI
    left join  TONGKIENNGHI_DAGIAIQUYET on   QUOCHOI_COQUAN.ICOQUAN  = TONGKIENNGHI_DAGIAIQUYET.ITHAMQUYENDONVI
    left join  TONGKIENNGHI_DANGGIAIQUYET on   QUOCHOI_COQUAN.ICOQUAN  = TONGKIENNGHI_DANGGIAIQUYET.ITHAMQUYENDONVI
    left join  TONGKIENNGHI_GIAITRINH on   QUOCHOI_COQUAN.ICOQUAN  = TONGKIENNGHI_GIAITRINH.ITHAMQUYENDONVI
    WHERE QUOCHOI_COQUAN.ICOQUAN<>20 AND QUOCHOI_COQUAN.IPARENT<>20 AND IHIENTHI=1;

  END PRO_BAOCAO_TK_PHULUC1;
----Bao cao 2
--- pram01 in IKYHOP, pram02 IN IDONVIBANHANH, pram03 IN ILINHVUC
  PROCEDURE PRO_BAOCAO_TK_PHULUC2(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER, pram03 IN NUMBER)AS 
  BEGIN
  OPEN res FOR
   SELECT
      QUOCHOI_COQUAN.IPARENT AS ID_PARENT,
      QUOCHOI_COQUAN.IVITRI AS VITRI,
      VB_VANBAN.CTRICHYEU AS TRICHYEU,
      CONCAT(CONCAT( (SELECT VB_LOAI.CTEN FROM VB_LOAI,VB_VANBAN WHERE VB_LOAI.ILOAI = VB_VANBAN.ILOAI AND VB_VANBAN.IVANBAN = VB_DONVI_VANBAN.IVANBAN),'/' ),
      (SELECT VB_VANBAN.CTIEUDE FROM VB_VANBAN WHERE VB_VANBAN.IVANBAN = VB_DONVI_VANBAN.IVANBAN  )) AS SOHIEUVANBAN,
      VB_VANBAN.DDATE AS NGAY
    FROM VB_DONVI_VANBAN INNER JOIN VB_VANBAN ON VB_DONVI_VANBAN.IVANBAN=VB_VANBAN.IVANBAN
        INNER JOIN QUOCHOI_COQUAN ON VB_DONVI_VANBAN.IDONVI=QUOCHOI_COQUAN.ICOQUAN
    WHERE VB_VANBAN.IKYHOP=pram01
        AND (pram03=-1 or VB_VANBAN.ILINHVUC=pram03)
        and (pram02=0 or QUOCHOI_COQUAN.ICOQUAN=pram02);

  END PRO_BAOCAO_TK_PHULUC2;
  ----Bao cao 3
  --- pram01 in IKYHOP, pram02 IN IDONVIBANHANH, pram03 IN ILINHVUC
  PROCEDURE PRO_BAOCAO_TK_PHULUC3(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER, pram03 IN NUMBER)AS 
  BEGIN
  OPEN res FOR
     SELECT ROW_NUMBER() OVER(ORDER BY 1 ASC) AS STT,
            KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,
            KN_KIENNGHI_TRALOI.CTRALOI AS LOTRINH,
            KN_KIENNGHI_TRALOI.ITINHTRANG AS TINHTRANG_TRALOI,
            QUOCHOI_COQUAN.ICOQUAN AS ID_DONVI,
            QUOCHOI_COQUAN.CTEN AS TEN_DONVI,
            KN_KIENNGHI_TRALOI.DNGAY_DUKIEN AS NGAYDUKIEN,
            KN_TRALOI_PHANLOAI.CTEN AS TENPHANLOAI,KN_TRALOI_PHANLOAI.IPHANLOAI AS ID_PHANLOAI
    FROM KN_KIENNGHI INNER JOIN KN_KIENNGHI_TRALOI ON KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI 
           INNER JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.ITHAMQUYENDONVI
           INNER JOIN KN_TRALOI_PHANLOAI ON KN_TRALOI_PHANLOAI.IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI
    WHERE KN_KIENNGHI.IKYHOP=pram01
         AND (pram02=0 or KN_KIENNGHI.IDONVITIEPNHAN=pram02)
         AND (pram03=-1 or KN_KIENNGHI.ILINHVUC=pram03)
         AND (KN_TRALOI_PHANLOAI.CCODE='DANGGIAIQUYET_COLOTRINH' OR KN_TRALOI_PHANLOAI.CCODE='DANGGIAIQUYET_KHONGLOTRINH')
         ORDER BY KN_TRALOI_PHANLOAI.IPHANLOAI
         ;
  END PRO_BAOCAO_TK_PHULUC3;
  ----Bao cao 4  
  ---pram01 in IDONVITIEPNHAN, pram02 IN ILINHVUC,
    PROCEDURE PRO_BAOCAO_TK_PHULUC4(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER)AS 
    BEGIN
    OPEN res FOR
       with
       /*
        TONGKIENNGHI as (SELECT COUNT(*) as TONGKIENNGHI, 
                  KN_KIENNGHI.ITHAMQUYENDONVI AS ICOQUAN 
                  FROM KN_GIAMSAT 
                  INNER JOIN KN_KIENNGHI ON KN_KIENNGHI.IKIENNGHI=KN_GIAMSAT.IKIENNGHI 
                  INNER JOIN KN_TRALOI_PHANLOAI ON KN_TRALOI_PHANLOAI.IPHANLOAI=KN_GIAMSAT.IPHANLOAI
                  WHERE KN_GIAMSAT.IDONGKIENNGHI =0 --CHUYEN THEO DOI KY HOP SAU
                  AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI 
                        WHERE CCODE='DAGIAIQUYET' OR CCODE='DANGGIAIQUYET')
                  AND (pram01=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram01)
                  AND (pram02=-1 OR KN_KIENNGHI.ILINHVUC=pram02)
                  GROUP BY KN_KIENNGHI.ITHAMQUYENDONVI),
      */                  
       TONGKIENNGHI_DAGIAIQUYET as (SELECT COUNT(*) as TONGKIENNGHI_DAGIAIQUYET, 
                  KN_KIENNGHI.ITHAMQUYENDONVI AS ICOQUAN 
                  FROM KN_GIAMSAT,KN_KIENNGHI,KN_TRALOI_PHANLOAI 
                  WHERE KN_GIAMSAT.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI AND KN_GIAMSAT.IPHANLOAI = KN_TRALOI_PHANLOAI.IPHANLOAI AND                  
                  KN_GIAMSAT.IDONGKIENNGHI =0 --CHUYEN THEO DOI KY HOP SAU
                  AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI 
                        WHERE CCODE='DAGIAIQUYET')
                  AND (pram01=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram01)
                  AND (pram02=-1 OR KN_KIENNGHI.ILINHVUC=pram02)
                  GROUP BY KN_KIENNGHI.ITHAMQUYENDONVI),

        TONGKIENNGHI_DANGGIAIQUYET as (SELECT COUNT(*) as TONGKIENNGHI_DANGGIAIQUYET, 
                  KN_KIENNGHI.ITHAMQUYENDONVI AS ICOQUAN 
                  FROM KN_GIAMSAT,KN_KIENNGHI,KN_TRALOI_PHANLOAI 
                  WHERE KN_GIAMSAT.IKIENNGHI =  KN_KIENNGHI.IKIENNGHI AND KN_GIAMSAT.IPHANLOAI = KN_TRALOI_PHANLOAI.IPHANLOAI AND                  
                  KN_GIAMSAT.IDONGKIENNGHI =0 --CHUYEN THEO DOI KY HOP SAU
                  AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI 
                        WHERE CCODE='DANGGIAIQUYET')
                  AND (pram01=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram01)
                  AND (pram02=-1 OR KN_KIENNGHI.ILINHVUC=pram02)
                  GROUP BY KN_KIENNGHI.ITHAMQUYENDONVI),
        COQUAN_PARENT AS (SELECT CTEN AS TEN_CAPCOQUAN,ICOQUAN AS ID_CAPCOQUAN FROM QUOCHOI_COQUAN WHERE IPARENT=0)     
        SELECT ROW_NUMBER() OVER(ORDER BY 1 ASC) AS STT,
                QUOCHOI_COQUAN.CTEN AS TEN_DONVI,
                QUOCHOI_COQUAN.IPARENT AS ID_CAPCOQUAN,
                (SELECT TEN_CAPCOQUAN FROM COQUAN_PARENT WHERE ID_CAPCOQUAN=QUOCHOI_COQUAN.IPARENT) AS TEN_CAPCOQUAN,
                COALESCE(TONGKIENNGHI_DAGIAIQUYET.TONGKIENNGHI_DAGIAIQUYET,0) as TONGKIENNGHI_DAGIAIQUYET,
                COALESCE(TONGKIENNGHI_DANGGIAIQUYET.TONGKIENNGHI_DANGGIAIQUYET,0) as TONGKIENNGHI_DANGGIAIQUYET
        FROM QUOCHOI_COQUAN 
        --LEFT JOIN TONGKIENNGHI ON TONGKIENNGHI.ICOQUAN=QUOCHOI_COQUAN.ICOQUAN
        LEFT JOIN TONGKIENNGHI_DAGIAIQUYET ON TONGKIENNGHI_DAGIAIQUYET.ICOQUAN=QUOCHOI_COQUAN.ICOQUAN
        LEFT JOIN TONGKIENNGHI_DANGGIAIQUYET ON TONGKIENNGHI_DANGGIAIQUYET.ICOQUAN=QUOCHOI_COQUAN.ICOQUAN;
    END PRO_BAOCAO_TK_PHULUC4;
  ----Bao cao 5
  ---pram01 in TUNGAY, pram02 in DENNGAY, pram03 in DONVITIEPNHAN, pram04 IN LINHVUC
  PROCEDURE PRO_BAOCAO_TK_PHULUC5(res out sys_refcursor, pram01 in DATE, pram02 in DATE, pram03 in NUMBER, pram04 IN NUMBER)AS 
  BEGIN
  OPEN res FOR
    WITH TBL1 AS(
    SELECT KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,KN_KIENNGHI.ID_GOP AS ID_GOP,KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI,
      (SELECT CTEN FROM QUOCHOI_KYHOP WHERE KN_KIENNGHI.IKYHOP=IKYHOP) AS TEN_KYHOP,
      (SELECT IPHANLOAI FROM KN_KIENNGHI_TRALOI WHERE KN_KIENNGHI_TRALOI.IKIENNGHI=KN_KIENNGHI.IKIENNGHI) AS ID_PHANLOAI,
      (SELECT CTEN FROM KN_TRALOI_PHANLOAI WHERE KN_TRALOI_PHANLOAI.IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI) AS TEN_PHANLOAI,
      (SELECT CTEN FROM QUOCHOI_KHOA WHERE QUOCHOI_KYHOP.IKHOA=IKHOA) AS TEN_KHOAHOP,
      KN_KIENNGHI.ITHAMQUYENDONVI AS ID_THAMQUYENCOQUAN,
      (SELECT CTEN FROM QUOCHOI_COQUAN WHERE KN_KIENNGHI.ITHAMQUYENDONVI=ICOQUAN) AS TEN_THAMQUYENCOQUAN,
      (SELECT CTEN FROM QUOCHOI_COQUAN WHERE KN_KIENNGHI.IDONVITIEPNHAN=ICOQUAN) AS TEN_DONVITIEPNHAN
      FROM KN_GIAMSAT,KN_KIENNGHI,KN_KIENNGHI_TRALOI,QUOCHOI_KYHOP,KN_TRALOI_PHANLOAI
      WHERE KN_GIAMSAT.IKIENNGHI=KN_KIENNGHI.IKIENNGHI 
            AND QUOCHOI_KYHOP.IKYHOP=KN_KIENNGHI.IKYHOP
            AND KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI
            AND KN_GIAMSAT.IDONGKIENNGHI=0 AND KN_TRALOI_PHANLOAI.IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI
            AND KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI WHERE CCODE='DANGGIAIQUYET')
            AND (pram03=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram03)
            AND (pram04=-1 OR KN_KIENNGHI.ILINHVUC=pram04)           
            AND KN_KIENNGHI_TRALOI.DNGAY_DUKIEN IS NOT NULL
            AND KN_KIENNGHI_TRALOI.DNGAY_DUKIEN BETWEEN pram01 AND pram02
            ),
    TBL2 as( select  KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP,
              (SELECT CTEN FROM QUOCHOI_COQUAN WHERE QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN) AS TENDONVITIEPNHAN_GOP
            FROM KN_KIENNGHI  INNER JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN WHERE ID_GOP>0
            )
     SELECT * FROM TBL1 LEFT JOIN TBL2 ON TBL1.ID_KIENNGHI=TBL2.ID_KIENNGHI_PARENT_GOP ;
     /*
     SELECT KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,
            QUOCHOI_KYHOP.CTEN AS TEN_KYHOP,
            QUOCHOI_KHOA.CTEN AS TEN_KHOAHOP,
            QUOCHOI_COQUAN.ICOQUAN AS ID_DONVI,
            QUOCHOI_COQUAN.CTEN AS TEN_DONVI,
            KN_KIENNGHI_TRALOI.ITINHTRANG AS TINHTRANG_TRALOI
    FROM KN_KIENNGHI
        INNER JOIN QUOCHOI_COQUAN ON KN_KIENNGHI.ITHAMQUYENDONVI=QUOCHOI_COQUAN.ICOQUAN
        INNER JOIN QUOCHOI_KYHOP ON KN_KIENNGHI.IKYHOP=QUOCHOI_KYHOP.IKYHOP
        INNER JOIN QUOCHOI_KHOA ON QUOCHOI_KYHOP.IKHOA=QUOCHOI_KHOA.IKHOA
        INNER JOIN KN_KIENNGHI_TRALOI ON KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI
    WHERE KN_KIENNGHI.ITINHTRANG =8
           AND (pram03=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram03)
           AND (pram04=-1 OR KN_KIENNGHI.ILINHVUC=pram04)           
           AND KN_KIENNGHI_TRALOI.DNGAY_DUKIEN IS NOT NULL
           AND KN_KIENNGHI_TRALOI.DNGAY_DUKIEN BETWEEN pram01 AND pram02;*/



  END PRO_BAOCAO_TK_PHULUC5;
  ----Bao cao 5B
  PROCEDURE PRO_BAOCAO_TK_PHULUC5B(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER, pram03 IN NUMBER) AS 
  BEGIN
  OPEN res FOR
    WITH TBL1 AS(
    SELECT KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI,KN_KIENNGHI.ID_GOP AS ID_GOP,
            (SELECT CTEN FROM LINHVUC_COQUAN WHERE ILINHVUC=KN_KIENNGHI.ILINHVUC) AS TEN_LINHVUC,
            KN_KIENNGHI.ILINHVUC AS ID_LINHVUC,KN_KIENNGHI.ITHAMQUYENDONVI AS ID_THAMQUYENCOQUAN,
            (SELECT CTEN FROM QUOCHOI_COQUAN WHERE ICOQUAN=KN_KIENNGHI.ITHAMQUYENDONVI) AS TEN_THAMQUYENCOQUAN,
            (SELECT CTEN FROM QUOCHOI_COQUAN WHERE ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN) AS TEN_DONVITIEPNHAN,
            (SELECT CTEN FROM KN_TRALOI_PHANLOAI WHERE IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI) AS TEN_PHANLOAI_TRALOI,
            KN_KIENNGHI_TRALOI.IPHANLOAI AS ID_PHANLOAI_TRALOI, KN_KIENNGHI_TRALOI.DNGAY_DUKIEN AS NGAY_DUKIENGIAIQUYET
    FROM KN_KIENNGHI,KN_KIENNGHI_TRALOI,KN_TRALOI_PHANLOAI 
    WHERE KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI AND KN_TRALOI_PHANLOAI.IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI
        AND  KN_TRALOI_PHANLOAI.IPARENT=(SELECT IPHANLOAI FROM KN_TRALOI_PHANLOAI WHERE CCODE='DANGGIAIQUYET')
        AND KN_KIENNGHI.IKYHOP=pram01
        AND (pram02=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram02)
        AND (pram03=-1 OR KN_KIENNGHI.ILINHVUC=pram03)
            ),
    TBL2 as( select  KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP,
              (SELECT CTEN FROM QUOCHOI_COQUAN WHERE QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN) AS TENDONVITIEPNHAN_GOP
            FROM KN_KIENNGHI  INNER JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN WHERE ID_GOP>0
            )
     SELECT * FROM TBL1 LEFT JOIN TBL2 ON TBL1.ID_KIENNGHI=TBL2.ID_KIENNGHI_PARENT_GOP 
     /*
     SELECT KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,
            (SELECT CTEN FROM LINHVUC_COQUAN WHERE ILINHVUC=KN_KIENNGHI.ILINHVUC) AS TENLINNHVUC,
            KN_KIENNGHI.ILINHVUC AS ID_LINHVUC,
            QUOCHOI_COQUAN.ICOQUAN AS ID_DONVI,
            QUOCHOI_COQUAN.CTEN AS TEN_DONVI,
            KN_KIENNGHI_TRALOI.ITINHTRANG AS TINHTRANG_TRALOI,
            KN_KIENNGHI_TRALOI.CTRALOI AS TRALOI_KIENNGHI
    FROM KN_KIENNGHI INNER JOIN QUOCHOI_COQUAN ON KN_KIENNGHI.ITHAMQUYENDONVI=QUOCHOI_COQUAN.ICOQUAN
        INNER JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC        
        INNER JOIN KN_KIENNGHI_TRALOI ON KN_KIENNGHI_TRALOI.IKIENNGHI=KN_KIENNGHI.IKIENNGHI  
    WHERE KN_KIENNGHI.IKYHOP=pram01
        AND (pram02=0 OR KN_KIENNGHI.IDONVITIEPNHAN=pram02)
        AND (pram03=-1 OR KN_KIENNGHI.ILINHVUC=pram03)
        AND LINHVUC_COQUAN.ICOQUAN=QUOCHOI_COQUAN.ICOQUAN*/
       ;

  END PRO_BAOCAO_TK_PHULUC5B;
  ----Bao cao 6
  ---pram01 in tungay, pram02 in denngay, pram03 in don vi giam sat
  PROCEDURE PRO_BAOCAO_TK_PHULUC6(res out sys_refcursor, pram01 in DATE, pram02 in DATE, pram03 in NUMBER)AS 
  BEGIN
  OPEN res FOR
    SELECT KN_DOANGIAMSAT.CTEN AS KEHOACH,
        KN_DOANGIAMSAT.CNOIDUNG AS NOIDUNG,
        QUOCHOI_COQUAN.ICOQUAN AS ID_DONVI,
        QUOCHOI_COQUAN.CTEN AS TEN_DONVI
    FROM KN_DOANGIAMSAT INNER JOIN QUOCHOI_COQUAN ON KN_DOANGIAMSAT.IDONVI=QUOCHOI_COQUAN.ICOQUAN
    WHERE (pram03=0 or KN_DOANGIAMSAT.IDONVI=pram03)
         AND KN_DOANGIAMSAT.DNGAYBATDAU BETWEEN pram01 AND pram02;

  END PRO_BAOCAO_TK_PHULUC6;
  ----Bao cao 7
  ---pram01 in kyhop,pram02 in truockyhop
  PROCEDURE PRO_BAOCAO_TK_PHULUC7(res out sys_refcursor, pram01 in NUMBER,pram02 in NUMBER)AS 
  BEGIN
  OPEN res FOR
     SELECT  DISTINCT (QUOCHOI_COQUAN.ICOQUAN) AS ID_DONVI,
            QUOCHOI_COQUAN.CTEN AS TEN_TINHTHANH,
            KN_VANBAN.DNGAYBANHANH AS NGAYNHAN
    FROM KN_VANBAN INNER JOIN QUOCHOI_COQUAN ON  KN_VANBAN.ICOQUANBANHANH=QUOCHOI_COQUAN.ICOQUAN
         INNER JOIN KN_TONGHOP ON KN_TONGHOP.ITONGHOP=KN_VANBAN.ITONGHOP 
    WHERE QUOCHOI_COQUAN.IPARENT=20
         AND KN_TONGHOP.IKYHOP=pram01
         AND KN_TONGHOP.ITRUOCKYHOP=pram02
         AND KN_VANBAN.CLOAI='tonghop_chuyenxuly'
         --AND KN_VANBAN.ICOQUANNHAN=4
    ORDER BY KN_VANBAN.DNGAYBANHANH;
  END PRO_BAOCAO_TK_PHULUC7;
  ----Bao cao PHANLOAI
  --pram01 in kyhop, pram02 IN donviXULY,pram03 IN linhvuc
  PROCEDURE PRO_BAOCAO_TK_PHANLOAI(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER,pram03 IN NUMBER)AS 
  BEGIN
  OPEN res FOR
    WITH TBL1 AS(
    SELECT    
              KN_KIENNGHI_TRALOI.IPHANLOAI AS ID_TRALOI_PHANLOAI,
              PHANLOAI.CTEN AS TEN_TRALOI_PHANLOAI,PHANLOAI.IPARENT AS ID_PARENT_TRALOI_PHANLOAI,
              PHANLOAI.IVITRI AS VITRI_PHANLOAI,KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI,KN_KIENNGHI.ID_GOP AS ID_GOP,
              KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,QUOCHOI_COQUAN.CTEN AS TEN_DONVITIEPNHAN,
              PHANLOAI_PARENT.CTEN AS TEN_PHANLOAI_PARENT
      FROM KN_KIENNGHI_TRALOI INNER JOIN KN_KIENNGHI ON KN_KIENNGHI_TRALOI.IKIENNGHI=KN_KIENNGHI.IKIENNGHI
          LEFT JOIN KN_TRALOI_PHANLOAI PHANLOAI ON PHANLOAI.IPHANLOAI=KN_KIENNGHI_TRALOI.IPHANLOAI
          LEFT JOIN KN_TRALOI_PHANLOAI PHANLOAI_PARENT ON PHANLOAI_PARENT.IPHANLOAI=PHANLOAI.IPARENT
          LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN
      WHERE (pram01 =0 or KN_KIENNGHI.IKYHOP=pram01)
            AND KN_KIENNGHI.ITHAMQUYENDONVI=pram02
            AND (pram03 =-1 or KN_KIENNGHI.ILINHVUC=pram03) 
            ),
    TBL2 AS( select  KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP,
            QUOCHOI_COQUAN.CTEN AS TENDONVITIEPNHAN_GOP
            FROM KN_KIENNGHI  INNER JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN WHERE ID_GOP>0
            )
    SELECT TBL1.*,TBL2.* FROM TBL1 LEFT JOIN TBL2 ON TBL1.ID_KIENNGHI=TBL2.ID_KIENNGHI_PARENT_GOP 
            ORDER BY TBL1.VITRI_PHANLOAI; 
      /*                
     SELECT   KN_TRALOI_PHANLOAI.CTEN AS TEN_PHANLOAI,
              KN_TRALOI_PHANLOAI.IPHANLOAI AS ID_PHANLOAI,
              KN_TRALOI_PHANLOAI.IPARENT AS ID_PARENT_PHANLOAI,
              KN_KIENNGHI_TRALOI.IPHANLOAI AS ID_TRALOI_PHANLOAI,
              KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI,
              KN_KIENNGHI.ID_KIENNGHI_PARENT AS ID_KIENNGHI_PARENT,
              KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,
              KN_KIENNGHI.CNOIDUNG_TRUNG AS NOIDUNG_KIENNGHI_CUNGNOIDUNG,
              (select QUOCHOI_COQUAN.CTEN FROM QUOCHOI_COQUAN WHERE 
              QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN AND 
              QUOCHOI_COQUAN.IPARENT=20) AS TEN_DIAPHUONG
      FROM    KN_TRALOI_PHANLOAI LEFT JOIN KN_KIENNGHI_TRALOI ON KN_TRALOI_PHANLOAI.IPHANLOAI= KN_KIENNGHI_TRALOI.IPHANLOAI
              LEFT JOIN KN_KIENNGHI ON KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI
              LEFT JOIN QUOCHOI_COQUAN ON KN_KIENNGHI.IDONVITIEPNHAN=QUOCHOI_COQUAN.ICOQUAN
      WHERE   KN_KIENNGHI.IKYHOP=1
              AND KN_KIENNGHI.ITHAMQUYENDONVI=pram02
              AND (pram03 =-1 or KN_KIENNGHI.ILINHVUC=pram03) 
              ;
      */      
  END PRO_BAOCAO_TK_PHANLOAI;
  ----Bao cao TRALOI
  --- pram01 in kyhop, pram02 IN DONVITHAMQUYEN, pram03 IN linhvuc
  PROCEDURE PRO_BAOCAO_TK_TRALOI(res out sys_refcursor, pram01 in NUMBER, pram02 IN NUMBER, pram03 IN NUMBER) AS 
  BEGIN
  OPEN res FOR
     WITH TBL1 AS(
      select 
        KN_KIENNGHI.ITHAMQUYENDONVI AS ID_THAMQUYENDONVI,
        COQUAN_TIEPNHAN.CTEN AS TEN_DONVITIEPNHAN,
        COQUAN_THAMQUYEN.CTEN AS TEN_THAMQUYENDONVI,
        KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI, KN_KIENNGHI.ID_GOP AS ID_GOP,KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI,     
        COQUAN_THAMQUYEN.IPARENT AS ID_THAMQUYENDONVI_PARENT,COQUAN_THAMQUYEN_PARENT.CTEN AS TEN_THAMQUYENDONVI_PARENT,
        COQUAN_THAMQUYEN_PARENT.IVITRI AS VITRI_COQUAN_THAMQUYEN_PARENT,
        KN_KIENNGHI_TRALOI.CSOVANBAN AS TRALOI_SOVANBAN,
        KN_KIENNGHI_TRALOI.CTRALOI AS TRALOI_NOIDUNG,
        KN_KIENNGHI_TRALOI.DNGAYBANHANH AS TRALOI_NGAYBANHANH_VANBAN        
      FROM KN_KIENNGHI_TRALOI
      INNER JOIN KN_KIENNGHI ON KN_KIENNGHI_TRALOI.IKIENNGHI=KN_KIENNGHI.IKIENNGHI
      LEFT JOIN QUOCHOI_COQUAN COQUAN_TIEPNHAN ON COQUAN_TIEPNHAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN
      LEFT JOIN QUOCHOI_COQUAN COQUAN_THAMQUYEN ON COQUAN_THAMQUYEN.ICOQUAN=KN_KIENNGHI.ITHAMQUYENDONVI
      LEFT JOIN QUOCHOI_COQUAN COQUAN_THAMQUYEN_PARENT ON COQUAN_THAMQUYEN_PARENT.ICOQUAN=COQUAN_THAMQUYEN.IPARENT
      WHERE  (pram02=0 OR KN_KIENNGHI.ITHAMQUYENDONVI=pram02) AND 
      (pram03=-1 OR KN_KIENNGHI.ILINHVUC=pram03)
      AND (pram01=0 OR KN_KIENNGHI.IKYHOP=pram01) 
      ORDER BY KN_KIENNGHI.ID_GOP),
    TBL2 as(
      select 
      KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_CHILD_GOP,
      QUOCHOI_COQUAN.CTEN AS TENDONVITIEPNHAN_GOP
      FROM KN_KIENNGHI LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN WHERE ID_GOP>0   
    )

    select TBL1.*,TBL2.* from TBL1 LEFT JOIN TBL2 on TBL1.ID_KIENNGHI=TBL2.ID_KIENNGHI_CHILD_GOP 
    ORDER BY TBL1.VITRI_COQUAN_THAMQUYEN_PARENT;

  END PRO_BAOCAO_TK_TRALOI;


	----Bao cao PRO_BAOCAO_TK_TRALOIKNTC
PROCEDURE PRO_BAOCAO_TK_TRALOIKNTC(res out sys_refcursor, pram01 in NUMBER, pram02 in NUMBER, pram03 in NUMBER)AS 
  BEGIN
  OPEN res FOR
    SELECT T1.IDIAPHUONG1, T1.IKYHOP,T1.CNOIDUNG, T1.ITHAMQUYENDONVI, T2.CSOVANBAN, T2.DNGAYBANHANH, T2.CTRALOI,
    DP.CTYPE || ' ' || DP.CTEN as CuTri, COQUAN_TQ.CTEN as CoQuanThamQuyen
    FROM KN_KIENNGHI T1
    INNER JOIN KN_KIENNGHI_TRALOI T2 ON T1.IKIENNGHI=T2.IKIENNGHI
    LEFT JOIN KN_CHUONGTRINH KN_CT ON T1.iCHUONGTRINH = KN_CT.iCHUONGTRINH
    LEFT JOIN DIAPHUONG DP ON DP.IDIAPHUONG = T1.IDIAPHUONG1
    LEFT JOIN QUOCHOI_COQUAN COQUAN_TQ ON COQUAN_TQ.ICOQUAN=T2.ICOQUANTRALOI
    WHERE (pram02 = 0 or T1.IKYHOP = pram02) and (pram03 = 2 or T1.ITRUOCKYHOP = pram03)
    and T1.IDOITUONGGUI  = pram01
    ORDER BY T2.DNGAYBANHANH;
  END PRO_BAOCAO_TK_TRALOIKNTC;

	---Bao cao PRO_BAOCAO_TK_TRALOIKN_DENDBQH
	PROCEDURE PRO_BAOCAO_TK_TRALOIKN_DENDBQH(res out sys_refcursor, pram01 in NUMBER, pram02 in VARCHAR2, pram03 in NUMBER)AS 
  BEGIN
  OPEN res FOR
    SELECT  T1.CNOIDUNG,T1.IKYHOP, T1.ITHAMQUYENDONVI,  T2.CSOVANBAN, T2.DNGAYBANHANH, T2.GHICHU_KQ, T2.CCOQUANTRALOI , KH.CTEN , K.IKHOA
    FROM KN_KIENNGHI T1
    INNER JOIN KN_KIENNGHI_TRALOI T2 ON T1.IKIENNGHI=T2.IKIENNGHI
    JOIN QUOCHOI_KYHOP KH on KH.IKYHOP = T1.IKYHOP
    JOIN QUOCHOI_KHOA K on K.IKHOA = KH.IKHOA
    WHERE pram02 like '%x'||T1.IKYHOP||'x%' and K.IKHOA = pram03
    and T1.IDOITUONGGUI = pram01
    ORDER BY T2.DNGAYBANHANH;
  END PRO_BAOCAO_TK_TRALOIKN_DENDBQH;
END PKG_KIENNGHI_BAOCAO;

