CREATE OR REPLACE
PACKAGE BODY "PKG_KHIEUNAI_TOCAO" AS

  /*

  PROCEDURE PRO_TRACUUDON(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT

                                        , P_ITINHTRANGDON IN INT, P_IDONVITHULY IN INT,P_IDONVI IN INT ,P_INGUOINHAN IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

  BEGIN

  OPEN res FOR

   WITH LIST_TRACUUDON AS(

  SELECT KNTC_DON.IDON

  ,QUOCHOI_COQUAN.CTEN

  ,KNTC_DON.CNOIDUNG

  ,KNTC_DON.DNGAYNHAN

  ,KNTC_LOAIDON.CTEN AS CLOAIDON,

    LINHVUC.CTEN AS CLINHVUC,

    KNTC_NOIDUNGDON.CTEN AS CNOIDUNGDON,

    KNTC_NGUONDON.CTEN AS CNGUONDON,

    KNTC_TINHCHAT.CTEN AS CTINHCHAT,

    TINH.CTEN AS CTINHTHANH,

    ITINHTRANGXULY AS TINHTRANG 

    ,KNTC_DON.CNGUOIGUI_DIACHI

    ,HUYEN.CTEN AS CTENHUYEN

    ,KNTC_DON.CNGUOIGUI_TEN

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN

    ,KNTC_DON.IDONVITIEPNHAN

    ,KNTC_DON.IDONVITHULY

    ,KNTC_DON.ISOLUONGTRUNG

    ,KNTC_DON.CGHICHU

    ,KNTC_DON.IDELETE

    ,KNTC_DON.IUSER

    ,C.SODONTRUNG

  FROM (SELECT KNTC_DON.* FROM (

                SELECT * FROM (

                SELECT IDON FROM KNTC_DON

                where IDONVITHULY = P_IDONVI

                UNION

                select IDON FROM KNTC_DON_LICHSU

                WHERE IDONVIGUI = P_IDONVI GROUP BY IDON)A GROUP BY IDON)B INNER JOIN KNTC_DON ON B.IDON = KNTC_DON.IDON) KNTC_DON

                LEFT JOIN (SELECT COUNT(*) AS SODONTRUNG,KNTC_DON.IDON FROM (

                 SELECT IDON FROM KNTC_DON

                  CONNECT BY PRIOR IDON=IDONTRUNG

                  UNION ALL SELECT IDON FROM KNTC_DON WHERE IDONTRUNG = -1

                  UNION ALL SELECT IDON FROM KNTC_DON CONNECT BY PRIOR IDON=-1 )KNTC_DON

                  GROUP BY KNTC_DON.IDON

                  ORDER BY KNTC_DON.IDON DESC)C ON C.IDON = KNTC_DON.IDON

                LEFT JOIN QUOCHOI_COQUAN ON KNTC_DON.IDONVITHULY = QUOCHOI_COQUAN.ICOQUAN

                LEFT JOIN KNTC_LOAIDON ON KNTC_DON.ILOAIDON = KNTC_LOAIDON.ILOAIDON

                LEFT JOIN LINHVUC ON KNTC_DON.ILINHVUC = LINHVUC.ILINHVUC

                LEFT JOIN KNTC_NOIDUNGDON ON KNTC_DON.INOIDUNG = KNTC_NOIDUNGDON.INOIDUNG

                LEFT JOIN KNTC_NGUONDON ON KNTC_DON.INGUONDON = KNTC_NGUONDON.INGUONDON

                LEFT JOIN KNTC_TINHCHAT ON KNTC_DON.ITINHCHAT = KNTC_TINHCHAT.ITINHCHAT             

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

                LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON KNTC_DON.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

    WHERE (P_IDONVITHULY = 0 OR KNTC_DON.IDONVITHULY = P_IDONVITHULY)

   AND (P_ITINHTRANGDON = -1 OR KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGDON)

    AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

    AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

    AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_TRACUUDON) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_TRACUUDON ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1);

  END PRO_TRACUUDON;

  */

  PROCEDURE PRO_TRACUUDON(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT

                                        , P_ITINHTRANGDON IN INT, P_IDONVITHULY IN INT,P_IDONVI IN INT ,P_INGUOINHAN IN INT

																				, P_IUSER IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

  BEGIN

  OPEN res FOR

   WITH LIST_TRACUUDON AS(

  SELECT KNTC_DON.IDON

  ,QUOCHOI_COQUAN.CTEN

  ,KNTC_DON.CNOIDUNG

  ,KNTC_DON.DNGAYNHAN

  ,KNTC_LOAIDON.CTEN AS CLOAIDON,

    LINHVUC.CTEN AS CLINHVUC,

    KNTC_NOIDUNGDON.CTEN AS CNOIDUNGDON,

    KNTC_NGUONDON.CTEN AS CNGUONDON,

    KNTC_TINHCHAT.CTEN AS CTINHCHAT,

    TINH.CTEN AS CTINHTHANH,

    ITINHTRANGXULY AS TINHTRANG 

    ,KNTC_DON.CNGUOIGUI_DIACHI

    ,HUYEN.CTEN AS CTENHUYEN

    ,KNTC_DON.CNGUOIGUI_TEN

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN

    ,KNTC_DON.IDONVITIEPNHAN

    ,KNTC_DON.IDONVITHULY

    ,KNTC_DON.ISOLUONGTRUNG

    ,KNTC_DON.CGHICHU

    ,KNTC_DON.IDELETE

    ,KNTC_DON.IUSER

    ,C.SODONTRUNG
  FROM (SELECT KNTC_DON.* FROM (

                SELECT * FROM (

                SELECT IDON FROM KNTC_DON

                where IDONVITHULY = P_IDONVI

                UNION

                SELECT IDON FROM KNTC_DON_LICHSU

                WHERE IDONVIGUI = P_IDONVI GROUP BY IDON)A GROUP BY IDON)B INNER JOIN KNTC_DON ON B.IDON = KNTC_DON.IDON) KNTC_DON LEFT JOIN QUOCHOI_COQUAN ON KNTC_DON.IDONVITHULY = QUOCHOI_COQUAN.ICOQUAN

                LEFT JOIN KNTC_LOAIDON ON KNTC_DON.ILOAIDON = KNTC_LOAIDON.ILOAIDON

                LEFT JOIN LINHVUC ON KNTC_DON.ILINHVUC = LINHVUC.ILINHVUC

                LEFT JOIN KNTC_NOIDUNGDON ON KNTC_DON.INOIDUNG = KNTC_NOIDUNGDON.INOIDUNG

                LEFT JOIN KNTC_NGUONDON ON KNTC_DON.INGUONDON = KNTC_NGUONDON.INGUONDON

                LEFT JOIN KNTC_TINHCHAT ON KNTC_DON.ITINHCHAT = KNTC_TINHCHAT.ITINHCHAT             

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

                LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON KNTC_DON.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

                LEFT JOIN (
                    SELECT SUM(SODONTRUNG) AS SODONTRUNG, IDON FROM (
                    SELECT  COUNT(*) AS SODONTRUNG,IDONTRUNG AS IDON FROM KNTC_DON GROUP BY IDONTRUNG
                    UNION ALL
                    SELECT COUNT(*) AS SODONTRUNG, KNTC_DONTRUNG.IDON FROM KNTC_DON INNER JOIN KNTC_DON  KNTC_DONTRUNG  ON KNTC_DON.IDONTRUNG = KNTC_DONTRUNG.IDONTRUNG
                    WHERE  KNTC_DONTRUNG.IDONTRUNG != -1 AND KNTC_DONTRUNG.IDONTRUNG !=0  GROUP BY KNTC_DONTRUNG.IDON) 
                    GROUP BY IDON 
                )C ON C.IDON = KNTC_DON.IDON

    WHERE (P_IDONVITHULY = 0 OR KNTC_DON.IDONVITHULY = P_IDONVITHULY)

    AND (P_ITINHTRANGDON = -1 OR KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGDON)

    --AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

		AND (P_IUSER = 0 OR KNTC_DON.IUSER = P_IUSER)

    AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

    AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_TRACUUDON) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_TRACUUDON ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )


        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1);

  END PRO_TRACUUDON;





  PROCEDURE PRO_LISTDON(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT ,P_INGUOINHAN IN INT) AS

  BEGIN

  OPEN res FOR

    SELECT KNTC_DON.IDON

    , KNTC_DON.CNOIDUNG

    ,KNTC_DON.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,KNTC_DON.DNGAYNHAN

    ,KNTC_DON.IDONVITHULY

    ,DVTHULY.CTEN

    ,KNTC_DON.ITHAMQUYEN

    ,KNTC_DON.IDUDIEUKIEN

    ,KNTC_DON.ITINHTRANGXULY

    ,KNTC_DON.IUSER

    ,KNTC_DON.IDONTRUNG

    ,KNTC_DON.CNGUOIGUI_TEN

    ,KNTC_DON.IUSER_DUOCGIAOXULY

    ,KNTC_DON.IDUDIEUKIEN_KETQUA

    ,KNTC_DON.ILUUTHEODOI

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,KNTC_DON.IDONVITIEPNHAN,KNTC_DON.IDANHGIA,KNTC_DON.CGHICHUDANHGIA

    FROM KNTC_DON

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = KNTC_DON.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON KNTC_DON.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE(P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

    AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY KNTC_DON.IDON DESC;

  END PRO_LISTDON;

  PROCEDURE PRO_LISTLICHSUDON(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT,P_INGUOINHAN IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT, P_IDONVI IN INT, P_ICHUYENXULY IN INT) AS

  BEGIN

  OPEN res FOR

    SELECT distinct  A.IDON

    ,A.CNOIDUNG

    ,A.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,A.DNGAYNHAN

    ,A.IDONVITHULY

    ,DVTHULY.CTEN

    ,A.ITHAMQUYEN

    ,A.IDUDIEUKIEN

    ,A.ITINHTRANGXULY

    ,A.IUSER

    ,A.IDONTRUNG

    ,A.CNGUOIGUI_TEN

    ,A.IUSER_DUOCGIAOXULY

    ,A.IDUDIEUKIEN_KETQUA

    ,A.ILUUTHEODOI

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,A.IDONVITIEPNHAN,A.IDANHGIA,A.CGHICHUDANHGIA

    FROM (SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE KNTC_DON_LICHSU.IDONVIGUI=P_IDONVI AND KNTC_DON_LICHSU.ICHUYENXULY = P_ICHUYENXULY) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE(P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

    AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (A.IDONVITHULY <> P_IDONVI)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC;

  END PRO_LISTLICHSUDON;

  PROCEDURE PRO_LISTDONDAXULY(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT,P_INGUOINHAN IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT, P_IDONVIXULY IN INT, P_ITRANGTHAI IN INT) AS

  BEGIN

  OPEN res FOR

    SELECT DISTINCT  A.IDON

    ,A.CNOIDUNG

    ,A.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,A.DNGAYNHAN

    ,A.IDONVITHULY

    ,DVTHULY.CTEN

    ,A.ITHAMQUYEN

    ,A.IDUDIEUKIEN

    ,A.ITINHTRANGXULY

    ,A.IUSER

    ,A.IDONTRUNG

    ,A.CNGUOIGUI_TEN

    ,A.IUSER_DUOCGIAOXULY

    ,A.IDUDIEUKIEN_KETQUA

    ,A.ILUUTHEODOI

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,A.IDONVITIEPNHAN,A.IDANHGIA,A.CGHICHUDANHGIA

    FROM (

    SELECT * FROM KNTC_DON WHERE KNTC_DON.IDONVITHULY = P_IDONVIXULY  AND KNTC_DON.ITINHTRANGXULY = P_ITRANGTHAI

    UNION

    SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE  KNTC_DON_LICHSU.IDONVIXULY = P_IDONVIXULY AND KNTC_DON_LICHSU.ITRANGTHAI = P_ITRANGTHAI) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE(P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

   AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC;

    END PRO_LISTDONDAXULY;

  PROCEDURE PRO_DONMOICAPNHAT(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT

                                        , P_IDONVITIEPNHAN IN INT, P_ITINHTRANGXULY IN INT,P_IUSER IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

    BEGIN

    OPEN res FOR

    WITH LIST_DONMOICAPNHAT AS(

          SELECT KNTC_DON.IDON

          ,KNTC_DON.CNOIDUNG

          ,KNTC_DON.CNGUOIGUI_DIACHI

          ,TINH.CTEN AS CTENTINH

          ,HUYEN.CTEN AS CTENHUYEN

          ,KNTC_DON.DNGAYNHAN

          ,KNTC_DON.CNGUOIGUI_TEN

          FROM KNTC_DON

                --LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = KNTC_DON.IDONVITHULY

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

          WHERE KNTC_DON.IDELETE <> 1
          AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

          --AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

          AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

          AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

          AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

          AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

          AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

          AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

          AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

          AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

          AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

          AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

          AND (P_IUSER = 0 OR KNTC_DON.IUSER = P_IUSER)

					AND (KNTC_DON.IKHOA = P_IKHOA or P_IKHOA = 0)  

          AND (KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY)

          AND (KNTC_DON.IDONVITIEPNHAN = P_IDONVITIEPNHAN)

          AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

          ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONMOICAPNHAT) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONMOICAPNHAT ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1)

    ORDER BY STT;

  END PRO_DONMOICAPNHAT;  

     PROCEDURE PRO_DONCHOXULY(res out sys_refcursor, P_USER in INT
										, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT
                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE
                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT
                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT
                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT
                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT
                                        , P_IDONVITIEPNHAN IN INT, P_ITINHTRANGXULY IN INT,P_IUSER_DUOCGIAOXULY IN INT
                                        , P_IDIEUKIENXULY IN INT
                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

    BEGIN

    OPEN res FOR

    WITH LIST_DONCHOXULY AS(

          SELECT KNTC_DON.IDON

          ,KNTC_DON.CNOIDUNG

          ,KNTC_DON.CNGUOIGUI_DIACHI

          ,TINH.CTEN AS CTENTINH

          ,HUYEN.CTEN AS CTENHUYEN

          ,KNTC_DON.DNGAYNHAN

          ,KNTC_DON.CNGUOIGUI_TEN

          FROM KNTC_DON

                --LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = KNTC_DON.IDONVITHULY

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

          WHERE 1=1 
          AND (( P_USER = 0 or  KNTC_DON.IUSER =  P_USER) OR (P_IUSER_DUOCGIAOXULY = 0 OR KNTC_DON.IUSER_DUOCGIAOXULY = P_IUSER_DUOCGIAOXULY)) -- phan quyen theo user va tham quyen xu ly

          AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

          AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

          AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

          AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

          AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

          AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

          AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

          AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

          AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

          AND (P_IDOANDONGNGUOI = 0 OR KNTC_DON.IDOANDONGNGUOI = P_IDOANDONGNGUOI)

          AND (P_IKHOA = 0 OR KNTC_DON.IKHOA = P_IKHOA) 

          AND (P_IDIEUKIENXULY = -2 OR KNTC_DON.IDUDIEUKIEN = P_IDIEUKIENXULY) 

          AND (P_DTUNGAY='' OR P_DTUNGAY IS NULL OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

          AND (P_DDENNGAY='' OR P_DDENNGAY IS NULL OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

          --AND (P_IUSER_DUOCGIAOXULY = 0 OR KNTC_DON.IUSER_DUOCGIAOXULY = P_IUSER_DUOCGIAOXULY)

          AND (KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY)

          AND (KNTC_DON.IDONVITIEPNHAN = P_IDONVITIEPNHAN)

          AND (P_CKEY='' OR P_CKEY IS NULL OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

          ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM
    (
        SELECT k.*,(SELECT COUNT(*) FROM LIST_DONCHOXULY) AS TOTAL,

        ROWNUM STT FROM( select * from LIST_DONCHOXULY ) k

        WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )
    )

    WHERE STT >= (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;
  END PRO_DONCHOXULY;   

  PROCEDURE PRO_DONDAPHANLOAI(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT

                                        , P_IDONVITIEPNHAN IN INT, P_ITINHTRANGXULY IN INT,P_IUSER_DUOCGIAOXULY IN INT

                                        , P_ITHAMQUYEN IN INT,P_IDIEUKIEN IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR

    WITH LIST_DONDAPHANLOAI AS(

          SELECT KNTC_DON.IDON

          ,KNTC_DON.CNOIDUNG

          ,KNTC_DON.CNGUOIGUI_DIACHI

          ,TINH.CTEN AS CTENTINH

          ,HUYEN.CTEN AS CTENHUYEN

          ,KNTC_DON.DNGAYNHAN

          ,KNTC_DON.CNGUOIGUI_TEN

          FROM KNTC_DON

                --LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = KNTC_DON.IDONVITHULY

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

          WHERE 1=1 
          AND ( ( P_USER =0 or   KNTC_DON.IUSER = P_USER) OR (P_IUSER_DUOCGIAOXULY = 0 OR KNTC_DON.IUSER_DUOCGIAOXULY = P_IUSER_DUOCGIAOXULY))

          AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

          AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

          AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

          AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

          AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

          AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

          AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

          AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

          AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

          AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

					AND (P_IKHOA = 0 OR KNTC_DON.IKHOA = P_IKHOA ) 

          AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

          AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

          --AND (P_IUSER_DUOCGIAOXULY = 0 OR KNTC_DON.IUSER_DUOCGIAOXULY = P_IUSER_DUOCGIAOXULY)

          AND (KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY)

          AND (KNTC_DON.ITHAMQUYEN = P_ITHAMQUYEN)

          AND (KNTC_DON.IDUDIEUKIEN = P_IDIEUKIEN)

          AND (KNTC_DON.IDONVITIEPNHAN = P_IDONVITIEPNHAN)

          AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

          ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONDAPHANLOAI) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONDAPHANLOAI ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

  END PRO_DONDAPHANLOAI; 

  PROCEDURE PRO_LISTDONDANHANXULY(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                         , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT
                                        , P_IDONVITHULY IN INT, P_ITINHTRANGXULY IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR

    WITH LIST_DONDANHANXULY AS(

          SELECT KNTC_DON.IDON

          ,KNTC_DON.CNOIDUNG

          ,KNTC_DON.CNGUOIGUI_DIACHI

          ,TINH.CTEN AS CTENTINH

          ,HUYEN.CTEN AS CTENHUYEN

          ,KNTC_DON.DNGAYNHAN

          ,KNTC_DON.CNGUOIGUI_TEN

          FROM KNTC_DON

                --LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = KNTC_DON.IDONVITHULY

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

          WHERE(P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

          AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

          AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

          AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

          AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

          AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

          AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

          AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

          AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

          AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

					AND (KNTC_DON.IKHOA = P_IKHOA or P_IKHOA = 0) 

          AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

          AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

          AND (KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY)     

          AND (KNTC_DON.IDONVITHULY = P_IDONVITHULY)

          AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

          ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONDANHANXULY) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONDANHANXULY ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

    END PRO_LISTDONDANHANXULY;

  PROCEDURE PRO_LISTDALUANCHUYEN(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT,P_INGUOINHAN IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT, P_IDONVI IN INT, P_ICHUYENXULY IN INT, P_ITINHTRANGXULY IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR 

    WITH LIST_DALUANCHUYEN AS(

    SELECT distinct  A.IDON

    ,A.CNOIDUNG

    ,A.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,A.DNGAYNHAN

    ,A.IDONVITHULY

    ,DVTHULY.CTEN

    ,A.ITHAMQUYEN

    ,A.IDUDIEUKIEN

    ,A.ITINHTRANGXULY

    ,A.IUSER

    ,A.IDONTRUNG

    ,A.CNGUOIGUI_TEN

    ,A.IUSER_DUOCGIAOXULY

    ,A.IDUDIEUKIEN_KETQUA

    ,A.ILUUTHEODOI

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,A.IDONVITIEPNHAN,A.IDANHGIA,A.CGHICHUDANHGIA

    FROM (SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE KNTC_DON_LICHSU.IDONVIGUI=P_IDONVI AND KNTC_DON_LICHSU.ICHUYENXULY = P_ICHUYENXULY) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE(P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

   AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (A.IDONVITHULY <> P_IDONVI)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (P_ITINHTRANGXULY = 0 OR ITINHTRANGXULY = P_ITINHTRANGXULY)

		AND (A.IKHOA = P_IKHOA or P_IKHOA = 0)

    AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DALUANCHUYEN) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DALUANCHUYEN ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

  END PRO_LISTDALUANCHUYEN; 

   PROCEDURE PRO_LISTDACHUYENXULY(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT
                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE
                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT
                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT
                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT,P_INGUOINHAN IN INT
                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT, P_IDONVI IN INT, P_ICHUYENXULY IN INT 																		 , P_ITINHTRANGXULY IN INT, P_IUSER_GIAOXULY IN INT
                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR 

    WITH LIST_DACHUYEN AS(

    SELECT distinct  A.IDON

    ,A.CNOIDUNG

    ,A.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,A.DNGAYNHAN

    ,A.IDONVITHULY

    ,DVTHULY.CTEN

    ,A.ITHAMQUYEN

    ,A.IDUDIEUKIEN

    ,A.ITINHTRANGXULY

    ,A.IUSER

    ,A.IDONTRUNG

    ,A.CNGUOIGUI_TEN

    ,A.IUSER_DUOCGIAOXULY

    ,A.IDUDIEUKIEN_KETQUA

		,A.ICANHBAO

		,A.INGAYQUYDINH

    ,A.ILUUTHEODOI

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,A.IDONVITIEPNHAN,A.IDANHGIA,A.CGHICHUDANHGIA

    FROM (SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE KNTC_DON_LICHSU.IDONVIGUI=P_IDONVI AND KNTC_DON_LICHSU.ICHUYENXULY = P_ICHUYENXULY) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE 

   ( ( P_USER =0 or   A.IUSER = P_USER) OR (P_IUSER_GIAOXULY = 0 OR A.IUSER_GIAOXULY = P_IUSER_GIAOXULY or A.IUSER_DUOCGIAOXULY = P_USER ))

   AND    (P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

   AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

	--AND (P_IUSER_GIAOXULY = 0 OR A.IUSER_GIAOXULY = P_IUSER_GIAOXULY)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    --AND (A.IDONVITHULY <> P_IDONVI)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (A.ITINHTRANGXULY  = 3)

    AND (P_ITINHTRANGXULY = 0 OR A.ITINHTRANGXULY = P_ITINHTRANGXULY)

		AND (A.IKHOA = P_IKHOA or P_IKHOA = 0) 

    AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DACHUYEN) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DACHUYEN ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

  END PRO_LISTDACHUYENXULY;

  PROCEDURE PRO_LISTDACHUYENXULYCOTRALOI(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT
                                        , P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT,P_INGUOINHAN IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT, P_IDONVI IN INT, P_ICHUYENXULY IN INT, P_ITINHTRANGXULY IN INT, P_IUSER_GIAOXULY IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR 

    WITH LIST_DACHUYENCOTRALOI AS(

    SELECT distinct  A.IDON

    ,A.CNOIDUNG

    ,A.CNGUOIGUI_DIACHI

    ,TINH.CTEN AS CTENTINH

    ,HUYEN.CTEN AS CTENHUYEN

    ,A.DNGAYNHAN

    ,A.IDONVITHULY

    ,DVTHULY.CTEN

    ,A.ITHAMQUYEN

    ,A.IDUDIEUKIEN

    ,A.ITINHTRANGXULY

    ,A.IUSER

    ,A.IDONTRUNG

    ,A.CNGUOIGUI_TEN

    ,A.IUSER_DUOCGIAOXULY

    ,A.IDUDIEUKIEN_KETQUA

    ,A.ILUUTHEODOI

    ,A.INGAYQUYDINH

    ,A.ICANHBAO

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN,A.IDONVITIEPNHAN,A.IDANHGIA,A.CGHICHUDANHGIA

    FROM (SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE KNTC_DON_LICHSU.IDONVIGUI=P_IDONVI AND KNTC_DON_LICHSU.ICHUYENXULY = P_ICHUYENXULY) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE 1=1 
   AND ( ( P_USER =0 or   A.IUSER = P_USER) OR (P_IUSER_GIAOXULY = 0 OR A.IUSER_GIAOXULY = P_IUSER_GIAOXULY or A.IUSER_DUOCGIAOXULY = P_USER ))

   AND (P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

   AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

		AND (P_IUSER_GIAOXULY = 0 OR A.IUSER_GIAOXULY =P_IUSER_GIAOXULY)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    --AND (A.IDONVITHULY <> P_IDONVI)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

    AND (A.ITINHTRANGXULY = 4 OR A.ITINHTRANGXULY = 6 OR A.ITINHTRANGXULY = 8 OR A.ITINHTRANGXULY = 9)

    AND (P_ITINHTRANGXULY = 0 OR A.ITINHTRANGXULY = P_ITINHTRANGXULY)

    AND (P_IKHOA = 0 OR A.IKHOA = P_IKHOA)

    AND (P_DTUNGAY ='' OR P_DTUNGAY IS NULL OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR P_DDENNGAY IS NULL OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR P_CKEY IS NULL OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DACHUYENCOTRALOI) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DACHUYENCOTRALOI ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

  END PRO_LISTDACHUYENXULYCOTRALOI; 

  PROCEDURE PRO_LISTDONDAXULYGIAIQUYET(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                         , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT

                                        , P_IDONVITHULY IN INT, P_ITINHTRANGXULY IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT)AS

    BEGIN

    OPEN res FOR

    WITH LIST_DONDAXULY AS(

          SELECT A.IDON

          ,A.CNOIDUNG

          ,A.CNGUOIGUI_DIACHI

          ,TINH.CTEN AS CTENTINH

          ,HUYEN.CTEN AS CTENHUYEN

          ,A.DNGAYNHAN

          ,A.CNGUOIGUI_TEN

          FROM (

    SELECT * FROM KNTC_DON WHERE KNTC_DON.IDONVITHULY = P_IDONVITHULY  AND KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY

    UNION

    SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE  KNTC_DON_LICHSU.IDONVIXULY = P_IDONVITHULY AND KNTC_DON_LICHSU.ITRANGTHAI = P_ITINHTRANGXULY) A

          LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY

          LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0

          LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1

          LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

   WHERE 1=1 
   AND ( ( P_USER =0 or   A.IUSER = P_USER) OR ( A.IUSER_GIAOXULY = P_USER or A.IUSER_DUOCGIAOXULY = P_USER ))
   AND (P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)

   AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)

    AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR A.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

		 AND (A.IKHOA = P_IKHOA or P_IKHOA = 0) 

    AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY A.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONDAXULY) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONDAXULY ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;

    END PRO_LISTDONDAXULYGIAIQUYET;

  PROCEDURE PRO_LISTDONTRUNG(res out sys_refcursor, P_CKEY in NVARCHAR2, P_IDOANDONGNGUOI IN INT



                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE



                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT



                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT



                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT



                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT



                                        , P_ITINHTRANGDON IN INT, P_IDONVITHULY IN INT,P_IDONVI IN INT) AS



  BEGIN



  OPEN res FOR



  SELECT listDon.IDON



  ,QUOCHOI_COQUAN.CTEN



  ,listDon.CNOIDUNG



  ,listDon.DNGAYNHAN



  ,KNTC_LOAIDON.CTEN AS CLOAIDON,



    LINHVUC.CTEN AS CLINHVUC,



    KNTC_NOIDUNGDON.CTEN AS CNOIDUNGDON,



    KNTC_NGUONDON.CTEN AS CNGUONDON,



    KNTC_TINHCHAT.CTEN AS CTINHCHAT,



    TINH.CTEN AS CTINHTHANH,



    ITINHTRANGXULY AS TINHTRANG



    ,listDon.CNGUOIGUI_DIACHI



    ,HUYEN.CTEN AS CTENHUYEN



    ,listDon.CNGUOIGUI_TEN



    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN



    ,listDon.IDONVITIEPNHAN



    ,listDon.IDONVITHULY



    --,KNTC_DON.ISOLUONGTRUNG



    ,listSoluongtrung.ISOLUONGTRUNG



    ,listCoutDon.SODONTRUNG



    ,listDon.CGHICHU
  FROM ( SELECT KNTC_DON.* 
         FROM (SELECT * 
                FROM (SELECT idontrung as IDON 
                        FROM KNTC_DON
                        where  idontrung is not null and idontrung > 0 and   IDONVITHULY = P_IDONVI
                            AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN > P_DTUNGAY -1 )
                            AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN < P_DDENNGAY +1)
                    UNION
                    select idontrung as IDON 
                    FROM KNTC_DON_LICHSU inner join  KNTC_DON on KNTC_DON_LICHSU.IDON = KNTC_DON.idon
                    WHERE   idontrung is not null and idontrung > 0 and   IDONVIGUI = P_IDONVI
                        AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN > P_DTUNGAY -1 )
                        AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN < P_DDENNGAY +1)
                    GROUP BY idontrung
                    /* Khong can cong them tap tat ca don trung goc vi nhu vay cac don vi khong co tham quyen van xem duoc du lieu
                    union
                    select idon from kntc_don where  idontrung  =-1
                    AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )
                    AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)
                    */

                    )A GROUP BY IDON
                )B INNER JOIN KNTC_DON ON B.IDON = KNTC_DON.IDON
          where 1=1 and  KNTC_DON.idontrung =-1
      ) listDon
    left JOIN ( select sum( nvl(ISOLUONGTRUNG,1)) as sodontrung, idontrung  
                  from KNTC_DON
                  where  idontrung is not null and idontrung > 0
                      AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )
                      AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)
                  group by idontrung

                )  listCoutDon ON  listDon.IDON = listCoutDon.idontrung
    left JOIN ( select sum( nvl(ISOLUONGTRUNG,1)) as ISOLUONGTRUNG, idontrung  
                  from KNTC_DON
                  where  idontrung is not null and idontrung > 0
                  group by idontrung
                ) listSoluongtrung on  listDon.IDON = listSoluongtrung.idontrung
    LEFT JOIN QUOCHOI_COQUAN ON listDon.IDONVITHULY = QUOCHOI_COQUAN.ICOQUAN
    LEFT JOIN KNTC_LOAIDON ON listDon.ILOAIDON = KNTC_LOAIDON.ILOAIDON
    LEFT JOIN LINHVUC ON listDon.ILINHVUC = LINHVUC.ILINHVUC
    LEFT JOIN KNTC_NOIDUNGDON ON listDon.INOIDUNG = KNTC_NOIDUNGDON.INOIDUNG
    LEFT JOIN KNTC_NGUONDON ON listDon.INGUONDON = KNTC_NGUONDON.INGUONDON
    LEFT JOIN KNTC_TINHCHAT ON listDon.ITINHCHAT = KNTC_TINHCHAT.ITINHCHAT            
    LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = listDon.IDIAPHUONG_0
    LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =listDon.IDIAPHUONG_1
    LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON listDon.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN
  WHERE (P_IDONVITHULY = 0 OR listDon.IDONVITHULY = P_IDONVITHULY)
      AND (P_ITINHTRANGDON = -1 OR listDon.ITINHTRANGXULY = P_ITINHTRANGDON)
      AND (P_ITINHCHAT = 0 OR listDon.ITINHCHAT = P_ITINHCHAT)
      AND (P_INGUOINHAN = 0 OR listDon.IUSER = P_INGUOINHAN)
      AND (P_INGUONDON = 0 OR listDon.INGUONDON = P_INGUONDON)
      AND (P_INOIDUNG = 0 OR listDon.INOIDUNG = P_INOIDUNG)
      AND (P_ILINHVUC = 0 OR listDon.ILINHVUC = P_ILINHVUC)
      AND (P_ILOAIDON = 0 OR listDon.ILOAIDON = P_ILOAIDON)
      AND (P_IDANTOC = 0 OR listDon.INGUOIGUI_DANTOC =P_IDANTOC)
      AND (P_IQUOCTICH = 0 OR listDon.INGUOIGUI_QUOCTICH = P_IQUOCTICH)
      AND (P_ITINHTHANH = 0 OR listDon.IDIAPHUONG_0 = P_ITINHTHANH)
      AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)
      --AND (P_DTUNGAY ='' OR listDon.DNGAYNHAN >= P_DTUNGAY )
      --AND (P_DDENNGAY ='' OR listDon.DNGAYNHAN <= P_DDENNGAY)

      AND (P_CKEY='' OR (UPPER(listDon.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(listDon.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(listDon.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))



  ORDER BY listDon.IDON DESC;



  END PRO_LISTDONTRUNG;

  PROCEDURE PRO_LISTDONTAMXOA(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IDOANDONGNGUOI IN INT

                                        , P_DTUNGAY IN DATE , P_DDENNGAY IN DATE

                                        , P_INGUONDON IN INT ,P_ITINHTHANH in INT

                                        , P_IQUOCTICH IN INT, P_IDANTOC IN INT

                                        , P_ILOAIDON IN INT,P_ILINHVUC IN INT

                                        , P_INOIDUNG IN INT, P_ITINHCHAT IN INT,P_INGUOINHAN IN INT

                                        , P_ITINHTRANGDON IN INT, P_IDONVITHULY IN INT,P_IDONVI IN INT

                                        , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

  BEGIN

  OPEN res FOR

   WITH LIST_DONTAMXOA AS(

  SELECT KNTC_DON.IDON

  ,QUOCHOI_COQUAN.CTEN

  ,KNTC_DON.CNOIDUNG

  ,KNTC_DON.DNGAYNHAN

  ,KNTC_LOAIDON.CTEN AS CLOAIDON,

    LINHVUC.CTEN AS CLINHVUC,

    KNTC_NOIDUNGDON.CTEN AS CNOIDUNGDON,

    KNTC_NGUONDON.CTEN AS CNGUONDON,

    KNTC_TINHCHAT.CTEN AS CTINHCHAT,

    TINH.CTEN AS CTINHTHANH,

    ITINHTRANGXULY AS TINHTRANG 

    ,KNTC_DON.CNGUOIGUI_DIACHI

    ,HUYEN.CTEN AS CTENHUYEN

    ,KNTC_DON.CNGUOIGUI_TEN

    ,DVTIEPNHAN.CTEN AS DONVITIEPNHAN

    ,KNTC_DON.IDONVITIEPNHAN

    ,KNTC_DON.IDONVITHULY

    ,KNTC_DON.ISOLUONGTRUNG

    ,KNTC_DON.CGHICHU

  FROM (SELECT KNTC_DON.* FROM (

                SELECT * FROM (

                SELECT IDON FROM KNTC_DON

                where IDONVITHULY = P_IDONVI

                UNION

                select IDON FROM KNTC_DON_LICHSU

                WHERE IDONVIGUI = P_IDONVI GROUP BY IDON)A GROUP BY IDON)B INNER JOIN KNTC_DON ON B.IDON = KNTC_DON.IDON) KNTC_DON LEFT JOIN QUOCHOI_COQUAN ON KNTC_DON.IDONVITHULY = QUOCHOI_COQUAN.ICOQUAN

                LEFT JOIN KNTC_LOAIDON ON KNTC_DON.ILOAIDON = KNTC_LOAIDON.ILOAIDON

                LEFT JOIN LINHVUC ON KNTC_DON.ILINHVUC = LINHVUC.ILINHVUC

                LEFT JOIN KNTC_NOIDUNGDON ON KNTC_DON.INOIDUNG = KNTC_NOIDUNGDON.INOIDUNG

                LEFT JOIN KNTC_NGUONDON ON KNTC_DON.INGUONDON = KNTC_NGUONDON.INGUONDON

                LEFT JOIN KNTC_TINHCHAT ON KNTC_DON.ITINHCHAT = KNTC_TINHCHAT.ITINHCHAT             

                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0

                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1

                LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON KNTC_DON.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN

    WHERE  KNTC_DON.IDELETE = 1  
    AND ( KNTC_DON.IUSER = P_USER    OR P_USER = 0)

    AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)

    AND (P_IDONVITHULY = 0 OR KNTC_DON.IDONVITHULY = P_IDONVITHULY)

    AND (P_ITINHTRANGDON = -1 OR KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGDON)

    AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)

    AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)

    AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)

    AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)

    AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)

    AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)

    AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)

    AND (P_ITINHTHANH = 0 OR KNTC_DON.IDIAPHUONG_0 = P_ITINHTHANH)

    AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)

		AND (KNTC_DON.IKHOA = P_IKHOA or P_IKHOA = 0)

    AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )

    AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)

    AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

    ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONTAMXOA) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONTAMXOA ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1);

  END PRO_LISTDONTAMXOA;
PROCEDURE PRO_DONLUUKHONGXULY(res out sys_refcursor, P_USER in INT, P_CKEY in NVARCHAR2, P_IKHOA IN INT, P_IUSER_GIAOXULY IN INT , P_PAGE IN INT , P_PAGE_SIZE IN INT) AS

    BEGIN

    OPEN res FOR

WITH LIST_DONKHONGXULY AS(

          SELECT KNTC_DON.IDON,KNTC_DON.CNOIDUNG,
                KNTC_DON.CNGUOIGUI_DIACHI, 
                TINH.CTEN AS CTENTINH, 
                HUYEN.CTEN AS CTENHUYEN,
                KNTC_DON.DNGAYNHAN,
                KNTC_DON.CNGUOIGUI_TEN
								 FROM KNTC_DON 
                LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0 
                LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG = KNTC_DON.IDIAPHUONG_1
                WHERE  1=1 
                AND  ((P_USER = 0 OR  KNTC_DON.IUSER =  P_USER) OR   (P_IUSER_GIAOXULY = 0 or P_IUSER_GIAOXULY = KNTC_DON.IUSER_GIAOXULY))

                AND KNTC_DON.IDELETE <> 1 
								AND ITINHTRANGXULY = 5
                AND (P_IKHOA = 0 or P_IKHOA = KNTC_DON.IKHOA)
				--AND (P_IUSER_GIAOXULY = 0 or P_IUSER_GIAOXULY = KNTC_DON.IUSER_GIAOXULY)
                AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))

          ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM

        (

            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONKHONGXULY) AS TOTAL,

            ROWNUM STT FROM( select * from LIST_DONKHONGXULY ) k

            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )

        )

    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1)

    ORDER BY STT; 
		END PRO_DONLUUKHONGXULY; 
END PKG_KHIEUNAI_TOCAO;

