create or replace PROCEDURE "PRC_TONGHOP_KIENNGHI_BDN" (res out sys_refcursor,  p_ITINHTRANG in NUMBER, /* DEFAULT: -1*/
                                                               p_MAKIENNGHI IN NVARCHAR2, /* DEFAULT: ''*/  
                                                               p_LISTLINHVUC IN NVARCHAR2, /* DEFAULT: -1*/
                                                               p_IDONVITONGHOP in NUMBER, /* DEFAULT: 0*/
                                                               p_ITRUOCKYHOP IN NUMBER, /* DEFAULT: -1*/
                                                               p_DTUNGAY IN DATE, /* DEFAULT: date min*/
                                                               p_DDENNGAY IN DATE, /* DEFAULT: date max*/
                                                               p_LISTNGUONKN in NVARCHAR2,
                                                               p_IDONVITIEPNHAN in NUMBER,
                                                               p_ITHAMQUYENDONVI_PARENT in NUMBER,/*DEFAULT:0*/
                                                               p_ITHAMQUYENDONVI in NUMBER,/* DEFAULT: -1*/
                                                               p_CNOIDUNG IN NVARCHAR2, /* DEFAULT: */
                                                               p_LISTKYHOP IN NVARCHAR2,
                                                               p_LIST_HUYEN_XA_TP IN NVARCHAR2,
                                                               p_PAGE IN NUMBER,/* DEFAULT: */
                                                               p_PAGE_SIZE IN NUMBER,
                                                               p_IUSER IN NUMBER
                                                               ) AS
BEGIN
Open res for
  WITH 
  TONGKIENNGHI AS (SELECT COUNT(*) AS SOKIENNGHI_TONGHOP, KN_TONGHOP.ITONGHOP AS ID_TONGHOP FROM KN_TONGHOP 
                  LEFT JOIN KN_KIENNGHI ON KN_KIENNGHI.ITONGHOP=KN_TONGHOP.ITONGHOP
                  WHERE KN_KIENNGHI.ID_GOP<=0  AND (p_IUSER = 0 OR KN_KIENNGHI.IUSER = p_IUSER)
                  GROUP BY KN_TONGHOP.ITONGHOP),
  TBL1 AS(
        SELECT  KN_TONGHOP.ITONGHOP, KN_TONGHOP.IUSER AS IUSER_CAPNHAT,
                KN_TONGHOP.DDATE AS NGAY_TONGHOP,KN_VANBAN.DNGAYBANHANH AS NGAY_CHUYENTONGHOP,                
                COQUAN_TONGHOP.CTEN AS TEN_DONVITONGHOP,KN_TONGHOP.IDONVITONGHOP AS ID_DONVITONGHOP,
                KN_TONGHOP.ITHAMQUYENDONVI AS ID_THAMQUYEN_DONVI_TONGHOP,
                COQUAN_THAMQUYEN.CTEN AS TEN_THAMQUYEN_DONVI_TONGHOP,
                LINHVUC_COQUAN.CTEN AS TEN_LINHVUC_TONGHOP,
                KN_TONGHOP.ILINHVUC AS ID_LINHVUC_TONGHOP,
                COQUAN_THAMQUYEN.IPARENT AS ID_PARENT_THAMQUYEN_DONVI,
                KN_TONGHOP.CNOIDUNG AS NOIDUNG_TONGHOP, TONGKIENNGHI.SOKIENNGHI_TONGHOP AS SOKIENNGHI_TONGHOP
        FROM KN_TONGHOP 
        LEFT JOIN KN_VANBAN ON KN_VANBAN.ITONGHOP=KN_TONGHOP.ITONGHOP AND KN_VANBAN.CLOAI='tonghop_chuyenxuly'
        LEFT JOIN QUOCHOI_COQUAN COQUAN_TONGHOP ON COQUAN_TONGHOP.ICOQUAN=KN_TONGHOP.IDONVITONGHOP
        LEFT JOIN QUOCHOI_COQUAN COQUAN_THAMQUYEN ON COQUAN_THAMQUYEN.ICOQUAN=KN_TONGHOP.ITHAMQUYENDONVI
        LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_TONGHOP.ILINHVUC
        LEFT JOIN TONGKIENNGHI ON TONGKIENNGHI.ID_TONGHOP=KN_TONGHOP.ITONGHOP
--        INNER JOIN KN_KIENNGHI ON KN_KIENNGHI.ITONGHOP=KN_TONGHOP.ITONGHOP OR KN_KIENNGHI.ITONGHOP_BDN=KN_TONGHOP.ITONGHOP
        WHERE 
              --KN_TONGHOP.IKYHOP=1 AND KN_TONGHOP.ITINHTRANG=2
            --(p_IKYHOP=0 OR KN_TONGHOP.IKYHOP=p_IKYHOP) AND 
            (p_ITHAMQUYENDONVI_PARENT=0 OR p_ITHAMQUYENDONVI_PARENT IS NULL OR COQUAN_THAMQUYEN.IPARENT=p_ITHAMQUYENDONVI_PARENT) AND 
            (p_ITINHTRANG=-1 OR p_ITINHTRANG IS NULL OR KN_TONGHOP.ITINHTRANG=p_ITINHTRANG) AND 
--            (KN_TONGHOP.ILINHVUC IN (select regexp_substr(p_LISTLINHVUC,'[^,]+', 1, level)
--					from dual
--					connect BY regexp_substr(p_LISTLINHVUC, '[^,]+', 1, level)
--					is not null) OR p_LISTLINHVUC = '' OR p_LISTLINHVUC is null) AND
            (p_IDONVITONGHOP=0 OR p_IDONVITONGHOP IS NULL OR p_IDONVITONGHOP is null OR KN_TONGHOP.IDONVITONGHOP=p_IDONVITONGHOP) AND 
            (p_ITRUOCKYHOP=-1 OR p_ITRUOCKYHOP IS NULL OR KN_TONGHOP.ITRUOCKYHOP=p_ITRUOCKYHOP) AND 
            (p_ITHAMQUYENDONVI=0 OR p_ITHAMQUYENDONVI IS NULL OR KN_TONGHOP.ITHAMQUYENDONVI=p_ITHAMQUYENDONVI) AND 
            KN_TONGHOP.ITHAMQUYENDONVI!=0 
--            KN_TONGHOP.IDELETE = 0
              ),
    KN_GOP AS (SELECT DISTINCT KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP, QUOCHOI_COQUAN.CTEN AS TENCOQUAN FROM 
                KN_KIENNGHI LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN =KN_KIENNGHI.IDONVITIEPNHAN
                WHERE KN_KIENNGHI.ID_GOP>0 
--                AND (p_IKYHOP=0 OR KN_KIENNGHI.IKYHOP=p_IKYHOP) 
                AND (p_IUSER = 0 OR KN_KIENNGHI.IUSER = p_IUSER) ORDER BY KN_KIENNGHI.ID_GOP),
    TBL2 as( select  KN_GOP.ID_KIENNGHI_PARENT_GOP AS ID_KIENNGHI_PARENT_GOP,
            LISTAGG( convert(KN_GOP.TENCOQUAN, 'UTF8', 'AL32UTF8'), ', ') WITHIN GROUP 
            (ORDER BY KN_GOP.ID_KIENNGHI_PARENT_GOP) TENDONVITIEPNHAN_GOP FROM KN_GOP GROUP BY KN_GOP.ID_KIENNGHI_PARENT_GOP),
     KIENNGHI AS(
      SELECT COALESCE(KN_KIENNGHI.IKIENNGHI,0) AS IKIENNGHI,KN_KIENNGHI.ID_GOP,KN_KIENNGHI.ITONGHOP AS KIENNGHI_ID_TONGHOP,KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI, KN_KIENNGHI.ITINHTRANG AS ITINHTRANG, KN_KIENNGHI.IKYHOP as IKYHOP,
      KN_KIENNGHI.IDIAPHUONG0 as IDIAPHUONG0,COALESCE(KN_KIENNGHI.ILINHVUC,0) AS ID_LINHVUC_KIENNGHI,
      LINHVUC_COQUAN.CTEN AS TEN_LINHVUC_KIENNGHI,QUOCHOI_COQUAN.CTEN AS TEN_DONVITIEPNHAN_KIENNGHI,
      TBL2.TENDONVITIEPNHAN_GOP, KN_KIENNGHI.CMAKIENNGHI, KN_KIENNGHI.ITHAMQUYENDONVI, KN_KIENNGHI.ITRUOCKYHOP, KN_KIENNGHI.IDONVITIEPNHAN, KN_KIENNGHI.DDATE, KN_KIENNGHI.CNOIDUNG
      FROM KN_KIENNGHI LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC
      LEFT JOIN QUOCHOI_COQUAN ON KN_KIENNGHI.IDONVITIEPNHAN=QUOCHOI_COQUAN.ICOQUAN  
      LEFT JOIN TBL2 ON TBL2.ID_KIENNGHI_PARENT_GOP=KN_KIENNGHI.IKIENNGHI
      LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC
      INNER JOIN KIENNGHI_NGUONDON on KN_KIENNGHI.IKIENNGHI = KIENNGHI_NGUONDON.IKIENNGHI
      INNER JOIN KN_NGUONDON on KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
      WHERE (p_IUSER = 0 OR p_IUSER is null OR KN_KIENNGHI.IUSER = p_IUSER) 
        AND (p_MAKIENNGHI IS NULL OR (UPPER(KN_KIENNGHI.CMAKIENNGHI) LIKE '%' || UPPER(TRIM(p_MAKIENNGHI)) || '%' )) AND
        (p_LISTNGUONKN = '' OR p_LISTNGUONKN IS NULL  OR  KN_NGUONDON.INGUONDON IN ( Select Regexp_Substr(p_LISTNGUONKN,'[^,]+',1,Level) INGUONDON From Dual Connect By Regexp_Substr(p_LISTNGUONKN,'[^,]+',1,Level) Is Not Null)) AND
        (p_ITHAMQUYENDONVI=0 OR p_ITHAMQUYENDONVI IS NULL OR  KN_KIENNGHI.ITHAMQUYENDONVI=p_ITHAMQUYENDONVI)
        --      AND KN_KIENNGHI.ID_GOP<=0 
        AND (p_LISTLINHVUC IS NULL OR LINHVUC_COQUAN.ILINHVUC IN (select regexp_substr(p_LISTLINHVUC,'[^,]+', 1, level) from dual connect BY regexp_substr(p_LISTLINHVUC, '[^,]+', 1, level) is not null)
        OR LINHVUC_COQUAN.IPARENT IN (select regexp_substr(p_LISTLINHVUC,'[^,]+', 1, level) from dual connect BY regexp_substr(p_LISTLINHVUC, '[^,]+', 1, level) is not null)) 
        AND (p_DTUNGAY is null OR KN_KIENNGHI.DDATE >= p_DTUNGAY)
        AND (p_DDENNGAY is null OR KN_KIENNGHI.DDATE <= p_DDENNGAY)
        AND (p_IDONVITIEPNHAN=0 OR p_IDONVITIEPNHAN is null OR KN_KIENNGHI.IDONVITIEPNHAN=p_IDONVITIEPNHAN)
        AND (p_ITRUOCKYHOP=-1 OR p_ITRUOCKYHOP is null OR KN_KIENNGHI.ITRUOCKYHOP=p_ITRUOCKYHOP) 
        AND (p_ITHAMQUYENDONVI=0 OR p_ITHAMQUYENDONVI is null OR KN_KIENNGHI.ITHAMQUYENDONVI=p_ITHAMQUYENDONVI) 
        AND (KN_KIENNGHI.IKYHOP IN (select regexp_substr(p_LISTKYHOP,'[^,]+', 1, level)
            from dual
            connect BY regexp_substr(p_LISTKYHOP, '[^,]+', 1, level)
            is not null) OR p_LISTKYHOP = '0') 
        AND KN_KIENNGHI.IDELETE = 0
        AND KN_KIENNGHI.ITONGHOP != 0
    ),
    TBL4 AS (SELECT  TBL1.*,KIENNGHI.*,TRACKING.CACTION AS THAMQUYEN_CHUYEN
    FROM TBL1 LEFT JOIN KIENNGHI ON TBL1.ITONGHOP=KIENNGHI.KIENNGHI_ID_TONGHOP
    LEFT JOIN TRACKING ON TRACKING.IKIENNGHI=KIENNGHI.IKIENNGHI AND TRACKING.ITONGHOP=TBL1.ITONGHOP
		LEFT JOIN QUOCHOI_COQUAN ON TBL1.ID_THAMQUYEN_DONVI_TONGHOP = QUOCHOI_COQUAN.ICOQUAN
		WHERE KIENNGHI.ITINHTRANG = 1 AND QUOCHOI_COQUAN.CTYPE = 'TW'
            AND (p_CNOIDUNG = '' OR (UPPER(KIENNGHI.CNOIDUNG) LIKE '%' || UPPER(TRIM(p_CNOIDUNG)) || '%') OR (UPPER(TBL1.NOIDUNG_TONGHOP) LIKE '%' || UPPER(TRIM(p_CNOIDUNG)) || '%'))
    ORDER BY TBL1.ID_THAMQUYEN_DONVI_TONGHOP,TBL1.ITONGHOP,KIENNGHI.ID_LINHVUC_KIENNGHI)
--select * from kn_kiennghi;

SELECT * FROM
    ( SELECT k.*,(SELECT COUNT(*) FROM TBL4) AS TOTAL, ROWNUM r_ FROM( select * from TBL4 ) k WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
    )
WHERE r_>=    (((p_PAGE-1) * p_PAGE_SIZE) + 1);
--LEFT JOIN TBL4 ON TBL1.ID_PARENT_THAMQUYEN_DONVI=TBL4.ICOQUAN_PARENT_THAMQUYEN_DONVI
--WHERE (p_ITHAMQUYENDONVI_PARENT=0 OR TBL1.ID_PARENT_THAMQUYEN_DONVI=p_ITHAMQUYENDONVI_PARENT);

END PRC_TONGHOP_KIENNGHI_BDN;