create or replace procedure prc_list_kiennghi_by_tonghop(
    res out sys_refcursor,
    p_ITONGHOP in number,
    p_ITONGHOP_BDN in number
) as 
begin
    Open res for
    with
    KN_ND as (
        SELECT KIENNGHI_NGUONDON.IKIENNGHI AS IKIENNGHI,
        LISTAGG(KN_NGUONDON.CTEN, ',') WITHIN GROUP (ORDER BY KIENNGHI_NGUONDON.IKIENNGHI ) AS DIAPHUONG
        FROM KIENNGHI_NGUONDON
        INNER JOIN KN_NGUONDON ON KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
        GROUP BY KIENNGHI_NGUONDON.IKIENNGHI 
    ),
    TBL1 as (
        select KN_KIENNGHI.CNOIDUNG, KN_KIENNGHI.IKIENNGHI, KN_KIENNGHI.ID_GOP,
            KN_KIENNGHI.CDIACHI, KN_ND.DIAPHUONG AS CNGUONDON,
            KN_KIENNGHI.ITINHTRANG, QUOCHOI_COQUAN.CTEN AS TENDONVITIEPNHAN,
            DIAPHUONG0.CTEN AS TEN_TINH, DIAPHUONG1.CTEN AS TEN_HUYEN
        FROM KN_KIENNGHI 
            INNER JOIN KN_ND on KN_ND.IKIENNGHI = KN_KIENNGHI.IKIENNGHI
            LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN
            LEFT JOIN DIAPHUONG DIAPHUONG0 ON DIAPHUONG0.IDIAPHUONG=KN_KIENNGHI.IDIAPHUONG0 
            LEFT JOIN DIAPHUONG DIAPHUONG1 ON DIAPHUONG1.IDIAPHUONG=KN_KIENNGHI.IDIAPHUONG1 
        WHERE 
        (p_ITONGHOP=0 OR KN_KIENNGHI.ITONGHOP=p_ITONGHOP) AND 
        (p_ITONGHOP_BDN=0 OR KN_KIENNGHI.ITONGHOP_BDN=p_ITONGHOP_BDN) and ID_GOP<=0
    ),
    --union all
    KN_GOP AS (
        SELECT DISTINCT KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP, QUOCHOI_COQUAN.CTEN AS TENCOQUAN
        FROM KN_KIENNGHI
        LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN = KN_KIENNGHI.IDONVITIEPNHAN
        WHERE KN_KIENNGHI.ID_GOP > 0 
        ORDER BY KN_KIENNGHI.ID_GOP
    ),
    TBL2 as (
        select  KN_GOP.ID_KIENNGHI_PARENT_GOP AS ID_KIENNGHI_PARENT_GOP,
            LISTAGG( convert(KN_GOP.TENCOQUAN, 'UTF8', 'AL32UTF8'), ',') WITHIN GROUP 
            (ORDER BY KN_GOP.ID_KIENNGHI_PARENT_GOP) TENDONVITIEPNHAN_GOP
        FROM KN_GOP
        GROUP BY KN_GOP.ID_KIENNGHI_PARENT_GOP             
    )
    select * from TBL1
    LEFT JOIN TBL2 on TBL1.IKIENNGHI = TBL2.ID_KIENNGHI_PARENT_GOP
    ORDER BY TBL1.ID_GOP;
end prc_list_kiennghi_by_tonghop;