CREATE OR REPLACE PROCEDURE PRC_KNTC_LISTDONDAXULYGIAIQUYET(
    res out sys_refcursor, 
    P_USER in INT, 
    P_CKEY in NVARCHAR2, 
    P_IKHOA IN INT, 
    P_IDOANDONGNGUOI IN INT, 
    P_DTUNGAY IN DATE , 
    P_DDENNGAY IN DATE, 
    P_INGUONDON IN INT ,
    P_IQUANHUYEN in INT, 
    P_IXAPHUONG in INT, 
    P_IQUOCTICH IN INT, 
    P_IDANTOC IN INT, 
    P_ILOAIDON IN INT,
    P_ILINHVUC IN INT, 
    P_INOIDUNG IN INT, 
    P_ITINHCHAT IN INT,
    P_INGUOINHAN IN INT, 
    P_IDONVITHULY IN INT, 
    P_ITINHTRANGXULY IN INT, 
    P_PAGE IN INT , 
    P_PAGE_SIZE IN INT)
    AS BEGIN
    OPEN res FOR
    WITH LIST_DONDAXULY AS(
          SELECT A.IDON,A.CNOIDUNG,A.CNGUOIGUI_DIACHI,TINH.CTEN AS CTENTINH,HUYEN.CTEN AS CTENHUYEN,A.DNGAYNHAN,A.CNGUOIGUI_TEN
          FROM (
            SELECT * 
            FROM KNTC_DON WHERE KNTC_DON.IDONVITHULY = P_IDONVITHULY  AND KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY
            UNION
            SELECT KNTC_DON.* FROM KNTC_DON_LICHSU INNER JOIN KNTC_DON ON KNTC_DON_LICHSU.IDON = KNTC_DON.IDON WHERE  KNTC_DON_LICHSU.IDONVIXULY = P_IDONVITHULY AND KNTC_DON_LICHSU.ITRANGTHAI = P_ITINHTRANGXULY) A
                  LEFT JOIN QUOCHOI_COQUAN DVTHULY ON DVTHULY.ICOQUAN = A.IDONVITHULY
                  LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = A.IDIAPHUONG_0
                  LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =A.IDIAPHUONG_1
                  LEFT JOIN QUOCHOI_COQUAN DVTIEPNHAN ON A.IDONVITIEPNHAN = DVTIEPNHAN.ICOQUAN
            WHERE 1=1 
            AND ( ( P_USER =0 or   A.IUSER = P_USER) OR ( A.IUSER_GIAOXULY = P_USER or A.IUSER_DUOCGIAOXULY = P_USER ))
            AND (P_ITINHCHAT = 0 OR A.ITINHCHAT = P_ITINHCHAT)
            AND (P_INGUOINHAN = 0 OR A.IUSER = P_INGUOINHAN)
            AND (P_INGUONDON = 0 OR A.INGUONDON = P_INGUONDON)
            AND (P_INOIDUNG = 0 OR A.INOIDUNG = P_INOIDUNG)
            AND (P_ILINHVUC = 0 OR A.ILINHVUC = P_ILINHVUC)
            AND (P_ILOAIDON = 0 OR A.ILOAIDON = P_ILOAIDON)
            AND (P_IDANTOC = 0 OR A.INGUOIGUI_DANTOC =P_IDANTOC)
            AND (P_IQUOCTICH = 0 OR A.INGUOIGUI_QUOCTICH = P_IQUOCTICH)
            AND (P_IQUANHUYEN = 0 OR A.IDIAPHUONG_1 = P_IQUANHUYEN)
            AND (P_IXAPHUONG = 0 OR A.IDIAPHUONG_2 = P_IXAPHUONG)
            AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)
            AND (A.IKHOA = P_IKHOA or P_IKHOA = 0) 
            AND (P_DTUNGAY ='' OR A.DNGAYNHAN >= P_DTUNGAY )
            AND (P_DDENNGAY ='' OR A.DNGAYNHAN <= P_DDENNGAY)
            AND (P_CKEY='' OR (UPPER(A.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(A.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(A.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))
            ORDER BY A.IDON DESC
    )
    SELECT * FROM
        (
            SELECT k.*,(SELECT COUNT(*) FROM LIST_DONDAXULY) AS TOTAL,
            ROWNUM STT FROM( select * from LIST_DONDAXULY ) k
            WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )
        )
    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;
END PRC_KNTC_LISTDONDAXULYGIAIQUYET;