create or replace PROCEDURE PRC_KIENNGHI_IMPORT_LISTKN 
(
    p_ID_IMPORT IN NUMBER,
    res OUT sys_refcursor
)
IS
BEGIN
Open res for
    SELECT KN_KIENNGHI.*, donvi_tiepnhan.cten AS TENDONVI_TIEPNHAN, DONVI_THAMQUYEN.cten AS TENDONVI_TIEPNHAN, LINHVUC_COQUAN.cten AS TEN_LINHVUC
    FROM KN_KIENNGHI
    LEFT JOIN QUOCHOI_COQUAN DONVI_TIEPNHAN ON DONVI_TIEPNHAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN
    LEFT JOIN QUOCHOI_COQUAN DONVI_THAMQUYEN ON DONVI_THAMQUYEN.ICOQUAN=KN_KIENNGHI.ITHAMQUYENDONVI
    LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC
    WHERE (p_ID_IMPORT = 0 OR KN_KIENNGHI.ID_IMPORT = p_ID_IMPORT)
    AND KN_KIENNGHI.IDELETE = 0
    ORDER BY KN_KIENNGHI.ddate
  ;
END PRC_KIENNGHI_IMPORT_LISTKN;