create or replace PROCEDURE PRC_KNTC_DONDAPHANLOAI 
(
    res out sys_refcursor, 
    P_USER in INT, 
    P_CKEY in NVARCHAR2, 
    P_IKHOA IN INT, 
    P_IDOANDONGNGUOI IN INT, 
    P_DTUNGAY IN DATE , 
    P_DDENNGAY IN DATE, 
    P_INGUONDON IN INT ,
    P_IQUANHUYEN in INT, 
    P_IXAPHUONG in INT, 
    P_IQUOCTICH IN INT, 
    P_IDANTOC IN INT, 
    P_ILOAIDON IN INT,
    P_ILINHVUC IN INT, 
    P_INOIDUNG IN INT, 
    P_ITINHCHAT IN INT,
    P_INGUOINHAN IN INT, 
    P_IDONVITIEPNHAN IN INT, 
    P_ITINHTRANGXULY IN INT,
    P_IUSER_DUOCGIAOXULY IN INT, 
    P_ITHAMQUYEN IN INT,
    P_IDIEUKIEN IN INT, 
    P_PAGE IN INT , 
    P_PAGE_SIZE IN INT
)
AS
BEGIN
OPEN res FOR
WITH LIST_DONDAPHANLOAI AS(
    SELECT KNTC_DON.IDON
    ,KNTC_DON.CNOIDUNG
    ,KNTC_DON.CNGUOIGUI_DIACHI
    ,TINH.CTEN AS CTENTINH
    ,HUYEN.CTEN AS CTENHUYEN
    ,KNTC_DON.DNGAYNHAN
    ,KNTC_DON.CNGUOIGUI_TEN
    FROM KNTC_DON
    LEFT JOIN DIAPHUONG TINH ON TINH.IDIAPHUONG = KNTC_DON.IDIAPHUONG_0
    LEFT JOIN DIAPHUONG HUYEN ON HUYEN.IDIAPHUONG =KNTC_DON.IDIAPHUONG_1
    WHERE 1=1 
        AND ( ( P_USER =0 or   KNTC_DON.IUSER = P_USER) OR (P_IUSER_DUOCGIAOXULY = 0 OR KNTC_DON.IUSER_DUOCGIAOXULY = P_IUSER_DUOCGIAOXULY))
        AND (P_ITINHCHAT = 0 OR KNTC_DON.ITINHCHAT = P_ITINHCHAT)
        AND (P_INGUOINHAN = 0 OR KNTC_DON.IUSER = P_INGUOINHAN)
        AND (P_INGUONDON = 0 OR KNTC_DON.INGUONDON = P_INGUONDON)
        AND (P_INOIDUNG = 0 OR KNTC_DON.INOIDUNG = P_INOIDUNG)
        AND (P_ILINHVUC = 0 OR KNTC_DON.ILINHVUC = P_ILINHVUC)
        AND (P_ILOAIDON = 0 OR KNTC_DON.ILOAIDON = P_ILOAIDON)
        AND (P_IDANTOC = 0 OR KNTC_DON.INGUOIGUI_DANTOC =P_IDANTOC)
        AND (P_IQUOCTICH = 0 OR KNTC_DON.INGUOIGUI_QUOCTICH = P_IQUOCTICH)
        AND (P_IQUANHUYEN = 0 OR KNTC_DON.IDIAPHUONG_1 = P_IQUANHUYEN)
        AND (P_IXAPHUONG = 0 OR KNTC_DON.IDIAPHUONG_2 = P_IXAPHUONG)
        AND (P_IDOANDONGNGUOI = 0 OR IDOANDONGNGUOI = P_IDOANDONGNGUOI)
        AND (P_IKHOA = 0 OR KNTC_DON.IKHOA = P_IKHOA ) 
        AND (P_DTUNGAY ='' OR KNTC_DON.DNGAYNHAN >= P_DTUNGAY )
        AND (P_DDENNGAY ='' OR KNTC_DON.DNGAYNHAN <= P_DDENNGAY)
        AND (KNTC_DON.ITINHTRANGXULY = P_ITINHTRANGXULY)
        AND (KNTC_DON.ITHAMQUYEN = P_ITHAMQUYEN)
        AND (KNTC_DON.IDUDIEUKIEN = P_IDIEUKIEN)
        AND (KNTC_DON.IDONVITIEPNHAN = P_IDONVITIEPNHAN)
        AND KNTC_DON.IDELETE = 0
        AND (P_CKEY='' OR (UPPER(KNTC_DON.CNOIDUNG) LIKE '%' || UPPER(P_CKEY) || '%' OR UPPER(KNTC_DON.CNGUOIGUI_TEN) LIKE '%' || UPPER(P_CKEY) || '%'  OR UPPER(KNTC_DON.CNGUOIGUI_DIACHI) LIKE '%' || UPPER(P_CKEY) || '%'))
        ORDER BY KNTC_DON.IDON DESC)

    SELECT * FROM
    (
        SELECT k.*,(SELECT COUNT(*) FROM LIST_DONDAPHANLOAI) AS TOTAL,
        ROWNUM STT FROM( select * from LIST_DONDAPHANLOAI ) k
        WHERE ROWNUM < ((P_PAGE * P_PAGE_SIZE) + 1 )
    ) 
    WHERE STT >=    (((P_PAGE-1) * P_PAGE_SIZE) + 1) ORDER BY STT;
END PRC_KNTC_DONDAPHANLOAI;