create or replace PROCEDURE "PRC_KIENNGHI_LIST_TRACUU" (res out sys_refcursor,    
                                                               p_ITINHTRANG IN NUMBER, /* DEFAULT: -1*/
                                                               p_ILINHVUC IN NUMBER, /* DEFAULT: -1*/
                                                               p_IDONVITIEPNHAN in NUMBER, /* DEFAULT: 0*/
                                                               p_IKYHOP in NUMBER, /* DEFAULT: 0*/
                                                               p_ITRUOCKYHOP IN NUMBER, /* DEFAULT: -1*/
                                                               p_ITHAMQUYENDONVI_PARENT in NUMBER,/* DEFAULT: 0*/
                                                               p_ITHAMQUYENDONVI in NUMBER,/* DEFAULT: 0*/
                                                               p_CNOIDUNG IN NVARCHAR2, /* DEFAULT: */
                                                               p_IUSER_CAPNHAT IN NUMBER,--0
                                                               p_NGAYNHAN_FROM IN DATE,
                                                               p_NGAYNHAN_TO IN DATE,
                                                               p_NGAYTONGHOP_FROM IN DATE,
                                                               p_NGAYTONGHOP_TO IN DATE,
                                                               p_NGAYTRALOI_FROM IN DATE,
                                                               p_NGAYTRALOI_TO IN DATE,
                                                               p_TINHTRANG_FROM IN NUMBER,
                                                               p_TINHTRANG_TO IN NUMBER,
                                                               p_KETQUA_GIAMSAT IN NUMBER,
                                                               p_DA_TRALOI IN NUMBER,
                                                               p_CMAKIENNGHI IN NVARCHAR2,
                                                               p_INGUONKIENNGHI IN NVARCHAR2,
                                                               p_CNOIDUNGKIENNGHI IN NVARCHAR2,
                                                               p_PAGE IN NUMBER,
                                                               p_PAGE_SIZE IN NUMBER    
                                                               ) AS
  BEGIN
    Open res for
    WITH 
    TRALOI AS(SELECT COUNT(*) AS DATRALOI,KN_KIENNGHI_TRALOI.IKIENNGHI AS ID_KIENNGHI 
          FROM KN_KIENNGHI_TRALOI INNER JOIN KN_KIENNGHI ON KN_KIENNGHI.IKIENNGHI=KN_KIENNGHI_TRALOI.IKIENNGHI
          GROUP BY KN_KIENNGHI_TRALOI.IKIENNGHI),
    TBL1 AS
    (SELECT   KN_KIENNGHI.IDELETE AS IDELETE,KN_KIENNGHI.IUSER AS IUSER,
              KN_KIENNGHI.DDATE AS NGAYCAPNHAT,
              KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI, ID_GOP, KN_KIENNGHI.IUSER AS ID_USER_CAPNHAT,
              IKIENNGHI_TRUNG AS ID_KIENNGHI_TRUNG, KN_KIENNGHI.ITONGHOP AS ID_KIENNGHI_TONGHOP,
              KN_KIENNGHI.ITONGHOP_BDN AS ID_KIENNGHI_TONGHOP_BDN, KN_KIENNGHI.IDONVITIEPNHAN AS ID_DONVITIEPNHAN,
              DONVI_TIEPNHAN.CTEN AS TEN_DONVITIEPNHAN,
              KN_KIENNGHI.ITHAMQUYENDONVI AS ID_THAMQUYEN_DONVI,KN_KIENNGHI.ILINHVUC AS ID_LINHVUC,KN_KIENNGHI.ITINHTRANG,
              DONVI_THAMQUYEN.CTEN AS TEN_THAMQUYEN_DONVI,LINHVUC_COQUAN.CTEN AS TEN_LINHVUC, 
              KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI
              FROM KN_KIENNGHI 
      LEFT JOIN QUOCHOI_COQUAN DONVI_TIEPNHAN ON DONVI_TIEPNHAN.ICOQUAN=KN_KIENNGHI.IDONVITIEPNHAN
      LEFT JOIN QUOCHOI_COQUAN DONVI_THAMQUYEN ON DONVI_THAMQUYEN.ICOQUAN=KN_KIENNGHI.ITHAMQUYENDONVI
      LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC
--      LEFT JOIN KN_KIENNGHI_TRALOI ON KN_KIENNGHI_TRALOI.IKIENNGHI=KN_KIENNGHI.IKIENNGHI
        LEFT JOIN 
            (
                SELECT KN_KIENNGHI_TRALOI.IKIENNGHI AS IKIENNGHI_TRALOI , MAX(KN_KIENNGHI_TRALOI.DNGAYBANHANH) AS  VB_NGAYBANHANH
                FROM KN_KIENNGHI_TRALOI
                INNER JOIN KN_KIENNGHI ON KN_KIENNGHI_TRALOI.IKIENNGHI = KN_KIENNGHI.IKIENNGHI
                GROUP BY KN_KIENNGHI_TRALOI.IKIENNGHI
            ) KIENNGHI_TRALOI ON KIENNGHI_TRALOI.IKIENNGHI_TRALOI = KN_KIENNGHI.IKIENNGHI
        INNER JOIN
        (        
            SELECT KIENNGHI_NGUONDON.IKIENNGHI AS IKIENNGHI , LISTAGG(KN_NGUONDON.CTEN, ',') WITHIN GROUP (ORDER BY  KIENNGHI_NGUONDON.IKIENNGHI )AS  DIAPHUONG
            FROM KIENNGHI_NGUONDON
            INNER JOIN 
            (
                SELECT KIENNGHI_NGUONDON.IKIENNGHI AS IKIENNGHI , LISTAGG(KN_NGUONDON.CTEN, ',') WITHIN GROUP (ORDER BY  KIENNGHI_NGUONDON.IKIENNGHI )AS  DIAPHUONG
                FROM KIENNGHI_NGUONDON
                INNER JOIN KN_NGUONDON ON KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
                WHERE  (p_INGUONKIENNGHI = '' OR p_INGUONKIENNGHI IS NULL OR  KN_NGUONDON.INGUONDON IN (  Select Regexp_Substr(p_INGUONKIENNGHI,'[^,]+',1,Level) INGUONDON From Dual Connect By Regexp_Substr(p_INGUONKIENNGHI,'[^,]+',1,Level) Is Not Null))
                GROUP BY KIENNGHI_NGUONDON.IKIENNGHI
            ) KN_ND_SELECT ON KN_ND_SELECT.IKIENNGHI = KIENNGHI_NGUONDON.IKIENNGHI
            INNER JOIN KN_NGUONDON ON KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
            GROUP BY KIENNGHI_NGUONDON.IKIENNGHI       
        ) KN_ND ON KN_ND.IKIENNGHI = KN_KIENNGHI.IKIENNGHI
      WHERE 1=1 AND
        KN_KIENNGHI.IDELETE = 0 and
        (p_NGAYTRALOI_FROM IS NULL OR KIENNGHI_TRALOI.VB_NGAYBANHANH >= p_NGAYTRALOI_FROM) AND
        (p_NGAYTRALOI_TO IS NULL OR KIENNGHI_TRALOI.VB_NGAYBANHANH <= p_NGAYTRALOI_TO) AND
        UPPER(KN_KIENNGHI.CMAKIENNGHI) LIKE '%' || UPPER(TRIM(p_CMAKIENNGHI)) || '%' AND 
        UPPER(KN_KIENNGHI.CNOIDUNG) LIKE '%' || UPPER(TRIM(p_CNOIDUNGKIENNGHI)) || '%' AND 
        (p_ITINHTRANG=-1 OR KN_KIENNGHI.ITINHTRANG=p_ITINHTRANG) AND
        (p_IKYHOP=0 OR KN_KIENNGHI.IKYHOP=p_IKYHOP) AND 
        (p_ILINHVUC=-1 OR KN_KIENNGHI.ILINHVUC=p_ILINHVUC) AND 
        (p_IDONVITIEPNHAN=0 OR KN_KIENNGHI.IDONVITIEPNHAN=p_IDONVITIEPNHAN) AND 
        (p_ITRUOCKYHOP=-1 OR KN_KIENNGHI.ITRUOCKYHOP=p_ITRUOCKYHOP) 
        AND (KN_KIENNGHI.IUSER=p_IUSER_CAPNHAT OR p_IUSER_CAPNHAT=0)
        AND (p_ITHAMQUYENDONVI=0 OR KN_KIENNGHI.ITHAMQUYENDONVI=p_ITHAMQUYENDONVI)
--        AND (KN_KIENNGHI_TRALOI.DNGAYBANHANH IS NULL OR KN_KIENNGHI_TRALOI.DNGAYBANHANH BETWEEN p_NGAYTRALOI_FROM AND p_NGAYTRALOI_TO)
        AND (p_NGAYNHAN_FROM IS NULL OR KN_KIENNGHI.DDATE >= p_NGAYNHAN_FROM)
        AND (p_NGAYNHAN_TO IS NULL OR KN_KIENNGHI.DDATE <= p_NGAYNHAN_TO)
        ),
        KN_GOP AS (SELECT DISTINCT KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP, QUOCHOI_COQUAN.CTEN AS TENCOQUAN FROM 
                KN_KIENNGHI LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN =KN_KIENNGHI.IDONVITIEPNHAN
                WHERE KN_KIENNGHI.ID_GOP>0 AND (p_IKYHOP=0 OR KN_KIENNGHI.IKYHOP=p_IKYHOP) ORDER BY KN_KIENNGHI.ID_GOP),
--        TBL3 as( select COALESCE(KN_GOP.ID_KIENNGHI_PARENT_GOP,0) AS ID_KIENNGHI_PARENT_GOP,
--            LISTAGG( convert(KN_GOP.TENCOQUAN, 'UTF8', 'AL32UTF8'), ', ') WITHIN GROUP 
--            (ORDER BY KN_GOP.ID_KIENNGHI_PARENT_GOP) TENDONVITIEPNHAN_GOP FROM KN_GOP GROUP BY KN_GOP.ID_KIENNGHI_PARENT_GOP),
        TBL4 AS(SELECT TBL1.* FROM TBL1 
           WHERE 
            TBL1.ITINHTRANG BETWEEN p_TINHTRANG_FROM AND p_TINHTRANG_TO 
--            AND (p_KETQUA_GIAMSAT=-1 OR TBL1.GIAMSAT_DONGKIENNGHI=p_KETQUA_GIAMSAT)            
--            AND (p_DA_TRALOI=-1 OR TBL1.DATRALOI=p_DA_TRALOI) 
            ORDER BY TBL1.ID_THAMQUYEN_DONVI,TBL1.ID_LINHVUC
        )
        SELECT * FROM 
        (
            SELECT k.*,(SELECT COUNT(*) FROM TBL4) AS TOTAL, 
            ROWNUM r_ FROM( select * from TBL4 ) k
              WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
        ) 
        WHERE r_>=    (((p_PAGE-1) * p_PAGE_SIZE) + 1)
         ;
END PRC_KIENNGHI_LIST_TRACUU;