create or replace PROCEDURE "PRC_KIENNGHI_TAMXOA" 
(
    p_IUSER IN NUMBER,
    p_LSTLINHVUC IN VARCHAR2,
    p_IDONVITIEPNHAN IN NUMBER,
    p_LSTNGUONKN IN VARCHAR2,
    p_IKYHOP IN NUMBER,
    p_ITRUOCKYHOP IN NUMBER,
    p_ITHAMQUYENDONVI_PARENT IN NUMBER,
    p_ITHAMQUYENDONVI IN NUMBER,
    p_CNOIDUNG IN NVARCHAR2,
    p_LISTKYHOP IN NVARCHAR2,
    p_MAKIENNGHI IN NVARCHAR2,
    p_TUNGAY IN DATE,
    p_DENNGAY IN DATE,
    p_PAGE IN NUMBER,
    p_PAGE_SIZE IN NUMBER,
    res OUT sys_refcursor
) IS 
BEGIN
    Open res for
    WITH TBL1 AS
    ( SELECT  KN_KIENNGHI.IKIENNGHI AS ID_KIENNGHI, KN_KIENNGHI.ID_GOP, KN_KIENNGHI.IUSER AS ID_USER_CAPNHAT,
              KN_KIENNGHI.IKIENNGHI_TRUNG AS ID_KIENNGHI_TRUNG, KN_KIENNGHI.ITONGHOP AS ID_KIENNGHI_TONGHOP,
              KN_KIENNGHI.ITONGHOP_BDN AS ID_KIENNGHI_TONGHOP_BDN, KN_KIENNGHI.IDONVITIEPNHAN AS ID_DONVITIEPNHAN,
              0 AS SOLUONG_KIENNGHI_GOP,
              COQUAN_TIEPNHAN.CTEN AS TEN_DONVITIEPNHAN,
              KN_KIENNGHI.ITHAMQUYENDONVI AS ID_THAMQUYEN_DONVI,KN_KIENNGHI.ILINHVUC AS ID_LINHVUC,ITINHTRANG,
              COQUAN_THAMQUYEN.IPARENT AS ID_PARENT_THAMQUYEN_DONVI,USERS.IDONVI AS ID_DONVI_CAPNHAT,
              COQUAN_THAMQUYEN.CTEN AS TEN_THAMQUYEN_DONVI,LINHVUC_COQUAN.CTEN AS TEN_LINHVUC,              
              KN_KIENNGHI.CNOIDUNG AS NOIDUNG_KIENNGHI, KN_KIENNGHI.IKYHOP
      FROM KN_KIENNGHI 
      LEFT JOIN QUOCHOI_COQUAN COQUAN_TIEPNHAN ON KN_KIENNGHI.IDONVITIEPNHAN=COQUAN_TIEPNHAN.ICOQUAN
      LEFT JOIN QUOCHOI_COQUAN COQUAN_THAMQUYEN ON KN_KIENNGHI.ITHAMQUYENDONVI=COQUAN_THAMQUYEN.ICOQUAN
      LEFT JOIN USERS ON USERS.IUSER=KN_KIENNGHI.IUSER
      LEFT JOIN LINHVUC_COQUAN ON LINHVUC_COQUAN.ILINHVUC=KN_KIENNGHI.ILINHVUC
      INNER JOIN KIENNGHI_NGUONDON on KN_KIENNGHI.IKIENNGHI = KIENNGHI_NGUONDON.IKIENNGHI
      INNER JOIN KN_NGUONDON on KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
        WHERE ID_GOP<=0 AND 
        KN_KIENNGHI.IDELETE=1 AND
        --(p_IKYHOP=0 OR KN_KIENNGHI.IKYHOP=p_IKYHOP or 
				(KN_KIENNGHI.IKYHOP IN (select regexp_substr(p_LISTKYHOP,'[^,]+', 1, level)
					from dual
					connect BY regexp_substr(p_LISTKYHOP, '[^,]+', 1, level)
					is not null) OR p_LISTKYHOP = '0')  
        AND (p_LSTNGUONKN IS NULL  OR  KN_NGUONDON.INGUONDON IN ( Select Regexp_Substr(p_LSTNGUONKN,'[^,]+',1,Level) INGUONDON From Dual Connect By Regexp_Substr(p_LSTNGUONKN,'[^,]+',1,Level) Is Not Null)) 
        AND (p_ITHAMQUYENDONVI_PARENT=0 OR COQUAN_THAMQUYEN.IPARENT=p_ITHAMQUYENDONVI_PARENT)
        AND (p_LSTLINHVUC IS NULL OR LINHVUC_COQUAN.ILINHVUC IN (select regexp_substr(p_LSTLINHVUC,'[^,]+', 1, level) from dual connect BY regexp_substr(p_LSTLINHVUC, '[^,]+', 1, level) is not null)
            OR LINHVUC_COQUAN.IPARENT IN (select regexp_substr(p_LSTLINHVUC,'[^,]+', 1, level) from dual connect BY regexp_substr(p_LSTLINHVUC, '[^,]+', 1, level) is not null))
        AND (p_IDONVITIEPNHAN=0 OR KN_KIENNGHI.IDONVITIEPNHAN=p_IDONVITIEPNHAN)
        AND (p_ITRUOCKYHOP=-1 OR KN_KIENNGHI.ITRUOCKYHOP=p_ITRUOCKYHOP)
        AND UPPER(KN_KIENNGHI.CMAKIENNGHI) LIKE '%' || UPPER(p_MAKIENNGHI) || '%'
        AND (p_TUNGAY is null OR KN_KIENNGHI.INGAYQUYDINH >= p_TUNGAY)
        AND (p_DENNGAY is null OR KN_KIENNGHI.INGAYQUYDINH <= p_DENNGAY)
        AND (p_ITHAMQUYENDONVI=0 OR KN_KIENNGHI.ITHAMQUYENDONVI=p_ITHAMQUYENDONVI) 
        AND (p_IUSER=0 OR KN_KIENNGHI.IUSER=p_IUSER)
        AND UPPER(KN_KIENNGHI.CNOIDUNG) LIKE '%' || UPPER(p_CNOIDUNG) || '%'
        ),
        KN_GOP AS (SELECT DISTINCT KN_KIENNGHI.ID_GOP AS ID_KIENNGHI_PARENT_GOP, QUOCHOI_COQUAN.CTEN AS TENCOQUAN FROM 
                KN_KIENNGHI LEFT JOIN QUOCHOI_COQUAN ON QUOCHOI_COQUAN.ICOQUAN =KN_KIENNGHI.IDONVITIEPNHAN
                WHERE KN_KIENNGHI.IDELETE=1 AND KN_KIENNGHI.ID_GOP>0 AND (p_IKYHOP=0 OR KN_KIENNGHI.IKYHOP=p_IKYHOP) ORDER BY KN_KIENNGHI.ID_GOP),
        TBL2 as( select  KN_GOP.ID_KIENNGHI_PARENT_GOP AS ID_KIENNGHI_PARENT_GOP,
            LISTAGG( convert(KN_GOP.TENCOQUAN, 'UTF8', 'AL32UTF8'), ', ') WITHIN GROUP 
            (ORDER BY KN_GOP.ID_KIENNGHI_PARENT_GOP) TENDONVITIEPNHAN_GOP FROM KN_GOP GROUP BY KN_GOP.ID_KIENNGHI_PARENT_GOP             
            ),
        TBL3 AS(
        SELECT * FROM TBL1 LEFT JOIN TBL2 ON TBL1.ID_KIENNGHI=TBL2.ID_KIENNGHI_PARENT_GOP
        WHERE (TBL1.ITINHTRANG=0 OR (TBL1.ITINHTRANG=0 AND (p_IUSER=0 OR TBL1.ID_USER_CAPNHAT=p_IUSER) ))
        ORDER BY TBL1.ID_THAMQUYEN_DONVI,TBL1.ID_LINHVUC,TBL1.ID_KIENNGHI)
        SELECT * FROM 
        (
            SELECT k.*,(SELECT COUNT(*) FROM TBL3) AS TOTAL, 
            ROWNUM r_ FROM( select * from TBL3 ) k
              WHERE ROWNUM < ((p_PAGE * p_PAGE_SIZE) + 1 )
        ) 
        WHERE r_>=    (((p_PAGE-1) * p_PAGE_SIZE) + 1);
END PRC_KIENNGHI_TAMXOA;