create or replace PROCEDURE "RPT_KN_HDND_DANHMUCCUTRI_1A" 
(
        p_IUSER IN NUMBER,
        lstKyHop IN VARCHAR2,
        lstNguonKN IN VARCHAR2,
        lstLinhVuc IN VARCHAR2,
        loaibaocao IN INT,
        res  OUT sys_refcursor
)
IS 
BEGIN

OPEN res FOR  
   SELECT to_char( ROW_NUMBER() OVER (ORDER BY IKIENNGHI)) AS TT, TBL.SOKIENNGHI, TBL.NOIDUNGKIENNGHI, TBL.GHICHU, TBL.DIAPHUONG, TBL.IKYHOP,
    CASE WHEN TBL.LINHVUC = 1 THEN  CTEN WHEN TBL.ILINHVUCPARENT = 1 THEN  CTEN ELSE '' END COCHE_CHINHSACH,
    CASE WHEN TBL.LINHVUC = 2 THEN  CTEN WHEN TBL.ILINHVUCPARENT = 2 THEN  CTEN ELSE '' END KINHTE_NGANSACH,
    CASE WHEN TBL.LINHVUC = 3 THEN  CTEN WHEN TBL.ILINHVUCPARENT = 3 THEN  CTEN ELSE '' END VANHOA_XAHOI,
    CASE WHEN TBL.LINHVUC = 4 THEN  CTEN WHEN TBL.ILINHVUCPARENT = 4 THEN  CTEN ELSE '' END TUPHAP,
    CASE WHEN TBL.LINHVUC = 5 THEN  CTEN WHEN TBL.ILINHVUCPARENT = 5 THEN  CTEN ELSE '' END ANQP_KHAC
    FROM (
          SELECT 
            KN_KIENNGHI.CMAKIENNGHI AS SOKIENNGHI, KN_KIENNGHI.CNOIDUNG AS NOIDUNGKIENNGHI,KN_KIENNGHI.CGHICHU AS GHICHU, 
            KN_ND.DIAPHUONG AS DIAPHUONG,
            KN_KIENNGHI.ILINHVUC AS LINHVUC, LINHVUC_COQUAN.CTEN AS CTEN, LINHVUC_COQUAN.IPARENT AS ILINHVUCPARENT, KN_KIENNGHI.IKIENNGHI AS IKIENNGHI, LINHVUC_COQUAN.ILINHVUC, KN_KIENNGHI.IKYHOP
        FROM KN_KIENNGHI
        INNER JOIN
        (        
            SELECT KIENNGHI_NGUONDON.IKIENNGHI AS IKIENNGHI , LISTAGG(KN_NGUONDON.CTEN, ',') WITHIN GROUP (ORDER BY  KIENNGHI_NGUONDON.IKIENNGHI )AS  DIAPHUONG
            FROM KIENNGHI_NGUONDON
            INNER JOIN 
            (
                SELECT KIENNGHI_NGUONDON.IKIENNGHI AS IKIENNGHI , LISTAGG(KN_NGUONDON.CTEN, ',') WITHIN GROUP (ORDER BY  KIENNGHI_NGUONDON.IKIENNGHI )AS  DIAPHUONG
                FROM KIENNGHI_NGUONDON
                INNER JOIN KN_NGUONDON ON KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
                WHERE  (lstNguonKN = '' OR lstNguonKN IS NULL OR  KN_NGUONDON.INGUONDON IN (  Select Regexp_Substr(lstNguonKN,'[^,]+',1,Level) INGUONDON From Dual Connect By Regexp_Substr(lstNguonKN,'[^,]+',1,Level) Is Not Null))
                GROUP BY KIENNGHI_NGUONDON.IKIENNGHI
            ) KN_ND_SELECT ON KN_ND_SELECT.IKIENNGHI = KIENNGHI_NGUONDON.IKIENNGHI
            INNER JOIN KN_NGUONDON ON KN_NGUONDON.INGUONDON = KIENNGHI_NGUONDON.INGUONDON
            GROUP BY KIENNGHI_NGUONDON.IKIENNGHI       
        ) KN_ND ON KN_ND.IKIENNGHI = KN_KIENNGHI.IKIENNGHI
        LEFT JOIN LINHVUC_COQUAN ON KN_KIENNGHI.ILINHVUC = LINHVUC_COQUAN.ILINHVUC
        LEFT JOIN QUOCHOI_KYHOP ON KN_KIENNGHI.IKYHOP = QUOCHOI_KYHOP.IKYHOP
        where 
          (lstKyHop = '' OR lstKyHop IS NULL OR QUOCHOI_KYHOP.IKYHOP IN (  Select Regexp_Substr(lstKyHop,'[^,]+',1,Level) IKYHOP From  Dual Connect By Regexp_Substr(lstKyHop,'[^,]+',1,Level) Is Not Null))
          AND (lstLinhVuc = '' OR lstLinhVuc IS NULL OR  LINHVUC_COQUAN.ILINHVUC IN (  Select Regexp_Substr(lstLinhVuc,'[^,]+',1,Level) ILINHVUC From  Dual Connect By Regexp_Substr(lstLinhVuc,'[^,]+',1,Level) Is Not Null)
               OR LINHVUC_COQUAN.IPARENT IN (  Select Regexp_Substr(lstLinhVuc,'[^,]+',1,Level) ILINHVUC From  Dual Connect By Regexp_Substr(lstLinhVuc,'[^,]+',1,Level) Is Not Null) )
          AND KN_KIENNGHI.IDOITUONGGUI = (CASE WHEN loaibaocao = 2 THEN 1 ELSE 0 END)
          AND (p_IUSER = 0 OR KN_KIENNGHI.IUSER = p_IUSER)
          AND KN_KIENNGHI.ITINHTRANG=0 
          AND KN_KIENNGHI.IDELETE = 0
        ORDER BY KN_KIENNGHI.CMAKIENNGHI
        )  TBL;

END RPT_KN_HDND_DANHMUCCUTRI_1A;