create or replace PROCEDURE RPT_KNTC_BAOCAO_TONGHOPKETQUAXULYDON_4G
(
	iUserID IN NUMBER,
	iDoiTuong IN NUMBER,
	iTuNgay IN DATE,
	iDenNgay IN DATE,
	iTuNgayKyTruoc IN DATE,
	iDenNgayKyTruoc IN DATE,
    listDiaPhuongTimKiem IN NVARCHAR2,
	res OUT sys_refcursor
)
IS
BEGIN
OPEN res FOR
	WITH
	TONG_TIEP_NHAN AS (
		SELECT COUNT(*) AS COUNT_TONG_TIEP_NHAN_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR iUserID = kntcdon.iuser)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	TONG_DON_TRA_LOI AS (
		SELECT COUNT(*) AS COUNT_TONG_DON_TRA_LOI_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE
        (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ITINHTRANGXULY = 6 OR kntcdon.ITINHTRANGXULY = 7 OR kntcdon.ITINHTRANGXULY = 8 OR kntcdon.ITINHTRANGXULY = 9
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DON_KHIEU_NAI AS (
		SELECT COUNT(*) AS COUNT_DON_KHIEU_NAI_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ILOAIDON = 1
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
--	SODONDAXULY AS (
--		SELECT COUNT(*) AS COUNTSODONDAXULY_0, kntcdon.IDIAPHUONG_1
--		FROM KNTC_DON kntcdon
--		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
--            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
--            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
--            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
--            AND kntcdon.ILOAIDON = 2
--        GROUP BY kntcdon.IDIAPHUONG_1
--	),
	DON_TO_CAO AS (
		SELECT COUNT(*) AS COUNT_DON_TO_CAO_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ILOAIDON = 2
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DON_KN AS (
		SELECT COUNT(*) AS COUNT_DON_KN_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ILOAIDON = 3
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	ND_KHAC_NHAU AS (
		SELECT COUNT(*) AS COUNT_ND_KHAC_NHAU_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ILOAIDON = 4
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	HANH_CHINH AS (
		SELECT COUNT(*) AS COUNT_HANH_CHINH_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND (kntcdon.ILINHVUC = 1 OR kntcdon.ILINHVUC = 6 OR kntcdon.ILINHVUC = 11 OR kntcdon.ILINHVUC = 16)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	TUPHAP AS (
		SELECT COUNT(*) AS COUNT_TUPHAP_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND (kntcdon.ILINHVUC = 2 OR kntcdon.ILINHVUC = 7 OR kntcdon.ILINHVUC = 12 OR kntcdon.ILINHVUC = 17)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DANG AS (
		SELECT COUNT(*) AS COUNT_DANG_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND (kntcdon.ILINHVUC = 3 OR kntcdon.ILINHVUC = 8 OR kntcdon.ILINHVUC = 13 OR kntcdon.ILINHVUC = 18)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	THAM_NHUNG AS (
		SELECT COUNT(*) AS COUNT_THAM_NHUNG_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND (kntcdon.ILINHVUC = 4 OR kntcdon.ILINHVUC = 9 OR kntcdon.ILINHVUC = 14 OR kntcdon.ILINHVUC = 19)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	LINH_VUC_KHAC AS (
		SELECT COUNT(*) AS COUNT_LINH_VUC_KHAC_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND (kntcdon.ILINHVUC = 5 OR kntcdon.ILINHVUC = 10 OR kntcdon.ILINHVUC = 15 OR kntcdon.ILINHVUC = 20)
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DON_TRUNG AS (
		SELECT COUNT(*) AS COUNT_DON_TRUNG_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 0 AND (kntcdon.IDONTRUNG != 0 OR kntcdon.IDONTRUNG != -1)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DONDUDK AS (
		SELECT COUNT(*) AS COUNT_DONDUDK_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	DONKODUDK AS (
		SELECT COUNT(*) AS COUNT_DONKODUDK_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 0
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
	CHUYEN_GIAI_QUYET AS (
		SELECT COUNT(*) AS COUNT_CHUYEN_GIAI_QUYET_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 AND (kntcdon.ITINHTRANGXULY = 3 OR kntcdon.ITINHTRANGXULY = 6 OR kntcdon.ITINHTRANGXULY = 7 OR kntcdon.ITINHTRANGXULY = 8 OR kntcdon.ITINHTRANGXULY = 9)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    DON_DOC_CQTQ AS (
		SELECT COUNT(*) AS COUNT_DON_DOC_CQTQ_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        INNER JOIN KNTC_VANBAN kntcvb on kntcvb.IDON = kntcdon.IDON
		WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1
            AND kntcvb.CLOAI = 'vanbandondocthuchien'
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    TRA_LOI_HD AS (
		SELECT COUNT(*) AS COUNT_TRA_LOI_HD_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 AND kntcdon.ITINHTRANGXULY = 10
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    DANG_NGHIEN_CUU AS (
		SELECT COUNT(*) AS COUNT_DANG_NGHIEN_CUU_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 AND kntcdon.ITINHTRANGXULY = 10
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    LUU_THEO_DOI AS (
		SELECT COUNT(*) AS COUNT_LUU_THEO_DOI_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 AND kntcdon.ITINHTRANGXULY = 5
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    NHAN_TRA_LOI AS (
		SELECT COUNT(*) AS COUNT_NHAN_TRA_LOI_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.IDUDIEUKIEN = 1 AND (kntcdon.ITINHTRANGXULY = 6 OR kntcdon.ITINHTRANGXULY = 7 OR kntcdon.ITINHTRANGXULY = 8 OR kntcdon.ITINHTRANGXULY = 9)
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    TONG_DON_LUU AS (
		SELECT COUNT(*) AS COUNT_TONG_DON_LUU_0, kntcdon.IDIAPHUONG_1
		FROM KNTC_DON kntcdon
        WHERE (iTuNgay IS NULL OR iTuNgay = '' OR kntcdon.DNGAYNHAN >= iTuNgay)
            AND (iDenNgay IS NULL OR iDenNgay = '' OR kntcdon.DNGAYNHAN <= iDenNgay)
            AND (iDoiTuong IS NULL OR kntcdon.IDOITUONGGUI = iDoiTuong)
            AND (iUserID = 0 OR iUserID IS NULL OR kntcdon.iuser = iUserID)
            AND kntcdon.ITINHTRANGXULY = 5
            AND kntcdon.IDELETE = 0
        GROUP BY kntcdon.IDIAPHUONG_1
	),
    TAT_CA_KNTC_DIAPHUONG1 AS (
        SELECT COUNT(*) AS COUNT_TONG
        FROM KNTC_DON kntcdon WHERE kntcdon.IDIAPHUONG_1 != 0 OR kntcdon.IDIAPHUONG_1 IS NOT NULL
        AND kntcdon.IDELETE = 0
    )
SELECT DIAPHUONG.IDIAPHUONG, TONG_TIEP_NHAN.IDIAPHUONG_1,
       to_char( ROW_NUMBER() OVER (ORDER BY DIAPHUONG.IDIAPHUONG)) || '. ' || DIAPHUONG.CTEN AS DIAPHUONG1,
--        TAT_CA_KNTC_DIAPHUONG1.COUNT_TONG,
       TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0 AS COUNT_TONG_TIEP_NHAN,
--        DON_KHIEU_NAI.COUNT_DON_KHIEU_NAI_0,
--        DON_TO_CAO.COUNT_DON_TO_CAO_0,
       TONG_DON_TRA_LOI.COUNT_TONG_DON_TRA_LOI_0 AS COUNT_TONG_DON_TRA_LOI,
       CASE WHEN TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0/TAT_CA_KNTC_DIAPHUONG1.COUNT_TONG*100 = 0 THEN 0 ELSE ROUND(TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0/TAT_CA_KNTC_DIAPHUONG1.COUNT_TONG*100, 2) END TYLE1,
       CASE WHEN DON_KHIEU_NAI.COUNT_DON_KHIEU_NAI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DON_KHIEU_NAI.COUNT_DON_KHIEU_NAI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DON_KHIEU_NAI,
       CASE WHEN DON_TO_CAO.COUNT_DON_TO_CAO_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DON_TO_CAO.COUNT_DON_TO_CAO_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DON_TO_CAO,
       CASE WHEN DON_KN.COUNT_DON_KN_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DON_KN.COUNT_DON_KN_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DON_KN,
       CASE WHEN ND_KHAC_NHAU.COUNT_ND_KHAC_NHAU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(ND_KHAC_NHAU.COUNT_ND_KHAC_NHAU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_ND_KHAC_NHAU,
       CASE WHEN HANH_CHINH.COUNT_HANH_CHINH_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(HANH_CHINH.COUNT_HANH_CHINH_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_HANH_CHINH,
       CASE WHEN TUPHAP.COUNT_TUPHAP_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(TUPHAP.COUNT_TUPHAP_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_TUPHAP,
       CASE WHEN THAM_NHUNG.COUNT_THAM_NHUNG_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(THAM_NHUNG.COUNT_THAM_NHUNG_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_THAM_NHUNG,
       CASE WHEN LINH_VUC_KHAC.COUNT_LINH_VUC_KHAC_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(LINH_VUC_KHAC.COUNT_LINH_VUC_KHAC_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_LINH_VUC_KHAC,
       CASE WHEN DON_TRUNG.COUNT_DON_TRUNG_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DON_TRUNG.COUNT_DON_TRUNG_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DON_TRUNG,
       CASE WHEN DONDUDK.COUNT_DONDUDK_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DONDUDK.COUNT_DONDUDK_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DONDUDK,
       CASE WHEN DONKODUDK.COUNT_DONKODUDK_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DONKODUDK.COUNT_DONKODUDK_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DONKODUDK,
       CASE WHEN CHUYEN_GIAI_QUYET.COUNT_CHUYEN_GIAI_QUYET_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(CHUYEN_GIAI_QUYET.COUNT_CHUYEN_GIAI_QUYET_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_CHUYEN_GIAI_QUYET,
       CASE WHEN DON_DOC_CQTQ.COUNT_DON_DOC_CQTQ_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DON_DOC_CQTQ.COUNT_DON_DOC_CQTQ_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DON_DOC_CQTQ,
       CASE WHEN TRA_LOI_HD.COUNT_TRA_LOI_HD_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(TRA_LOI_HD.COUNT_TRA_LOI_HD_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_TRA_LOI_HD,
       CASE WHEN DANG_NGHIEN_CUU.COUNT_DANG_NGHIEN_CUU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(DANG_NGHIEN_CUU.COUNT_DANG_NGHIEN_CUU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_DANG_NGHIEN_CUU,
       CASE WHEN LUU_THEO_DOI.COUNT_LUU_THEO_DOI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(LUU_THEO_DOI.COUNT_LUU_THEO_DOI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_LUU_THEO_DOI,
       CASE WHEN NHAN_TRA_LOI.COUNT_NHAN_TRA_LOI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(NHAN_TRA_LOI.COUNT_NHAN_TRA_LOI_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END COUNT_NHAN_TRA_LOI,
       CASE WHEN TONG_DON_LUU.COUNT_TONG_DON_LUU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100 = 0 THEN 0 ELSE ROUND(TONG_DON_LUU.COUNT_TONG_DON_LUU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) END TYLE2,
--        ROUND(TONG_DON_LUU.COUNT_TONG_DON_LUU_0/TONG_TIEP_NHAN.COUNT_TONG_TIEP_NHAN_0*100, 2) AS TYLE2,
       TONG_DON_LUU.COUNT_TONG_DON_LUU_0 AS COUNT_TONG_DON_LUU
FROM DIAPHUONG
         INNER JOIN TONG_TIEP_NHAN ON DIAPHUONG.IDIAPHUONG = TONG_TIEP_NHAN.IDIAPHUONG_1
         LEFT JOIN TONG_DON_TRA_LOI ON DIAPHUONG.IDIAPHUONG = TONG_DON_TRA_LOI.IDIAPHUONG_1
         LEFT JOIN DON_KHIEU_NAI ON DIAPHUONG.IDIAPHUONG = DON_KHIEU_NAI.IDIAPHUONG_1
         LEFT JOIN DON_TO_CAO ON DIAPHUONG.IDIAPHUONG = DON_TO_CAO.IDIAPHUONG_1
         LEFT JOIN DON_KN ON DIAPHUONG.IDIAPHUONG = DON_KN.IDIAPHUONG_1
         LEFT JOIN ND_KHAC_NHAU ON DIAPHUONG.IDIAPHUONG = ND_KHAC_NHAU.IDIAPHUONG_1
         LEFT JOIN HANH_CHINH ON DIAPHUONG.IDIAPHUONG = HANH_CHINH.IDIAPHUONG_1
         LEFT JOIN TUPHAP ON DIAPHUONG.IDIAPHUONG = TUPHAP.IDIAPHUONG_1
         LEFT JOIN DANG ON DIAPHUONG.IDIAPHUONG = DANG.IDIAPHUONG_1
         LEFT JOIN THAM_NHUNG ON DIAPHUONG.IDIAPHUONG = THAM_NHUNG.IDIAPHUONG_1
         LEFT JOIN LINH_VUC_KHAC ON DIAPHUONG.IDIAPHUONG = LINH_VUC_KHAC.IDIAPHUONG_1
         LEFT JOIN DON_TRUNG ON DIAPHUONG.IDIAPHUONG = DON_TRUNG.IDIAPHUONG_1
         LEFT JOIN DONDUDK ON DIAPHUONG.IDIAPHUONG = DONDUDK.IDIAPHUONG_1
         LEFT JOIN DONKODUDK ON DIAPHUONG.IDIAPHUONG = DONKODUDK.IDIAPHUONG_1
         LEFT JOIN CHUYEN_GIAI_QUYET ON DIAPHUONG.IDIAPHUONG = CHUYEN_GIAI_QUYET.IDIAPHUONG_1
         LEFT JOIN DON_DOC_CQTQ ON DIAPHUONG.IDIAPHUONG = DON_DOC_CQTQ.IDIAPHUONG_1
         LEFT JOIN TRA_LOI_HD ON DIAPHUONG.IDIAPHUONG = TRA_LOI_HD.IDIAPHUONG_1
         LEFT JOIN DANG_NGHIEN_CUU ON DIAPHUONG.IDIAPHUONG = DANG_NGHIEN_CUU.IDIAPHUONG_1
         LEFT JOIN LUU_THEO_DOI ON DIAPHUONG.IDIAPHUONG = LUU_THEO_DOI.IDIAPHUONG_1
         LEFT JOIN NHAN_TRA_LOI ON DIAPHUONG.IDIAPHUONG = NHAN_TRA_LOI.IDIAPHUONG_1
         LEFT JOIN TONG_DON_LUU ON DIAPHUONG.IDIAPHUONG = TONG_DON_LUU.IDIAPHUONG_1
   , TAT_CA_KNTC_DIAPHUONG1
WHERE DIAPHUONG.IPARENT = 26
  AND (listDiaPhuongTimKiem = '' OR listDiaPhuongTimKiem IS NULL
    OR (DIAPHUONG.IDIAPHUONG IN (Select Regexp_Substr(listDiaPhuongTimKiem,'[^,]+',1,Level) IDIAPHUONG0 From Dual Connect By Regexp_Substr(listDiaPhuongTimKiem,'[^,]+',1,Level) Is Not Null)))
ORDER BY DIAPHUONG.IDIAPHUONG ASC
;


END RPT_KNTC_BAOCAO_TONGHOPKETQUAXULYDON_4G;