TRUNCATE TABLE "KNTC_LOAIDON";
INSERT INTO "KNTC_LOAIDON"("ILOAIDON", "CTEN", "IHIENTHI", "IDELETE", "IMALOAIDON", "CCODE", "IVITRI", "IPARENT") VALUES ('1', 'Đơn khiếu nại', '1', '0', '1', 'KN', '1', '0');
INSERT INTO "KNTC_LOAIDON"("ILOAIDON", "CTEN", "IHIENTHI", "IDELETE", "IMALOAIDON", "CCODE", "IVITRI", "IPARENT") VALUES ('2', 'Đơn tố cáo', '1', '0', '2', 'TC', '2', '0');
INSERT INTO "KNTC_LOAIDON"("ILOAIDON", "CTEN", "IHIENTHI", "IDELETE", "IMALOAIDON", "CCODE", "IVITRI", "IPARENT") VALUES ('3', 'Đơn kiến nghị, phản ánh', '1', '0', '3', 'KNPA', '3', '0');
INSERT INTO "KNTC_LOAIDON"("ILOAIDON", "CTEN", "IHIENTHI", "IDELETE", "IMALOAIDON", "CCODE", "IVITRI", "IPARENT") VALUES ('4', 'Đơn có nhiều nội dung khác nhau', '1', '0', NULL, 'TCDD', '5', NULL);
