TRUNCATE TABLE "USER_CHUCVU";
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('42', 'Chuyên viên', '0', '008', '1', '67');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('37', 'Trưởng phòng', '0', '003', '1', '66');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('38', 'Chuyên viên', '0', '004', '1', '66');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('40', 'Chuyên viên', '0', '006', '1', '50');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('39', 'Trưởng phòng', '0', '005', '1', '50');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('35', 'Trưởng phòng', '0', '001', '1', '49');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('36', 'Chuyên viên', '0', '002', '1', '49');
INSERT INTO "USER_CHUCVU"("ICHUCVU", "CTEN", "IDELETE", "CCODE", "IVITRI", "IPHONGBAN") VALUES ('41', 'Trưởng phòng', '0', '007', '1', '67');
